- Dockerfile-nb
- README.md
- docker-compose-notebook.yml
- localdev/app.ipynb.example
No ticket
- Updates README, which is out of date in the cookie cutter
- Set mailgun vars to no longer be mandatory (`MANDATORY_SETTINGS` appears to be removed in open-discussions, so it's likely we should remove it here too, but that could be done in a separate PR)
- Added notebook container
All 3 of these changes should probably be applied in some way to the cookie cutter
> Updated readme, un-required mailgun vars, added notebook container

- config/nginx.conf
None
Fixes static file serving. We are using dj-static for this on our other projects but I removed it from the cookiecutter for some reason. I think it's unnecessary anyway, we can just have nginx serve this file.
Go to /admin and verify that everything looks appropriate.
> Add rule to serve static files on dev environments

- pytest.ini
N/A
Fixes the test environment so that tests pass locally
- Under `master` branch, set `MITXPRO_USE_S3=True` and `AWS_*` vars to configure S3 file uploading
- Run `docker-compose run web pytest` and see it fail
- Checkout this branch and verify all tests pass now
> Fixed settings tests locally

- Dockerfile
Fixes #91
Bumps dockerfile to use stretch instead of jessie
Travis should pass again, `docker-compose build web` and `docker-compose up` app should still work
> Bump docker to stretch debian

- ecommerce/conftest.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/urls.py
- ecommerce/views.py
- ecommerce/views_test.py
- fixtures/common.py
Based on #115
Partially addresses #107 and #15
- Adds an API view for creating coupons
- Adds an API view for listing products (needed by coupon creation form)
- Adds a view for downloading a csv of coupon codes associated with a `CouponPaymentVersion`
- Log in as a staff user.
- Post data like this to `/api/coupons` for creating multiple single-use coupons:
```
{                       "tag": "FAKETAG", 
"name": "FAKENAME",
"automatic": true,
"activation_date": "2018-01-01T00:00:00Z",
"expiration_date": "2019-12-31T00:00:00Z",
"amount": 0.75,
"num_coupon_codes": 2,
"coupon_type": "single-use",
"company": "Acme Corp.",
"payment_type": "credit_card",
"payment_transaction": "fakeorderid",
"products": [1]
}
```
This should generate 2 `Coupon` objects with different random `coupon_code`s, 2 …
> API view for creating coupons

- docs/configure_open_edx.md
Part of #103 
Update documentation on how to configure `mitxpro-openedx-extensions` and other settings which were required for CI/RC, but default to correct settings on devstack
Follow the new installation steps and verify xPro and edX still function correctly, albeit with a redirect to xPro if you're not logged in
> Update edx configuration docs to match latest setup

- conftest.py
N/A
Fixes an autouse fixture when testing only a subset of the suite.
Tests should pass and you should see that `pytest courseware/` passes in theis branch but fails on master.
> Fix running pytest for a subset of tests that don't create TEST_MEDIA_ROOT

- courseware/api.py
- courseware/api_test.py
- courseware/factories.py
- ecommerce/conftest.py
Fixes #99 
Refractors the existing method used to acquire a new set of tokens only if they are going to expire and does via a lock on the row.
Verify you can still enroll in a course
> Updated OpenEdxApiAuth refresh to account for expiration

- travis/js_tests.sh
- travis/python_tests.sh
No ticket, just a simple improvement
For each test suite step/command in the Python or JS travis scripts, the command is echo'ed before it's run. This should help us to visually (and programatically) parse a job log from a Travis build
Run `travis/js_tests.sh` and `travis/python_tests.sh`, make sure it looks nice
> Added test script detail to Travis output

- ecommerce/api.py
- ecommerce/api_test.py
Part of #233 
Removes cancel override field and updates the receipt override field to redirect users to `/dashboard` so that CyberSource checkout will go through.
Checkout should work (no need to verify order fulfillment)
> Redirect users to /dashboard after CyberSource checkout

- static/scss/resource.scss
Fixes #245 
Fix path of banner image on resource pages.
- Add resource page.
- View its live version.
- Banner image should load.
> fix static path of banner image

- mitxpro/views.py
- mitxpro/views_test.py
Fixes #241 
Adds `@csrf_exempt` to allow POST to `/dashboard` and other HTML pages which use the same `index` view. This allows CyberSource to POST to this page without causing a CSRF error. 
Run `curl -XPOST http://mitxpro.mit.local:8053/dashboard/`. On master you should see text about a CSRF validation error, but on this branch it should show a little bit of HTML.
> Don't check CSRF token for index pages

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/conftest.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
Related to #212 
- Adds optional keyword arguments for `get_valid_coupon_versions` to filter by company and/or 100% off discounts
- Improves efficiency/speed of the  query
- Removes the `best_coupon_for_basket` function and tests because it's no longer used
- Improves efficiency of batch coupon creation via `bulk_create`
Unit tests should still pass, any valid coupons you have should still be valid.
> Additional kwargs, better efficiency for get_valid_coupon_versions query

- courses/admin.py
- courses/views_test.py
- mitxpro/urls.py
- mitxpro/urls_test.py
- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/scss/dashboard.scss
No ticket
- fixed dashboard style regressions at mobile width
- added a simple message to the dashboard if a user has no enrollments
- added rule to serve course catalog at root route (this will eventually be replaced by the actual home page - #246)
- added enrollment admin classes
- Check dashboard at multiple screen widths
- Go to the root URL of the app and make sure you see the course catalog
> Misc. improvements - dashboard style, root route, enrollment admin

- static/js/containers/pages/DashboardPage.js
- static/scss/dashboard.scss
No ticket 
#285 fixed the dashboard styling after a regression, but the root cause of that regression was fixed, so the styling regressed again. This PR un-regresses the regression regression.
It also makes sure that the product type flags appear above the product images in the mobile view
Look at the dashboard
> Fixed dashboard styling again

- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
Fixes #268 
Fixes logic on frontend where the coupon code submitted and the one rendered in the text field were calculated differently.
Apply a coupon. Refresh the page. Click the "Apply" button next to the coupon code. Nothing should appear to change. If you look in the network tab you should see a successful PATCH to the basket with the coupon code. On master you would see the coupon being removed from the basket, which is incorrect.
> Fix coupon apply button bug

- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/lib/ecommerce.js
- static/js/lib/form.js
- static/js/lib/form_test.js
Fixes #121 
Uses query parameters to populate the basket on checkout page load. This will allow links from the catalog pages to the checkout page.
Go to `/checkout/?product_id=123456` where `123456` is a valid `ProductVersion` id. You should see that page loaded. If you go to `?product_id=123456&code=xyz` for a valid coupon code, it should automatically apply the discount and show it on the checkout page.
If you have no query parameters, it should show you whatever your basket looked like previously.
If you have an invalid product id, the page should load with whatever the old basket content was and an error message should be displayed at the bottom of the screen. This is a rare case so the error message won't be more prominent than that.
If you have an invalid coupon code, the page …
> Use query parameters when loading checkout page

- courses/templates/course_app_base.html
- mitxpro/templates/base.html
- mitxpro/templates/resource_template.html
- mitxpro/views_test.py
#329 
Removes bug introduced by #311 
Go to any React rendered page, the header should appear only once, not duplicated.
> Move Header Bundle back to Original Location

- compliance/api.py
- compliance/api_test.py
Fixes #327 
This fixes an issue where the encrypted responses were being encoded as raw byte strings, which made them more difficult to decrypt later on. This changes that to base64 encode them since we're storing them on a `TextField`
Tests passing should be sufficient since they check that the records can be decrypted with the private key and they match the input. Feel free to manually perform what the new test added here does though if you wish to verify this independently.
> Fixed encrypted response getting ascii-escaped

- courses/models.py
- courses/models_test.py
- courses/templates/partials/hero.html
- courses/views.py
- courses/views_test.py
- static/scss/detail/header.scss
Fixes #101 
Adds a link, styled as a button, which will direct the user to purchase the product for the next unexpired
course run for the course, or to view the course in edX if they are already enrolled. 
Have a course with an unexpired course run, and make sure a `Product` and `ProductVersion` exist for that course run. Visit the course product page and you should see an "Enroll now" link. Click on it and you should be directed to the checkout page with the course run listed as the item on the checkout page.
To test the 'View course' link, it may be easiest to just fake a couple things:
- update `courseware_url_path` on the `CourseRun` you created to have some path, as long as it's not none. The link may not work but it will show up at least. 
- Create `CourseRunEnrollment` between your …
> Enroll/View Dashboard button

- static/js/notifications.js
Fixes #349 
Add check in `notifications.js` to avoid error in console.
- Make sure, there is no notification available in CMS
- Render any page
- You should not see any error in console
> fix error in console when no notification available

- cms/models.py
#372 
Sets `HomePage` as a valid parent page class of `ResourcePage` so those instances can be moved/created under `HomePage`
Try to add a `ResourcePage` under a `HomePage` instance. The CMS should allow you to add that pagae.
> #372 Fix: Set HomePage as Parent of ResourcePage

- courses/templates/partials/metadata-tiles.html
Fixes #376 
Add check if there is only one date available, don't show more dates option.
- Make sure, you have course with only one open enrollment.
- Visit course page
- You should not see "More dates"
> fix if only one date available

- static/js/components/forms/RegisterEmailForm.js
- static/js/containers/pages/register/RegisterConfirmPage.js
- static/js/containers/pages/register/RegisterDetailsPage.js
- static/js/containers/pages/register/RegisterEmailPage.js
- static/js/containers/pages/register/RegisterEmailPage_test.js
Fixes #344 
Some of #312 
- Adds a redirect to `/login/password` if a user tries to register for an account that exists
- Adds test coverage for `RegisterEmailPage.js`
- Fixes some copy/paste typos on register page class names
- Go to /signup and try to register with an existing email, it should prompt you to enter password and you should be able to login.
- Go to /signup and verify you can still signup with an email that doesn't exist
> Added support for redirect on register existing email

- localdev/seed/api.py
- localdev/seed/api_test.py
- localdev/seed/management/commands/seed_data.py
- localdev/seed/resources/seed_data.json
#207 
Add sample resource pages for `terms of services`, `privacy policy` and `honor code`.
- Run management command `./manage.py seed_data`
- Click on links (`terms of services`, `privacy policy` and `honor code`.) in footer.
- You should see sample pages.
- `./manage.py seed_data --delete` this should delete seed data.
**Note:** Terms of services page will be shown after #399 merged.
> add seed resource pages in CMS

- static/js/components/forms/CouponForm.js
- static/js/containers/pages/admin/CreateCouponPage.js
- static/js/containers/pages/admin/CreateCouponPage_test.js
Closes #415 
- Sets max_redemptions to 1 for single-use coupons when creating them via the form.
- Removes 'Course' product listings option from coupon form (no longer allowed - related to #177)
Create a new single-use coupon with ~10 coupon codes.
Check the new `CouponPaymentVersion` from django admin and verify that `max_redemptions` and `max_redemptions_per_user` are both 1.
> max_redemptions should be 1 for single-use coupons

- cms/models.py
- cms/templates/partials/hero.html
- courses/views_test.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/views_test.py
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/factories/ecommerce.js
- static/js/flow/ecommerceTypes.js
Closes #418
Updates serializers and checkout page to accept Product id instead of ProductVersion id in parameters.
Try URL `http://xpro.odl.local:8053/checkout/?product=<courserun_product_id>`.  It should display the correct course run on the page, and you should be able to purchase it.
Try URL `http://xpro.odl.local:8053/checkout/?product=<program_product_id>`.  It should display the correct program on the page, and you should be able to select a course run for each course in the program and purchase the program.
Go to a courserun or program CMS page and click the enroll link, it should use the product id and not the product_version id.
> Accept product id, not product version id, on checkout page

- cms/templates/partials/metadata-tiles.html
- courses/models.py
- courses/models_test.py
Fixes #408 and #410
- Show price on course or program page.
- For courses show first unexpired course run price as course price.
**For courses:**
- Add product against course run which is set to be first unexpired course run in your course.
- Add product version for added product.
- View course page.
- You should see `Price` tile on course product page.
**For programs:**
- Add product against program
- Add product version for added product.
- View program page.
- You should see `Price` tile on program product page.
Initially price was present under `course`, after #336 it is moved under `courserun`. This PR will update the template to render price of first unexpired course run.
@pdpinch Your thoughts on rendering price of first unexpired course run?
**Course:**
**Program:**
> Fix missing price on product page

- courses/serializers.py
- courses/serializers_test.py
- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/serializers.py
- ecommerce/views_test.py
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/factories/course.js
- static/js/factories/ecommerce.js
- static/js/flow/courseTypes.js
#418 should be fixed first, this PR assumes `Product.id` and not `ProductVersion.id` is being used.
Closes #231 
Allows user to select alternate course runs on the checkout page, regardless of whether the current product is for a program or course run.
Try both `http://xpro.odl.local:80-53/checkout?product_id=<program>` and `http://xpro.odl.local:8053/checkout?product_id=<courserun>`
In each case, you should get a select list of alternate runs (if any) for the course(s).  The checkout page should work as before for programs.  For a course run, the product's course run should be selected by default.  If you switch to another course run and it has a different price, the price should update on the page.  If the coupon is no longer valid for the new course run it should disappear.
> Always show course run selections

- static/scss/detail/tiles.scss
Fixes #463 
Update styling of metadata tiles.
View course or program page.
**Desktop**
**Mobile**
> update styling of metadata tiles

- cms/templates/partials/course-carousel.html
- cms/templates/product_page.html
Closes #472 
Modifies product detail page to not show the "view full program" button in courseware carousel when it is on the program page as it just links to itself.
Visit a course page and then a program page. The "view full program" button should appear in the courseware carousel on the course page but not on the program page.
Course Page
Program Page
> #472 Program Page: don't show "view full program"

- cms/templates/partials/hero.html
#504 
Fixes bottom margins on the "Enroll Now" button so it doesn't get overlapped by video on product detail pages.
Go to any product detail page that has video configured (view in mobile device width). The "Enroll Now" button should appear with proper margins and it should not be overlapped by video as shown in the ticket.
> #504 Enroll Now Button Overlapped

- static/js/course_detail.js
#470
Modifies subnav scrolling to take into account of the navbar's own height while scrolling so content is not hidden behind the navbar (typically the heading of the section scrolled to).
On the product page, use the navbar to scroll to different sections. The page should scroll right up to the top of the section with the heading of the section not overlapped by the navbar.
> #470 Product page: Subnav scroll fix

- static/js/courseware_carousel.js
Closes #499 
Narrows the scope of click listener in courseware carousel to react only to clicks in the courseware carousel, not to react to clicks on any other carousel.
Go to any page that has the courseware carousel and any other carousel. The courseware carousel cards should be clickable and navigate to the detail page. Other carousel cards should not be clickable and function as expected.
> #499 Clicking on Continue Reading Leads to 404

- cms/templates/partials/courseware-carousel-base.html
Fixes #510 
Adds the missing `href` attribute to title anchor in courseware carousel cards.
Go to any page with a courseware carousel. Click on the title link, it should take you to the correct page.
> #510 Courseware carousel links not working

- cms/templates/partials/testimonial-carousel.html
Closes #469 
Modifies the testimonial carousel to not show the "continue reading" link if the testimonial content is less than truncation length (150 characters).
Add/Modify a testimonial to be less than/equal to 150 characters. View the relevant page on the website. The carousel should not display "continue reading" link for any of the testimonials with content up to 150 characters in length.
> #469 Testimonial Carousel Read More Link

- static/js/courseware_carousel.js
- static/js/faculty_carousel.js
- static/js/home_page.js
- static/js/testimonials_carousel.js
Closes #447
Switches `infinite` property to `false` on carousel settings that were missed in a previous PR.
Go to any carousel, try to scroll past the content in either direction. The slider should not wrap around and start from the beginning. It should end scroll at the end of the content.
> #447 Disable infinite scroll on carousels

- cms/templates/catalog_page.html
- static/js/tooltip.js
- static/scss/catalog/tabs.scss
#466 
Adds a hover popover to catalog tabs for programs and courses.
On catalog page, hover on the programs tab and courses tab. Respective tooltip should be visible.
> #466 Catalog: display popover on tab hover

- mitxpro/templates/footer.html
Fixes #468 
Modifies footer links to disable redirecting to page in a new tab. Now links open in the current tab.
Click on any link in the footer. The browser should be redirected in the currently open tab, not in a new tab.
> #468 Footer links should not spawn new tab

- cms/templates/partials/courseware-carousel-base.html
- cms/templates/partials/faculty-carousel.html
- static/scss/detail/courses-in-program.scss
- static/scss/detail/faculty.scss
Continues on from #503 that was closed by mistake and can't be reopened because the branch was squashed meanwhile.
> #448 Courseware: space between text/"view detail"

- static/scss/notification.scss
No ticket - bug introduced by an oversight in #438 
Fixes site-wide notification styling
Forgot to add this back in a previous PR
> Fixed site-wide notification styling

- static/js/containers/App.js
Fixes #419
See title
Try to access the checkout page as a logged-out and logged-in user. The former should redirect you to the login page with the checkout page as the "next" path
> Set checkout page to be accessible only to logged-in users

- app.json
- authentication/views.py
- mail/api.py
- mitxpro/settings.py
Fixes #516 
Add 'reply-to' email address in emails.
Try create an account, once you will get verification email. 
Click on reply, you will see `MITXPRO_REPLY_TO_ADDRESS` as reply-to address.
**NOTE:** Set `MITXPRO_REPLY_TO_ADDRESS` in your settings.
> add reply-to email address in emails

- static/scss/catalog/keep-me-posted.scss
- static/scss/detail/for-teams.scss
- static/scss/detail/text-video-section.scss
- static/scss/detail/who-should-enroll.scss
- static/scss/resource.scss
- static/scss/variables.scss
Fixes #490 
- Replace aqua color to more darker color.
- Where we are using dark theme, replace it with white color.
- Visit any course, program page or resource page.
- Try switching between dark/light themes on course/program.
- Note that aqua color has changed to darker on light themes, and changed to white on light theme.
Go through the designs provided at https://github.com/mitodl/mitxpro/issues/490#issuecomment-501434608
**Product page**
**Resource page**
**Question @pdpinch **
After changing aqua to darker, `Thank You` becomes more darker, should I change this to white?
> replace aqua color to more darker color

- cms/templates/partials/learning-outcomes.html
- static/scss/detail/learning-outcomes.scss
Fixes #203 
Fixes display of learning outcomes section (What You Will Learn) on product pages to not go out of its container at table width (768px).
Go to any product page which has the learning outcomes section. Resize viewport to 768px width. There should be no empty space to either sides of the page.
> #203 Product Page: fix right margin at 768px

- ecommerce/api_test.py
N/A
Hopefully fix a test that occasionally fails
Run `docker-compose run web pytest ecommerce/api_test.py` a few times, it should pass consistently.  It should also pass on travis consistently.
> Ensure order of runs is always the same to avoid test flakiness

- courses/api_test.py
- courses/models.py
- courses/models_test.py
- courses/serializers.py
- courses/serializers_test.py
- courses/views_test.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/views_test.py
- fixtures/common.py
Closes #422
- Modifies `CourseSerializer` to filter out runs that are no longer enrollable, and (if a request user is in the serializer context) course runs that the user is already enrolled in.
- Modifies `BucketSerializer` to pass on its context to `ProductVersionSerializer` and then on to `CourseSerializer`
- Modifies `CourseRun.is_not_beyond_enrollment` to also consider `enrollment_start`.
- Create 5+ runs for a course.  One run should have an `enrollment_start` date in the future, one should have an `enrollment_end` date in the past, one should have an `end_date` in the past, two should have some combination of null dates or real dates that should make it enrollable.
- Create `Product` and `ProductVersion` for each run.
- Go to the checkout page with one of the valid runs in your …
> Exclude expired and enrolled runs from courserun dropdowns

- cms/templates/partials/hero.html
- cms/views_test.py
- courses/views_test.py
- static/scss/detail/header.scss
Fixes #441 
Adds a popup which shows when anonymous users try to enroll informing them to sign up or sign in first.
As an anonymous user click the enroll button on a program or course page. You should also verify that a home page with a video playing looks the same as before. The overflow CSS was removed so that the popup could go over the boundary. I adjusted the z-index and set a background color of the header so everything should still look the same as before.
Desktop:
Mobile:
> Add popup for anonymous users to login when they want to enroll

- ecommerce/serializers.py
- ecommerce/views_test.py
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/flow/ecommerceTypes.js
Fixes #565 
Related to #418 
Changes the valid patch key from `id` to `product_id`. This makes it so `id` always means `ProductVersion.id` and `product_id` always means `Product.id`.
Nothing should break
> Change basket PATCH to use product_id instead of id

- mitxpro/settings.py
Fixes #577 
Fixes the regression for @login_required protected redirects
Go to /dashboard and verify you get redirected to /signin with the `next` parameter populated
> Fix login redirect regression

- ecommerce/api.py
Closes #566
In `ecommerce.api.create_unfulfilled_order`, moves the `sync_hubspot_deal` call out of an atomic transaction.
Log in as a new user and sign up for every course run available.  You should never see an exception in the log caused by `sync_hubspot_deal` being called for a non-existent `Order` object.
> Move sync_hubspot_deal call out of atomic transaction

- courses/management/commands/defer_enrollment.py
- courses/management/commands/refund_enrollment.py
- courses/management/commands/transfer_enrollment.py
- courses/management/utils.py
- courseware/api.py
Closes #457
Closes #458
Closes #460
Adds management commands for setting an enrollment to refunded, deferring an enrollment to a different course run, and transferring an enrollment to a different user
To test refunds:
- Create or use an active course run or program enrollment
- `manage.py refund_enrollment --user <YOUR_USERNAME_OR_EMAIL> --run <COURSEWARE_ID>` (`--program <READABLE_ID>` instead of `--run` to test program enrollments)
- Check that the enrollment record now has active=False, change_status=refunded
To test deferrals:
- Create or use an active course run enrollment
- `manage.py defer_enrollment --user <YOUR_USERNAME_OR_EMAIL> --from-run <ENROLLED_COURSEWARE_ID> --to-run <DESIRED_COURSEWARE_ID>`
- Check that the enrollment record now has active=False, change_status=deferred; …
> Added enrollment change management commands

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/serializers.py
- static/js/components/forms/CheckoutForm.js
- static/js/components/forms/CheckoutForm_test.js
Fixes #518 
Adds validation of data consent agreements on the backend
- Generate a coupon which has a data consent agreement attached to it. Paste the code in the checkout text field and click 'Apply'. Click 'place your order' and note the error message saying that you have not clicked the checkbox yet.
-  Clear the code textbox and click 'Apply'. The checkbox goes away and the coupon is unapplied. Add the coupon code back and click 'Place your order' without clicking 'Apply' first. You should see a validation error message saying that the agreement is not yet signed
> Validate data consent agreements have been signed

- ecommerce/conftest.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/views_test.py
Fixes #539 
If the basket item changes, the selected runs are deleted. Previously this was only done when the runs were specified explicitly. Leaving the old runs selected caused subtle errors in checkout.
-   Go to /checkout/?product=xxx where xxx is the id number for a course run product. Change the selected run to be "Select a course run", then change it back to some valid run.
-   Go to /checkout/?product=yyy where yyy is the id number for a program product. Look at CourseRunSelection for your user. You should see no `CourseRunSelection` objects anymore.
> Clear runs from basket when selected item changes

- static/js/components/UserMenu.js
- static/js/components/UserMenu_test.js
Fixes #620 
Changes the logout button from a `MixedLink` to a vanilla `a` tag.
Click `Sign out` from a CMS page and a non-CMS page.  In both cases you should get logged out.
> Convert signout MixedLink to regular <a> tag

- hubspot/serializers.py
- hubspot/serializers_test.py
Fixes #623 
- Uses a hubspot-formatted purchaser id in the `OrderToDealSerializer`
- Create a new user.
- Order a product as that user.
- Sign in to Hubspot and find the new order, it should be associated with the contact you just created.
> User hubspot-formatted purchaser id in OrderToDealSerializer

- courseware/api.py
- courseware/api_test.py
Fixes #579 
This makes `create_edx_user` resilient against multiple access tokens already existing. It can handle 0 or 1 but more that that causes django to raise an error.
- Run the app
- Run `docker-compose stop celery` so the task doesn't get run immediately
- Register a new user
- Go into django admin and create at least 2 `AccessToken` records for your user
- `docker-compose start celery`
- Verify `CoursewareUser` and `OpenEdxApiAuth` records were created for your user
> Fixed race condition with AccessToken

- static/scss/detail/header.scss
- static/scss/detail/text-video-section.scss
Closes #619 
Fix styling of youtube video of home and product page.
- Add youtube video in home or product page with different aspect ratio.
- It should render within parent container.
Introduce in #590 
**Youtube video**
**Rendered:**
> Styling of youtube video of different aspect ratio

- static/js/components/forms/CheckoutForm.js
- static/js/components/forms/CheckoutForm_test.js
Fixes #454 
Previously the form was reset whenever the `initialValues` changed, which would happen when the basket is updated. The intent was to have the form be reset if there was a significant change of content from some form update, so that the new content could fill in the form fields. This makes sense when switching the product but we don't want to do this when just switching the coupon code, and we don't need to do this when submitting the form since we will be redirected away from the form right after. For the `updateProduct` case we explicitly call `resetForm`.
On a program product start with no runs being selected. Choose some runs then apply a coupon code. Then selected runs will remain and the coupon will be applied with the update to the discount.
If you go to a course run …
> Remove enableReinitialize, call resetForm explicitly instead

- courses/models.py
- courses/models_test.py
- courses/serializers_test.py
- courses/views_test.py
#615 
Adds a filter to unexpired course runs for `live=True`.
Add multiple course runs to a course. Have some of them `live=True` and others `live=False`. Only the course runs that are live should show up in the metadata tiles and through the "More Dates" popup.
> #615 Add `live` filter to unexpired course runs

- cms/models.py
- cms/views_test.py
#610 
Overrides the `serve` method for page classes that are not to be viewed on their own, to raise a 404 rather than throwing a `TemplateNotFound` exception.
In the CMS, go to any course/program child page and click on the `live` link. It should show a 404 page. Alternatively you can also try going to `/courses/` and `/programs/` and it should show a 404 page.
> #610 TemplateDoesNotExist should raise a 404

- cms/models.py
- cms/models_test.py
- cms/templates/catalog_page.html
- cms/utils.py
- cms/utils_test.py
- courses/views_test.py
Fixes #568 
- Add courses and program pages, with different start dates. 
- Card should sort based on above criteria.
> Catalog page sorting

- cms/templates/partials/hero.html
- cms/views_test.py
- static/scss/catalog/keep-me-posted.scss
- static/scss/detail/header.scss
- static/scss/detail/subnav.scss
Fixes #464 
Updates default color of sub navbar links on product detail page to solid black.
Hero section button style:
> #464 Subnav font style should conform to designs

- cms/templates/partials/catalog-card.html
Fixes #659 
Previously metadata tiles were fixed by updating the current price methods for courseware. This PR updates the same for the catalog cards.
Add products for programs and courses and visit the catalog page. All cards with products linked should display the price.
> #659 Catalog: prices are not displayed for some courses/programs

- ecommerce/api.py
- ecommerce/api_test.py
- mitxpro/utils.py
Closes #626
Sends an email to customer support if an attempt to create or update an enrollment fails.
- Set `MITXPRO_SUPPORT_EMAIL` or `MAILGUN_RECIPIENT_OVERRIDE` to your email.
- Temporarily change `enroll_user_in_order_items` to throw an error when creating a `CourseRunEnrollment` or `ProgramEnrollment`, for instance `defaults=dict(company=order)`
- Try to purchase a course run or program, an error should be thrown
- Check your inbox, you should get an email with subject "MIT xPRO enrollment error" with a message including the username and email, order number, course run or program id and title, and the stacktrace.
> Send email to support when enrollments fail

- users/serializers.py
- users/views.py
- users/views_test.py
Fixes #635
Moves `unused_coupons` attribute to the `UserSerializer` instead of inserting it from `CurrentUserRetrieveUpdateViewSet`
- Edit your profile and click submit, the 'View Profile' page should load afterward.
- Use the bulk coupon enrollment tool (`http://xpro.odl.local:8053/ecommerce/admin/enroll/`) to associate a coupon with your user, you should see the `You have an unused coupon. Checkout now to redeem it.` banner near the top of each page, including the profile pages (view/edit).
> Get unused coupons in UserSerializer, not CurrentUserRetrieveUpdateViewSet

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- mail/api.py
- mail/constants.py
- mail/templates/course_run_enrollment/body.html
- mail/templates/course_run_enrollment/subject.txt
- mail/verification_api.py
Fixes #567 
Adds a per-courserun confirmation email when/if enrollment succeeds. 
- Sign up for a program and verify you receive an email for each course run
- Sign up for a course run and verify that you receive an email for that course run
Note: a known issue we're not fixing in this PR is that a failure to enroll in any course in a program causes no emails to get send because that matches the current state behavior of `CourseRunEnrollment.edx_enrolled`.
This code also handles any errors from sending the email and logs them so that they do not cause a checkout to fail.
<details>
<summary>Individual email</summary>
</details>
<details>
<summary>Set of emails for a program</summary>
</details>
> Add enrollment emails

- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
Closes #633 
Removed edX links in the dashboard for course runs that have not yet started in edX
For your local setup, using the edX demo course will probably be easiest. Make sure your user is enrolled in that course run.
- Set the `start_date` for your course run to some future date. The course title in the dashboard **should not** be a link
- Set the `start_date` for your course run to some past date. The course title in the dashboard **should** be a link
- Set the `start_date` for your course run to null. The course title in the dashboard **should not** be a link
> Removed links for course runs that have not yet started in edX

- cms/templates/home_page.html
- cms/templates/partials/hero.html
- cms/templates/product_page.html
- static/scss/detail/header.scss
Fixes #602 
Fixes video CSS to show video over background image but under any text or other elements in the header block. Video is 100% of width which should mean videos that change resolution will be shown correctly.
The video should not be visible at mobile resolutions. 
View the video on the homepage. At mobile resolutions you should see only the background image. Additionally you should be able to go to a program or course page as an anonymous user, click the 'Enroll now' link and see a tooltip which shows correctly. 
Desktop
Mobile
> Fix header CSS for video on home page

- static/scss/notification.scss
Fixes #687 
Adds `position: relative` and `z-index: 1` to explicitly position the notifications above the window.
Add a `SiteNotification` and visit your home page. You should see a notification.
Wide desktop
Narrow desktop
Mobile
> Tweak notification CSS to prevent video from displaying over notifications

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/views.py
- ecommerce/views_test.py
- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/js/lib/util.js
- static/js/lib/util_test.js
- static/scss/dashboard.scss
Fixes #598 
Fixes #663 
Adds query parameters to the redirect from CyberSource, then uses that information to direct the 
Go to `/dashboard/?readable_id=xyz&status=receipt`. You should see a request being made every 3 seconds. After 2 minutes the polling should stop and you should see "Something went wrong. Please contact support." in a alert message.
Find a readable id for an item you are already enrolled in (`Program.readable_id` or `CourseRun.courseware_id`). Encode it as a query parameter and put it in the `readable_id` query parameter in place of the `xyz` in the URL above. You should see the URL change to `/dashboard/` and a message saying that you are successfully enrolled in the course run or program.
Separately, go to `/checkout?product=?` for a product you can purchase. Have a …
> Poll dashboard page for course run/program

- mitxpro/templates/partials/notifications.html
- static/scss/notification.scss
No ticket (I think)
See title
Make sure the spacing issue with site-wide notifications is gone (best to test it on the home page with a video enabled like RC)
> Fixed margin issue with site-wide notifications

- cms/embeds.py
- cms/embeds_test.py
- cms/templates/partials/text-video-section.html
- mitxpro/settings.py
- static/js/hero.js
Fixes #704
Adds support for Youtube videos to the "Watch Now" button in hero section on the home page.
Configure a Youtube video within the "Text Video" section on home page (typically titled "About MIT"). Click on the "Watch Now" button, the screen should scroll to bring the section in view and the video should start playing.
**Note:** While testing make sure your browser isn't trying to use a stale version of the JS file.
> #704 Watch Now button support for Youtube videos

- static/js/components/forms/EmailForm.js
- static/js/components/forms/EmailForm_test.js
- static/js/containers/pages/login/LoginEmailPage.js
Closes #680 
Adds a 'create account' link to sign in page
Go to the login page and use the "create account" link. Other email-only forms (e.g.: the forgot password page) should not have that link
> Added 'create account' link to sign in page

- ecommerce/serializers.py
- ecommerce/serializers_test.py
- static/js/components/forms/CheckoutForm.js
- static/js/components/forms/CheckoutForm_test.js
- static/js/factories/ecommerce.js
- static/js/flow/ecommerceTypes.js
Fixes #720 
Adds the program title to the API and uses it instead of the product description when displaying it on the checkout page
View a product in the checkout page and verify that the title matches the course run or program title, not necessarily the product description.
> Use program.title and run.title instead of product.description

- courses/admin.py
No ticket yet
Adds readonly admin classes for enrollment audit models
Make sure the admin views for these two new classes are not editable
> Added enrollment audit admin classes

- static/js/components/NotificationContainer.js
- static/js/components/NotificationContainer_test.js
- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/js/reducers/notifications.js
- static/scss/notification.scss
Fixes #698 
Removes the `<Alert />` component used on the dashboard page and uses the sitewide notifications instead
Go to `/dashboard/?purchased=abcde&status=purchased` where `abcde` is a readable id for a product you already have in the dashboard. You should see the URL change to remove the query parameter and a alert message pop up which looks like the screenshot below.
If you change the readable id to something else not in the dashboard, and go to `/dashboard?purchased=xyzzy&status=purchased` and wait for approx 2 minutes, you should see the other alert similar to the screenshot below.
> Use site wide notifications for dashboard

- static/js/components/forms/EmailForm.js
- static/js/components/forms/EmailForm_test.js
- static/js/components/forms/ProfileFormFields.js
- static/js/components/forms/RegisterDetailsForm_test.js
- static/js/components/forms/RegisterEmailForm.js
- static/js/components/forms/RegisterEmailForm_test.js
Partially addresses #684
Adds `autoComplete` attributes to name/address profile fields and email form fields.
- With Chrome, try using autofill on the email form and the new user registration form.  The fields should be populated correctly based on your autofill selection.
- Repeat with Firefox, all fields should be populated correctly except state and postal code (see below).
Autofill will only work partially in Firefox.  The browser seems unable to auto-populate state and zipcode fields because they are not on the form until either "US" or "Canada" is selected for country.  [There is a workaround](https://github.com/mitodl/mitxpro/issues/684#issuecomment-507355531) but it involves more substantial changes to the form so it will be handled in a separate PR later.
> autoComplete attributes for form fields (Chrome)

- cms/templates/partials/hero.html
Closes #738 
Removes the `h5` label from product page that displays a course's position in its program
> #738 Remove course position label from product page

- cms/templates/partials/metadata-tiles.html
#740 
Humanizes the price display on product page metadata tiles.
On any product page that has a price, the tile should display the value with appropriate thousands separators.
> #740 Product Page: Add commas to prices tile

- cms/models.py
- cms/templates/partials/hero.html
- static/js/containers/pages/register/RegisterExtraDetailsPage.js
- static/js/lib/selectors.js
- static/js/lib/selectors_test.js
Fixes #697 
- Adds the `next=?` parameter to the catalog popup dialog
- Fixes `RegisterExtraDetailsPage.js` to support this on registration complete since it was missed previously
- As a logged in user, verify the enroll button on a product page still gives you a valid link to the checkout page for that product.
- As an anonymous user, verify both the sign in and create an account buttons in the popup result in you ending up on the checkout page after successfully completing either auth flow
In the interest of delivery time, did not write tests for this change because `RegisterExtraDetailsPage.js` doesn't have any tests carved out for it anyway. See #312.
> Fixed catalog login/signup urls

- static/js/components/forms/CheckoutForm.js
- static/js/components/forms/CheckoutForm_test.js
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/lib/queries/ecommerce.js
Fixes #711 
Disables coupon update and checkout buttons while mutating requests are processing
Throttle down your network activity in the browser console and click the button repeatedly. You should see only one request be initiated
> Disable submit button while processing

- static/js/containers/pages/DashboardPage.js
- static/scss/common.scss
- static/scss/dashboard.scss
Closes #682 
Adds catalog link to the dashboard when there are no enrollments
Clear out any enrollments you have for some user and visit `/dashboard`. If you click the link it should take you to the catalog
I'm pretty sure that header issue in the mobile view is an existing bug
> Added catalog link to empty dashboard

- mitxpro/urls.py
- mitxpro/views.py
- mitxpro/views_test.py
Fixes #554 
Add redirect view, which will redirect wagtail login to site login page.
- Logout of CMS.
- Hit `/cms`
- You will be redirected to `/signin/?next=/cms/`
- After signing in you will be redirected back to CMS.
> redirect the wagtail login to the site login

- courses/management/commands/defer_enrollment.py
- courses/management/commands/refund_enrollment.py
- courses/management/commands/transfer_enrollment.py
- courses/management/utils.py
- courses/models.py
- courses/models_test.py
- mitxpro/utils.py
- mitxpro/utils_test.py
Fixes #671 
Fixes #669 
- Fixes bugs with the refund and defer enrollment management commands
- Fixes edX API client error handling so that the actual error response body is shown in the command output
- Refactors some common functionality to make these commands a less susceptible to bugs
- Enroll a user in some program ("SysEngX"/"Systems Engineering" for example), then transfer that enrollment to a different user via the `transfer_enrollment` command. If you weren't previously enrolled, and if the course runs in that program aren't set up in your local edX instance, you should see (a) the program enrollment and associated course run enrollments transfer over to the new user, (b) the existing program enrollment and associated course run enrollments deactivated for your 'from' user, and …
> Fixed and refactored enrollment commands

- hubspot/api.py
- hubspot/api_test.py
- hubspot/conftest.py
- hubspot/management/commands/configure_hubspot_bridge.py
- hubspot/serializers.py
- hubspot/serializers_test.py
Closes #497 
Closes #498
- Modifies the `configure_hubspot_bridge` command to create/update new properties (`payment_type`, `payment_transaction`, `discount_percent`, `order_type`) and a new group `coupons` to contain most of these (along with some other existing properties - `company`, `coupon_code`).
`docker-compose run web python manage.py configure_hubspot_bridge`
`docker-compose run web python manage.py sync_hubspot`
You can also manually purchase something: use a single-use coupon with an affiliated company, payment type, and payment transaction.
Log into Hubspot and verify that the order(s) have the new fields, they are correctly populated, and assigned to the correct group.
> Create 'Coupons' group and additional properties for Hubspot deals

- hubspot/api.py
- hubspot/api_test.py
Fixes #765
Removes `unused_coupons` field from contact sync message JSON
Run `docker-compose run web python manage.py sync_hubspot --contacts`, it should complete without errors.
> Do not include unused_coupons field when syncing contacts to hubspot

- static/js/components/forms/CouponForm.js
- static/js/components/forms/CouponForm_test.js
Closes #555
Closes #736 
- Sets time on start/end dates to 00:00:00
- Orders products by title
- Adds an 'All Products' radio button so that both programs and course runs can be selected.
- Go to `http://xpro.odl.local:8053/ecommerce/admin/coupons`
- Click the `All Products` radio button, you should be able to see and select both programs and runs.
- Fill out the form and save.  Go to django admin and verify that the start and end dates for the new `CouponPaymentVersion` have a time of `00:00:00`
(Optional)
(Optional)
(Optional)
(Optional)
> Coupon form improvements

- static/js/containers/pages/register/RegisterConfirmPage.js
- static/js/containers/pages/register/RegisterConfirmPage_test.js
Fixes #719 
Adds a notification which shows up when the user goes to the email verification page
Register a new account and click the verification email link. You should see something like the screenshot below.
> Add notification when user verifies their email

- authentication/serializers.py
- static/js/containers/pages/register/RegisterEmailPage.js
- users/serializers.py
- users/serializers_test.py
Fixes #782 and #786
- Update regex to match Canadian postal codes.
- Replace sign up with create account
- go to `/create_account` and start create account flow
- Click on the verification email link, to go to `/create-account/details/`
- Enter the account details using a Canadian address, including province and Candian postal code (e.g. K0M 2K0).
> Tasawer/fix account creation for Canadian users

- users/serializers.py
- users/serializers_test.py
Fixes #789 
- Update regex for invalid codes.
- Add test for invalid postal codes.
- go to /create_account and start create account flow
- Click on the verification email link, to go to /create-account/details/
- Enter the account details using a Canadian address, including province and Candian postal code (e.g. K0M 2K0).
- Also try with invalid format of postal code.
This PR is follow up of #787
> fix regex for false positive, add test for invalid codes

- courseware/admin.py
Fixes #677 
Changes the `search_fields` option for `CoursewareUserAdmin` so it doesn't break
Go to `http://xpro.odl.local:8053/admin/courseware/coursewareuser/` and run a text search.  You should not get any errors.
> Fix django admin search for CoursewareUser

- static/js/components/forms/EditProfileForm.js
- static/js/components/forms/EditProfileForm_test.js
- static/js/containers/pages/profile/EditProfilePage.js
- static/js/containers/pages/profile/EditProfilePage_test.js
Fixes #735 
Changes some null fields to empty strings when the values are rendered, then changes some back to null for the PATCH of the payload.
On the `/profile/edit/` page, set all of the fields below the dashed line, for example "Years of experience", to non-empty values. Click "Continue" and then click "Edit". All values should have been persisted correctly.
Next, clear those values and click 'Continue', then click 'Edit'. All values should now be blank in the UI.
> Coerce fields to and from empty strings to fix React uncontrolled warnings

- ecommerce/serializers.py
- ecommerce/views_test.py
Fixes #778 
Updates the validation message for an invalid coupon code
At the checkout page, type some random string that's not a coupon code and click 'Apply Coupon'.
> Change validation error message to Enrollment / Promotional Code

- config/nginx.conf.erb
When a user aborts an HTTP request, uWSGI will still attempt to write back to the request socket, resulting in an OSERROR. By adding the `ignore_client_abort` parameter we avoid spamming our Sentry logs with this exception.
N/A
Fixes the occurrence of OSERRORs from uWSGI when a client aborts a request before it is completed
Deploy to CI, start a web request and close the tab before it completes
> Added config to avoid OSERRORs from uwsgi

- static/scss/detail/companies-trust.scss
- static/scss/slick.scss
@pdpinch for #777 I have adjusted the `min-width: 1275px` but if screen size would be lower than that then arrows will overlap again over cards again due to space constraint over there. There is no any space remain for left/right arrows.
> minor scss fixes

- authentication/pipeline/user.py
- compliance/api.py
- compliance/api_test.py
- compliance/management/commands/decrypt_exports_inquiry.py
Fixes #805 
Adds a command to decrypt exports inquiry logs
- Find or create a user with an `ExportsInquiryLog` record
- Run `./manage.py decrypt_exports_inquiry [--id ID] [--username USERNAME] [--email EMAIL]`
- Enter your private key in the prompt
- Verify you get sensible xml output of the cybersource request and response
> Added command to decrypt exports inquiry

- cms/utils.py
- localdev/seed/api.py
- localdev/seed/api_test.py
- localdev/seed/management/commands/delete_seed_data.py
- localdev/seed/management/commands/seed_data.py
- localdev/seed/resources/seed_data.json
- mitxpro/utils.py
- mitxpro/utils_test.py
Fixes #425 
Closes #206 
Closes #207 
- Fixes bug where course/program pages were added under the root page rather than under the course/program index pages
- Fixes bug where seeded objects couldn't be deleted due to delete-protected ecommerce tables
- Adds products & prices to certain seeded objects
- Adds command that allows you to selectively delete all seeded data or just some specific objects
Some of the course run titles in the original `seed_data.json` were poorly set. They were corrected in this PR, which provides an opportunity to test out the delete command. Start by running the following:
- `manage.py delete_seed_data --type courserun --title "SEED Systems Engineering - Fall 2019"`
- `manage.py delete_seed_data --type courserun --title "SEED Systems Engineering - Spring 2020"` …
> Fixed seed data bugs, added products, added deletion command

- cms/templates/partials/course-carousel.html
- cms/templates/partials/faculty-carousel.html
- cms/templates/partials/for-teams.html
- cms/templates/partials/learning-techniques.html
- cms/templates/partials/target-audience.html
- cms/templates/partials/text-section.html
- cms/templates/partials/text-video-section.html
- static/scss/detail/companies-trust.scss
- static/scss/detail/faculty.scss
- static/scss/detail/for-teams.scss
- static/scss/detail/learning-techniques.scss
- static/scss/detail/testimonial-carousel.scss
#776 
Removes forced `text-uppercase` classes and `text-transform: uppercase;` properties on section heads and subheads so mixed case can be used.
Go to any section, modify it's title to use mixed case. On the page where the section appears, verify that the head/subhead appears as configured in CMS and not forced to uppercase.
> #776 Allow Mixed Case Section Heads and Subheads

- cms/templates/partials/catalog-card.html
- cms/templates/partials/featured_card.html
#792 
Fixes featured product card to use the product thumbnail instead of only the default image. 
Extra: Also fixes the wagtail image rendition size according to the image dimensions.
Mark a product featured and make sure that product has a thumbnail image. Go to the catalog page, verify that the catalog card and featured product card show the same thumbnail.
> #792 Featured Product Card Thumbnail Fix

- compliance/management/commands/decrypt_exports_inquiry.py
N/A
Fixes a typo in the command that caused it to immediate crash
- Run `./manage.py decrypt_exports_inquiry --user-id 1`
- Command should not crash or exit and you should see a prompt
- No need to test further
> Fix typo with command arg

- cms/models.py
- requirements.in
- requirements.txt
Fixes #774 
Upgrades Django to 2.2, and wagtail to 2.5.1 because wagtail 2.4 won't work with Django 2.2
Nothing should break. You can double check the release notes for django and wagtail, but I didn't notice anything that would affect us when I looked earlier.
> Upgrade Django to 2.2, wagtail to 2.5.1

- courses/models.py
- courses/models_test.py
Fixes #643 
fix comparison error when there is not start_data for course run
- Goto admin/courses/courserun.
- Edit any course run.
- Remove start datetime.
- Save it.
- Reload the /catalog page
- No error should raise
> fix comparison error when there is not start_data for course run

- courses/management/commands/defer_enrollment.py
- courses/management/commands/refund_enrollment.py
- courses/management/commands/transfer_enrollment.py
- courses/management/utils.py
Fixes #655 
Fixes #780
- Sets the associated order to refunded when an enrollment is refunded
- Changes the enrollment summary output to indicate the readable_id/courseware_id of the enrolled objects
- Purchase some program/course via full-price coupon, then set it to refunded via the `refund_enrollment` management command. It should set the associated order to refunded as well, and the command output should indicate that
- Run any of the enrollment change commands (including `refund_enrollment`) and check that the enrollment summaries in the output look readable
> Fixed enrollment commands - set order status, changed output

- static/scss/layout.scss
- static/scss/variables.scss
- static/scss/voucher.scss
- voucher/templates/enroll.html
- voucher/templates/redeemed.html
- voucher/templates/resubmit.html
- voucher/templates/upload.html
Closes #818
- Changes voucher page styling to resemble invision design
- Set the following .env variables to the same as used on CI:
```
VOUCHER_***
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_STORAGE_BUCKET_NAME=
```
Also set the following:
```
VOUCHER_COMPANY_ID=1
```
- Create a course run, product, product version, and 100% off single-use coupons by company (id=1) that will match a sample voucher pdf that I can send you.
- Go to `/voucher/upload`, check the page styling. 
- Upload the voucher
- You should end up at `/voucher/enroll`. Check the styling.
- Also go directly to `/voucher/resubmit` and `/voucher/redeemed`, and check the styling.
> Change voucher pages style

- cms/templates/partials/catalog-card.html
- cms/templates/partials/featured_card.html
- cms/templates/partials/metadata-tiles.html
Fix: #709 
- Create a Program, Course and CourseRun
- Create a Product and ProductVersion for the CourseRun
- Create a Product page for the Program
- With no Product and ProductVersion for the program, I expect the Program product page to be missing the price card.
- On the Program product page, the price card displays the price of the courserun
> asadiqbal08/mitxpro-709 Wrong price for program

- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/factories/course.js
- static/js/flow/courseTypes.js
Fixes #421 
Use the next unexpired run as a default option for selected runs in the checkout page
Go to `/checkout/?product=???` for a certain product. You should see default options selected on the checkout page. You should be able to change the runs as before and the changes should persist.
> Use next_run_id for a default for the checkout page course run selection

- pytest.ini
- test_requirements.txt
None
Removes pep8. With `black` and `pylint` we should be well covered already with linting.
> Remove pep8

- static/js/containers/pages/register/RegisterEmailPage.js
- static/js/containers/pages/register/RegisterEmailPage_test.js
Fixes #600 
Display message when user has already account with provided email.
- Try to create an account with an existing account email.
- You should see a message.
> display message when account already exists

- cms/templates/partials/featured_card.html
#885 
Updates featured product card to use `catalog_details` instead of `description` (which was previously being used). 
Go to the catalog page, the featured product card should show the same catalog description that it shows for the normal card for that product (ensure you have set a `courseware_page.catalog_details` different from the `courseware_page.description` so you can see the different).
> #885 Use catalog_details for featured product card

- ecommerce/api_test.py
- ecommerce/migrations/0015_db_protect.py
- ecommerce/models_test.py
- ecommerce/test_utils.py
- ecommerce/utils.py
- ecommerce/views_test.py
- localdev/seed/api_test.py
Fixes #492 
Prevents updating or deleting rows from `ProductVersion`, `CouponVersion`, or `CouponPaymentVersion`
Run the migrations and try updating or deleting information from those models
> Add protection rules for ProductVersion, CouponVersion, CouponPaymentVersion

- courses/management/commands/refund_enrollment.py
Fixes #894 
Fixes bug where the `refund_enrollment` command did not call the correct save method that automatically adds an audit record when changes are made
Refund some enrollment, then check the OrderAudit table in Django admin to make sure a record was created that reflects the change of status
> Changed refund command to properly create order audit record

- ecommerce/admin.py
- static/css/django-admin-version.css
Blocked until #795 is merged
Fixes #830 
On the admin page for the three version models (`CouponVersion`, `CouponPaymentVersion`, `ProductVersion`) you should not be allowed to edit or delete the model. You can edit and click 'Save as new' to persist your change as a newer version.
On the admin page for the related models `Coupon`, `CouponPayment`, and `Product` you should see the contents of the version model on the inline panel but none of the fields should be editable. There should be links to click to edit the inline models. Note that the Django admin doesn't seem to allow restricting the number of inline forms but they should be ordered so the most recent is first.
Try out editing via the Django admin. Please comment if you see anything that feels strange or is missing.
> Django admin for version tables

- courses/models.py
- courses/models_test.py
- mitxpro/test_utils.py
Fixes #690 
Adds information to the `CourseRunEnrollment` and `ProgramEnrollment` audit tables
Check out and add an enrollment. Check the audit table for that enrollment and verify that the fields listed in the linked issue are part of the audit table now.
> Update audit table serialization for program and course run enrollments

- cms/models.py
- cms/models_test.py
#908 
Updates the `CourseProgramChildPage` class to generate the correct URL in the form:
`/courses|programs/<readable_id>/<child_page_slug>`
Go to wagtail admin (cms) and click on `live` links of any course/program child pages. The **link** should be of the format described above (please bear in mind that most of the child pages are right now set up to raise a 404 on these links, so that is the expected behavior).
> #908 Wagtail admin generated URLs for child pages

- app.json
- mitxpro/settings.py
Fixes #367 
Adds tagging of review apps so we can tell when a "CI" error is really a PR app.
Example:
https://sentry.io/organizations/mit-office-of-digital-learning/issues/1127338602/?project=1413655&query=is%3Aunresolved&statsPeriod=14d
Open a shell in heroku and raise an error so it logs to sentry:
```python
import sentry_sdk                                                                                                                                                                
sentry_sdk.capture_exception(Exception("test")) 
```
Verify it shows up on sentry with the review app name tagged.
> Added tagging for sentry errors to review apps

- cms/templates/partials/metadata-tiles.html
- courses/models.py
- courses/models_test.py
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
#882 
Enables "more dates" to be displayed on the program page with  dates from the earliest course in the program. ~~runs/products loaded appropriately for the first (one with the earliest course run) course in the program. Clicking on the start date in the pop up should display checkout page with the correct course run loaded in cart.~~
Clicking on the start date in the pop up should display the program checkout page with the appropriate course run (for which the date was clicked to get here) already selected for that specific course.
Set up a program with different courses. The first course (one with the earliest unexpired course run) should have multiple course runs which are live, have a valid (unexpired) enrollment time span. When you visit the program detail page the metadata tiles …
> #882 display more dates on program page

- cms/models.py
- cms/views_test.py
#914 
Adds filters to catalog contents to exclude all entries which have a product with `live=False`.
Go to catalog, select any course or program and in the django admin against that course or program, set `live=False`. Verify that course or program card does not appear on the catalog anymore. This also applies to featured product card.
> #914 Inactive products should not show on catalog

- static/js/Router.js
- static/js/components/ScrollToTop.js
#783 
Adds a component to the router which, when navigation occurs (page loads), scrolls the window to the top of the page.
Go to any page that is rendered by react. Make sure window height is small enough to enable vertical scrolling. Navigate to any other react rendered page, the screen should scroll to top of the content. An example is going to "Create Account" link, scrolling to the bottom till the form is barely visible, enter an existing email address. The form upon submission should try to redirect to the sign in form. The screen should scroll to top.
You can also verify by switching between the profile and dashboard pages given viewport height is small enough to enable vertical scrolling.
> #783 React should scroll to top on page load

- courses/models_test.py
#929 
Fixes tests for more dates section (specifically the `first_course_unexpired_runs` property on programs).
Run `pytest courses/models_test.py`. It should no longer fail even if repeatedly run.
> #929 Test fixes for program more dates

- uwsgi.ini
In order to mitigate the issue we are seeing with cookie sizes resulting in 502 errors
N/A
Increases the uWSGI buffer size to allow for larger cookies and headers
Create a set of cookies that are larger than 4k and attempt to make a request
> Added explicit buffer size to uWSGI for cookie size issues

- courses/api.py
- courses/api_test.py
- courses/models.py
- courses/models_test.py
- courses/views.py
- courses/views_test.py
- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/js/factories/course.js
- static/js/flow/courseTypes.js
- static/js/lib/courses.js
- static/scss/dashboard.scss
Fixes #876 
Show past courses and programs on dashboard.
- Enroll in couple courses and programs.
- Make at least one course/program as ended. 
- View your dashboard.
- Courses is considered ended if all of its runs are ended.
- Program is considered as ended if all of its courses are ended.
> show past enrollments on dashboard

- courses/admin.py
Fix: #903 
It looks like the course admin defines the nonexistent description as a searchable field which is causing this.
visit `admin/courses/course/` and `admin/courses/program/`
perform search against the course/program title. 
It will complain: `Cannot resolve keyword 'description' into field.`
visit `admin/courses/course/` and `admin/courses/program/`
perform search against the course/program title. 
It should not complain about the `description` field now.
> asadiqbal08/mitxpro-903 Removed un existent field 'description'

- static/js/components/forms/CheckoutForm_test.js
- static/js/containers/pages/CheckoutPage.js
Fixes #824 
Trim spaces around coupon code before applying.
- Create coupon at `/ecommerce/admin`
- Apply it on basket including spaces around it.
- There should be no error.
> fix spaces around coupon code

- authentication/serializers.py
- authentication/views_test.py
Fixes #936
Fixes a regression on the login password page caused by changes in #853 
- Go to login
- Enter an incorrect password
- You should see an inline error message instead of the redirect that happens on master
> Fix incorrect password redirecting a user to the create account error page

- static/js/hero.js
- webpack.config.shared.js
None
IE11 was not working properly because arrow functions which were present in the webpack bundle aren't supported in IE11. This PR configures webpack to also transpile libraries used by our bundle in addition to our own code. I don't know what the downsides are but I assume webpack will take longer to compile, will probably use more memory, and the bundles will probably be larger than before.
`hero.js` is not transpiled at all so the default parameter is removed so that it won't cause a syntax error.
Note that the hero banner video still doesn't work but this is outside the scope of this PR.
Go to the home page. You should be able to see the "sign in" and "create account" buttons.
> Add support for IE11

- courses/management/utils.py
- ecommerce/mail_api.py
- mail/constants.py
- mail/templates/course_run_enrollment/subject.txt
- mail/templates/course_run_unenrollment/body.html
- mail/templates/course_run_unenrollment/subject.txt
Task: #835 
- We still don't have the necessary code for automatically unenrolling the user in open edX.
- We need to run the following commands that are listed under [/mitxpro/courses/](https://github.com/mitodl/mitxpro/tree/master/courses/management/commands)
- For enrolling in course / program, a person can set the price to `0` and go through the checkout process. 
- Email should be send according to the acceptance criteria above.
> asadiqbal08/mitxpro- Send enrollment/unenrollment emails

- cms/templates/partials/metadata-tiles.html
Fix: #925 
- Go to https://xpro.mit.edu/courses/course-v1:xPRO+SysEngx1/ in Safari
- Click on "More Dates" on the "Start Date" tile.
- Pop-up should display with list of future course dates.
> asadiqbal08/mitxpro-925  "More Dates" on Course Product page doesn't work in Safari

- static/scss/collapsible.scss
Fixes #966 
Updates a CSS rule which made checkboxes invisible by default. Other CSS rules made the checkboxes visible so we didn't see this issue on Chrome or Firefox. My guess is that IE11 has a bug or two with its CSS implementation.
View the checkbox in IE11
> Make checkbox CSS rule more specific to catalog page

- app.json
- courseware/api.py
- courseware/api_test.py
- courseware/constants.py
- docker-compose.yml
- mitxpro/settings.py
- mitxpro/test_utils.py
- mitxpro/test_utils_test.py
Closes #375 
Changes edX enrollment mode from `audit` to `no-id-professional`
1. You will need a course that exists in xpro and in your Open edX instance. The edX demo course (course id `course-v1:edX+DemoX+Demo_Course`) exists in all local devstack instances, but any course that exists in both apps should work.
1. You can use a course that you're already enrolled in with the default `audit` mode. That enrollment will just be updated/overwritten.
1. (__Might be optional! This might only be needed to make the professional mode the default. You can skip this and try applying it if there's a failure__) Make sure LMS has the `no-id-professional` enrollment mode enabled. This can be done by adding this to the top level of your `lms.env.json` file (the server will need to be restarted):
```json …
```
> Changed edX enrollment mode from audit to professional

- static/js/containers/pages/profile/EditProfilePage.js
- static/js/containers/pages/profile/EditProfilePage_test.js
Closes #987 
Fixes the 'Highest education' field on the profile edit page
Go to the 'Edit Profile' page.  Make some changes to several fields but set 'Highest education' to '----'.  Submit the form.  Your changes should be saved with no errors.
> Fix profile edit form

- b2b_ecommerce/factories.py
- b2b_ecommerce/urls.py
- b2b_ecommerce/views.py
- b2b_ecommerce/views_test.py
- courses/serializers.py
- courses/serializers_test.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/views.py
Part of #858 
Adds miscellaneous backend work left out of the previous PR:
- `total_price` calculation is fixed
- views for downloading coupon codes and for viewing order information, both using the order hash for lookup
- Cybersource receipt URL updated to include the order hash as a query parameter
- Cybersource cancel URL changed to the b2b checkout page (Cybersource errors if this value is the home page)
- Course serializer will return an empty list of runs for anonymous users. Logged in users get a list of available runs for that user. There is also a context value `show_all_runs` which will show all unexpired runs instead of just the ones for a user.
- `ProductVersionSerializer` now used by `ProductSerializer` to show more product info
- `ProductViewSet` now visible to anonymous …
> Backend work for b2b enrollment code purchases

- courses/management/commands/defer_enrollment.py
- courses/management/commands/refund_enrollment.py
- courses/management/commands/transfer_enrollment.py
- courses/management/utils.py
- ecommerce/api.py
- ecommerce/management/commands/retry_edx_enrollment.py
- ecommerce/utils.py
- mitxpro/utils.py
- users/api.py
- users/api_test.py
No ticket - related to #970 
Adds options to the `retry_edx_enrollment` so that (a) enrollment can be retried even if `edx_enrolled=True`, (b) a specific course run can be targeted, and (c) users can be targeted based on email and id in addition to username.
- Create an enrollment for some user with `edx_enrolled=True` (probably easiest just to add in Django admin/shell), then run the retry command: `manage.py retry_edx_enrollment -f --run <YOUR_COURSE_RUN_TEXT_ID> <YOUR_USER_EMAIL>`. The output should be as expected given your enrollment state in edX (and whether or not the course exists on edX)
- Use the command as you would have before and check the results: `manage.py retry_edx_enrollment <USERNAME_1> <USERNAME_2>`
- Part of the reason for this change is that we want to use a new edX …
> Added new edX enrollment command options and refactored command helpers

- mitxpro/utils.py
- mitxpro/utils_test.py
- users/api.py
- users/api_test.py
Closes #993 
Enables case-insensitive email search in management commands such as `defer_`/`transfer_`/`refund_enrollment` and `retry_edx_enrollment`
Run the commands mentioned above and provide email values with randomly capitalized characters. You should not see a `User.DoesNotExist` error
> Enabled case-insensitive email search in management commands

- b2b_ecommerce/urls.py
- static/js/components/B2BPurchaseSummary.js
- static/js/components/B2BPurchaseSummary_test.js
- static/js/components/forms/B2BPurchaseForm.js
- static/js/components/forms/B2BPurchaseForm_test.js
- static/js/components/input/ProductSelector.js
- static/js/components/input/ProductSelector_test.js
- static/js/containers/App.js
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/b2b/B2BPurchasePage.js
- static/js/containers/pages/b2b/B2BPurchasePage_test.js
- static/js/containers/pages/b2b/B2BReceiptPage.js
- static/js/containers/pages/b2b/B2BReceiptPage_test.js
- static/js/containers/pages/b2b/EcommerceBulkPages.js
- static/js/factories/ecommerce.js
- static/js/flow/ecommerceTypes.js
- static/js/lib/queries/ecommerce.js
- static/js/lib/urls.js
- static/scss/checkout.scss
Part of #858 
Implements the site where b2b customers can purchase enrollment codes which would be used by end users to enroll in the course run or program bundle of course runs.
First note that the functionality should work exactly the same with or without login.
For the purchase page, select a product and enter the number of seats and your email address. Click 'Place Order' and you will be directed to Cybersource. Fill in the fake credit card information and you should be redirected to the receipt page. You should see a simple "Loading..." message. If you look at the network tab you should see a request made every three seconds to the new order status API.
To test the receipt page we need to fulfill the order in the backend. You could try to fulfill the order via the order fulfillment …
>  Add pages for bulk enrollment code purchase and a receipt page to download codes

- b2b_ecommerce/api.py
- b2b_ecommerce/api_test.py
- b2b_ecommerce/serializers.py
- b2b_ecommerce/views_test.py
- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- mail/constants.py
- mail/templates/b2b_receipt/body.html
- mail/templates/b2b_receipt/subject.txt
- mail/views.py
- mitxpro/utils.py
- mitxpro/utils_test.py
Part of #858 
Adds functionality to send the email with a link back to the receipt page.
- Go to `/ecommerce/bulk/` and purchase some coupons. Complete the CyberSource transaction and you should be directed back to the receipt page which will show a loading indication while it waits for order fulfillment. 
- I'm getting the Cybersource receipt emails for the test server. Ask me for the receipt email and I'll forward it to you. You can simulate the Cybersource order fulfillment with this script: https://gist.github.com/noisecapella/5aa1073c895d99d991b85289cb26f0d9
- After fulfillment you should get an email with a link to the receipt page.
> Send email after enrollment code order is fulfilled

- b2b_ecommerce/views.py
- b2b_ecommerce/views_test.py
- ecommerce/api.py
- ecommerce/mail_api.py
- ecommerce/views.py
- ecommerce/views_test.py
- mitxpro/utils.py
- mitxpro/utils_test.py
- voucher/views.py
- voucher/views_test.py
Fixes #1034 
Previously the CSV file created had one column with only coupon codes. This does some refactoring and changes the CSV to also include a URL column with a link to the checkout page, with query parameters for the product and the coupon code.
This also refactors the CSV download at `/ecommerce/admin/coupons/` but there should only be a header row added here. Due to multiple possible products the URL is left out of this CSV for now.
Purchase enrollment codes if you haven't yet, then go to the receipt page and click the download link. You should see a CSV file with two columns, one is the code and the other should be a URL. Copy one of the URLs and paste it in the browser URL bar. You should see a checkout page with the coupon code created.
> Add checkout URL to B2B enrollment code checkout CSV

- hubspot/tasks.py
- hubspot/tasks_test.py
Closes #791
Skips making an API call to Hubspot for error-checking if the API key is not set.
Set `HUBSPOTAPI_KEY=None` and `HUBSPOT_ERROR_CHECK_FREQUENCY=10`  in your `.env` file.  The task should run every 10 seconds but not throw any errors as a consequence of trying to make API calls without a key.
> Do not check for hubspot errors without an api key

- b2b_ecommerce/api.py
- b2b_ecommerce/api_test.py
- b2b_ecommerce/models.py
- b2b_ecommerce/urls.py
- b2b_ecommerce/views.py
- b2b_ecommerce/views_test.py
- ecommerce/api.py
- ecommerce/models.py
- ecommerce/views.py
- ecommerce/views_test.py
Fixes #1027 
part of #858 
Merges the two CyberSource order fulfillment APIs. CyberSource will only contact one of these APIs for a given account and environment so we will need to combine the APIs and add logic to tell from the reference number which request should be handled by the regular ecommerce workflow and which by the b2b ecommerce workflow.
If the reference number prefix is missing, which sometimes happens on CyberSource error cases, the value will be stored in `Receipt`, not `B2BReceipt`, since there is no easy way to tell which one was intended. An exception will be raised in that case and reported to Sentry.
You should be able to go through the B2B workflow (see instructions in #1003) and feed the order fulfillment data to `/api/order_fulfillment/` instead of …
> Remove B2B order fulfillment API, merge with ecommerce order fulfillment API

- ecommerce/__init__.py
- ecommerce/admin.py
- ecommerce/apps.py
- hubspot/serializers.py
- hubspot/serializers_test.py
Closes #1019
Adds ": Run _n_" to the product title if there is a courseware id ending with +Rn, otherwise adds the entire `ProductVersion.text_id` value to the title.
- Set `API_HUBSPOT_KEY` to the value for the sandbox Hubspot instance (I can send it to you).
- Make sure some of your course runs have a courseware id ending in `+R1` or `+R2`, etc
- Run `docker-compose run web python manage.py sync_hubspot --products`
- Log in to hubspot ( I can give you credentials ), search for your products, and verify that the they appear in the same format as the screenshots below.
- If you create new `ProductVersion`s, Hubspot should be updated shortly.
> Add id to Hubspot product title

- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/views.py
- ecommerce/views_test.py
- static/js/components/forms/B2BPurchaseForm.js
- static/js/components/forms/B2BPurchaseForm_test.js
- static/js/components/input/ProductSelector.js
- static/js/components/input/ProductSelectorMenu.js
- static/js/components/input/ProductSelectorMenu_test.js
- static/js/components/input/ProductSelector_test.js
- static/js/factories/ecommerce.js
- static/js/flow/ecommerceTypes.js
- static/js/lib/ecommerce.js
- static/scss/checkout.scss
Part of #858 
Replaces the standard HTML select with a modal dropdown element
Go to `/ecommerce/bulk/` and select some courses and programs. It should look similar to the mockup in the linked issue. Please comment if the UI feels strange or if you notice anything which should be changed.
Desktop:
Mobile:
> Add modal selection widget for enrollment code purchase form

- app.json
- courses/management/utils.py
- courseware/api.py
- courseware/api_test.py
- courseware/constants.py
- courseware/exceptions.py
- courseware/management/commands/retry_edx_enrollment.py
- courseware/tasks.py
- courseware/tasks_test.py
- ecommerce/api.py
- ecommerce/api_test.py
- mitxpro/settings.py
Closes #985
Adds cron job to retry edx enrollments (+ a couple sensible refactors). edX enrollments are retried every 30m by default, and that time period can be adjusted via the `RETRY_FAILED_EDX_ENROLLMENT_FREQUENCY` setting
**Happy path:**
- Set the `RETRY_FAILED_EDX_ENROLLMENT_FREQUENCY` setting to something like `30` so the task will be run frequently
- Pick some course run that exists in your edX instance (probably `course-v1:edX+DemoX+Demo_Course`)
- Enroll a user in that course run, then set `edx_enrolled` to `False`
Within the time frame you provided in `RETRY_FAILED_EDX_ENROLLMENT_FREQUENCY`, the `retry_failed_edx_enrollments` task should run successfully, you should see that your user's enrollment was set to `edx_enrolled=True`, and the command log line should contain a tuple …
> Added cron job to retry edx enrollments

- app.json
- courseware/api.py
- courseware/api_test.py
- courseware/factories.py
- courseware/management/commands/repair_missing_courseware_records.py
- courseware/tasks.py
- mitxpro/envs.py
- mitxpro/settings.py
- mitxpro/utils.py
- mitxpro/utils_test.py
- users/models.py
- users/models_test.py
Closes #984 
Related to #985 (PR #1058)
Adds cron job to loop through users that aren't correctly configured in edX, and, as necessary, creates `CoursewareUser` and `OpenEdxApiAuth` records
**Happy path:**
- Set the `REPAIR_COURSEWARE_USERS_FREQUENCY` setting to something like `30` so the task will be run frequently
- Delete some local `CoursewareUser` record and also delete the same user in edX (can be done via Django admin in both cases)
- Delete some `OpenEdxApiAuth` record for that same user
- Delete some `OpenEdxApiAuth` record for a different user
Within the time frame you provided in `REPAIR_COURSEWARE_USERS_FREQUENCY`, the `repair_faulty_courseware_users` task should run successfully, and in the task results you should see the emails of the users associated with the deleted …
> Added cron job to repair courseware users

- static/js/components/B2BExplanation.js
- static/js/components/Expandable.js
- static/js/components/Expandable_test.js
- static/js/containers/pages/b2b/B2BPurchasePage.js
- static/js/containers/pages/b2b/B2BReceiptPage.js
- static/scss/checkout.scss
- static/scss/expandable.scss
- static/scss/layout.scss
Fixes #1073 
Adds explanation text on the purchase and receipt pages
Go to `/ecommerce/bulk` and verify that you see the explanation text. You should see similar explanation text for the receipt page, but note the differences in the mockups.
Purchase page
Receipt page
> Add explanation text to B2B purchase and receipt pages

- ecommerce/api.py
- ecommerce/api_test.py
Fixes #1025 
Adjusts the filter so that refunded orders are treated the same as fulfilled orders when determining coupon validity.
Create a coupon, then use it in a purchase in the checkout page (probably easiest to do a 100% off coupon). In the Django admin change the order status to "refunded" for the newest order. Try using the coupon again and it should error.
> Coupons for refunded orders should not be valid

- b2b_ecommerce/api.py
- b2b_ecommerce/api_test.py
Fixes #1114 
Sets a `payment_transaction` and `payment_type` for created coupons
Create enrollment codes and check that they have a `payment_transaction` set on the `CouponPaymentVersion` instance
> Add payment_type and payment_transaction for coupons created by B2B purchases

- courses/factories.py
- courses/signals.py
- courses/signals_test.py
- courses/utils.py
- courses/utils_test.py
Certificates: create program certificate when user has certificates in all courses in a program
> Certificates: create program certificate

- ecommerce/serializers.py
- ecommerce/serializers_test.py
- static/js/components/forms/CouponForm.js
- static/js/components/forms/CouponForm_test.js
- static/js/containers/pages/admin/CreateCouponPage.js
- static/js/factories/ecommerce.js
- static/js/flow/ecommerceTypes.js
- static/js/lib/util.js
- static/js/lib/util_test.js
- static/scss/ecommerce-admin.scss
Fixes #980 
Increases width of product selection dropdown to max `992px` (same as bootstrap medium device width) and updates the product label in the dropdown with the format:
```
<readable_id> | <title>
```
For course runs with start dates, the format is:
```
<readable_id> | <title> | <start_date>
```
Because the new format includes both the title and readable id (as well as start date for course runs) any of these values may be used for a partial or full filter.
Go to `/ecommerce/admin/coupons/` and verify the UI is as expected.
> #980 Coupons: product selection improvement

- users/api_test.py
- users/constants.py
- users/models.py
No ticket. Addresses this sentry issue: https://sentry.io/organizations/mit-office-of-digital-learning/issues/1229561383/events/8f8e5c2ee91b41798d21f5a3ead8e06a/?environment=production&project=1413655
Lowers username max length in code (not yet in database field)
Create a user with a very long name (i.e.: a name that would create a username with more than 30 chars). The generated username should be 30 chars long
> Lowered max username length to 30 (in code, not in db)

- RELEASE.rst
- b2b_ecommerce/views_test.py
- courses/factories.py
- courses/serializers.py
- courses/serializers_test.py
- courses/views.py
- ecommerce/views_test.py
- mitxpro/settings.py
- mitxpro/test_utils.py
- mitxpro/test_utils_test.py
Prereq to https://github.com/mitodl/open-discussions/issues/2182
- Allows public access on the `/api/programs/` API so that discussions can access it
- Adds the `current_price` field to the program serializer
Go to `/api/programs` while logged out and verify it returns data and that the price is present on programs
> Enhancements to programs API to support discussions ingestion

- courses/__init__.py
- courses/signals.py
- courses/signals_test.py
- courses/utils.py
#1148 
- Referenced the `CoursesConfig` in courses app.
- Will not try to generate program certificate if the course is not associated with program.  
- After creating all the `CourseRunCertificate` for a program, 
- A signal should be fired and there should be corresponding `ProgramCertifiacate`. 
- Create a course that is not linked with any program. (standalone course).
- Enroll user for this course.
- CourseRunCertificate will create after passing the course and after saving an entry in `CourseRunCertificate`, a signal will be fired that try to generate program certificate. 
- As the course is not associated with any program. ProgramCertificate will not be created.
> asadiqbal08/mitxpro-1148 ProgramCertificate will not create for standalone course

- courses/serializers.py
- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/constants.py
- ecommerce/models.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/views.py
- ecommerce/views_test.py
- mitxpro/test_utils.py
- static/js/components/forms/BulkEnrollmentForm.js
- static/js/components/forms/BulkEnrollmentForm_test.js
- static/js/flow/courseTypes.js
- static/js/flow/ecommerceTypes.js
- static/js/lib/ecommerce.js
- static/js/lib/ecommerce_test.js
- static/js/lib/queries/ecommerceAdmin.js
- static/js/lib/util.js
Fixes #1071 
Fixes performance issues with the bulk coupon assignment page. There were deeply-nested queries N+1 in the serializers being used to return 100%-off coupons and the products they apply to. This PR "flattens" those queries
Make sure the bulk enrollment form still works. The real test for performance can happen when this makes it to RC
> Optimized bulk enrollment form queries

- courses/factories.py
- courses/serializers.py
- courses/serializers_test.py
Fixes #1129 
Adds `start_date`, `end_date`, `enrollment_start`, `url`, and updates `thumbnail_url` to use absolute urls.
Go to `/api/programs/` and verify that the data looks accurate
> Update program serializer

- courses/views.py
- courses/views_test.py
Fixes #1151 
Allow anonymous access to the courses API so we can access this information from open discussions
Regarding the question about leaking data, this data is already exposed in `/api/programs/` if the course is part of a program. I don't think there is extra risk for courses which aren't part of programs.
Log out (or use incognito mode) and go to `/api/courses/`. Verify that the data exists and looks correct.
> Allow anonymous access to course list and detail API

- cms/models.py
- cms/utils.py
- cms/utils_test.py
- courses/factories.py
- courses/models.py
- courses/models_test.py
Fixes #1168 
Changes catalog logic so that if a course/program only has runs with a past start date, but has at least one run with a future enrollment end date, it still shows up in the program
For some program/course:
1. Set all associated course runs to have a past `start_date` and `enrollment_end`
1. Confirm that the program/course does not show up in the catalog
1. Choose one of those course runs, and set the `enrollment_end` to a future date
1. Confirm that the program/course now shows up in the catalog
There are some inefficiencies going on with the way we query for program/course pages, filter them, and sort them. Issue: https://github.com/mitodl/mitxpro/issues/1170
> Changed catalog logic to show courses with past start dates but future enrollment end dates

- static/js/containers/pages/login/LoginForgotPasswordPage.js
- static/js/containers/pages/login/LoginForgotPasswordPage_test.js
- static/js/containers/pages/register/RegisterConfirmSentPage.js
- static/js/containers/pages/register/RegisterConfirmSentPage_test.js
- static/scss/auth.scss
#1104 
Updated the message over the Forget-Password Screen.
- Click on the Sign In button.
- Input your email ID.
- Click on the Forget Password link.
- Enter the email which will receive the email. 
- A text message should be appeared a shown above and in the ticket design .
> asadiqbal08/mitxpro-1104 - Update Forgot Password message

- ecommerce/admin.py
No ticket - fixes minor django admin bug introduced in #1166
Fixes `Product` admin to show all Products when there is no content type filter. There was a bug that showed nothing in this admin unless a content type filter was selected
Go to Product admin page (/admin/ecommerce/product/), confirm that you see all products
> Fixed Product admin

- compliance/admin.py
- users/utils.py
- users/utils_test.py
#978 
Adds a Django admin section for export compliance results. ~~If the status is changed to `RESULT_MANUALLY_APPROVED` the user is activated if not already, and the edx account/record is repaired if necessary.~~ The section is read-only however provides an admin action to manually approve selected inquiry records. Upon manual approval the user is activated (if not already) and edx auth credentials are repaired (if required).
Create an export compliance result object with `computed_result` not equal to `MANUALLY_APPROVED` or `SUCCESS`. From the change list, select the record and apply the manual approval action. The log from the `web` service should display the process being carried out, and errors if any.
> #978 Admin interface for export compliance result

- users/admin.py
#1162 
Display account created date and last login date on user admin page
- Visit `/admin/users/user/`
- `Last Login` and `Created On` date should be there in both detail & user edit mode.
> asadiqbal08/mitxpro-1162 Display account created date and last login date on user admin page

- courses/models.py
- courses/models_test.py
- courses/serializers.py
- courses/serializers_test.py
Fixes #1165 
Moves the instructor logic to a property on the `CourseRun`, and adds additional logic to the programs API to return the instructors for the program page if there is one
Go to `/api/programs/` and check that the instructor list for the program contains all the instructors for each course run. There should not be any duplicates, each instructor should only appear once.
> Add instructors to programs API

- courses/utils.py
#1200 
Fixes a bug in the `ensure_course_run_grade` method that caused automatic course certificate generation task to fail.
Set up the environment appropriately (a finished course run, course run grades in xpro, task timing set up as required) and verify that at the configured time the certificates are generated as per the grades in your xpro database. There should be no error logs generated.
> #1200 Course certificate generation task fix

- compliance/admin.py
#1203 
Fixes #1203 
Use the admin action as designed to manually update exports inquiry log and verify that the respective user has been activated and Open edX credentials have been created.
> #1203 Exports inquiry admin action fix

- courses/api.py
- courses/serializers.py
#1205 
Modifies the `CourseRunEnrollmentSerializer` and `ProgramEnrollmentSerializer` to not include any certificate related information in output if the corresponding wagtail page does not exist for the courseware object or if the courseware object page does not have a valid `CertificatePage` child page.
N.B.: This PR also fixes a couple of small n+1 query issues in the dashboard view.
Make sure your testing user has multiple enrollments and certificate. Go to the dashboard page and verify that "view certificate" button is visible against those courses/programs for which:
- the certificate exists
- the courseware page exists in wagtail
- the courseware page has a valid and live `CertificatePage` child page
any other enrollments should not show a "view certificate" button.
> #1205 certificate button 404 fix

- courses/serializers.py
- courses/serializers_test.py
Blocked by #1196 
Fixes #1172 
Adds a union of course topics to the program API.
Go to `/api/programs/` and verify that the topics for each program match all topics in each course.
> Add topics to programs API

- courses/management/commands/refund_enrollment.py
- courses/management/utils.py
- courses/management/utils_tests.py
Fixes #1199  
- Add `order` an optional parameter in refund_enrollment command.
- Added tests for utils method.
- Purchase some programs/courses via full-price coupon
- Try refunded via the refund_enrollment management command and provide 'order' parameter
- It should set the associated order to refunded if `order` passed otherwise first enrollment would be refunded.
> add order optional parameter in refund_enrollment command

- static/js/lib/courses.js
- static/js/lib/courses_test.js
- static/js/lib/util.js
Fixes #1192 
As a user, I'd like to know the exact time that the course starts, so I'm not checking and re-checking the dashboard over a 24 hour period. So displaying the start time along with date for upcoming courses. 
- Enroll in a course or a program. 
- Start date of product would be in future. 
- After landing to dashboard, time in `AM/PM` format should be displayed.
- Verify the time along with End Date too
> asadiqbal08/mitxpro-1192 Show time along with date for upcoming courses.

- courses/factories.py
- courses/serializers.py
- courses/serializers_test.py
- courses/views.py
- courses/views_test.py
Fixes #1224 
Filters out programs and course runs which don't have products, and filters out non-live programs, courses, and course runs
Set `live=False` on a program and view `/api/programs/`. It should not show up.
> Filter courses, runs, and programs based on product and live status

- mitxpro/templates/base.html
- static/js/containers/pages/CheckoutPage.js
#843 
Logs error to Sentry for basket update response as well as checkout response if the status was non 200 and there was no body.
Configure sentry and make sure you return a non-200 response from the API for the basket and checkout operations.
Checkout page
Sentry issue
Sentry error (response not in format so the whole response object is dumped)
Sentry exception (response is in format so only the API error object is dumped)
> #843 Checkout: non-200 responses

- cms/templates/partials/hero.html
- cms/views_test.py
fixes #1119 
Hide **Watch Now** button if there is no video to play
Remove Video Section from Home page or remove Video URL from video section and check whether **Watch Now** button is available or not.
> MIT xPRO - 1119 Watch Now button should come only in the presence of video

- ecommerce/api_test.py
- ecommerce/models.py
- ecommerce/views.py
- static/js/components/forms/BulkEnrollmentForm.js
- static/js/components/forms/BulkEnrollmentForm_test.js
- static/js/factories/ecommerce.js
- static/js/flow/ecommerceTypes.js
fixes #1184 
fixes #1211
In ecommerce admin, sort all the dropdowns
**Companies sorted alphabetically**
**Products sorted by readable id**
**Coupons sorted alphabetically**
> add sorting for all ecommerce adming pages

- b2b_ecommerce/views.py
- b2b_ecommerce/views_test.py
- ecommerce/api.py
- ecommerce/constants.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- ecommerce/models.py
- ecommerce/models_test.py
- ecommerce/utils.py
- ecommerce/views.py
- mail/api.py
- mail/api_test.py
- voucher/views.py
Closes #1213 
(Required)
- Make sure you have access to Mailgun logs (you should be able to log in at mailgun.com and use your MIT email)
- (Optional) Set your `MAILGUN_SENDER_DOMAIN` to the xpro-ci setting. It will be easier to find your logged messages and it will create less noise for otherwise-important domains
- Create a bulk coupon for some run/program (if you don't already have one), and use the Bulk Enrollments form to assign some of those coupons to two or more users
- Both of those pages can be found under `/ecommerce/admin/`
- Feel free to use 2 different emails that will go to the same address (`me@mit.edu`, `me+1@mit.edu`)
- If the bulk enrollment submission was successful, you should see the messages in the Mailgun logs
- Click on each message in the Mailgun logs to see the …
> Added custom metadata options in mail API, added metadata to bulk enrollment emails

- cms/models.py
#1250 
Fixes #1250, adds the ability to create a `SignatoryIndexPage` from the CMS rather than solely relying on `setup_index_pages` management command to set up the index page.
Make sure you do not have an existing signatory index page under the home page. Click `Add child page` under the home page, you should be able to see `SignatoryIndexPage` as an eligible candidate type for child page.
> #1250 Add SignatoryIndexPage from CMS

- cms/models.py
- cms/templates/partials/hero.html
- cms/views_test.py
- courses/models.py
- courses/models_test.py
- courses/views_test.py
#1222 
Modifies `start_date` and `next_run_date` calculations in programs to use the first course in the program (`position_in_program=1`).
Create different courses and course runs for a program. Verify that the start date and next run dates are those set for the first course only. This includes hiding the "enroll now" button if the first course in the program does not have an upcoming course run to enroll into.
> #1222 Program next run date comes from first course

- courses/factories.py
- courses/utils.py
- courses/utils_test.py
#1265 
Modifies the certificate generation method to consider the `grade.passed` and `grade.percentage` (`grade.grade` in xPRO) while creating/updating/deleting certificates for course run grades. 
Run any sync commands or use the `courses.utils.process_course_run_grade_certificate` method (used in the scheduled app tasks) to sync/generate grades and certificates. No certificates should be generated for any grades that have either:
- `passed=False`
- `percentage=0.0` (for Open edX grade object) or `grade=0.0` (for xPRO `CourseRunGrade` object)
> #1265 Certificate generation only on passed status

- cms/templates/partials/hero.html
Fixes #1280 
Fixes the regression bug that caused "Apply Now" button to disappear on external course pages.
Go to any external course page, the "Apply Now" button should appear. Go to any other product page with a product setup properly and the "Enroll Now" or "Enrolled" button should appear as expected.
> #1280 External course page apply now button fix

- ecommerce/api.py
- ecommerce/api_test.py
No ticket – this bug was observed by @pdpinch
Changes the logic for fetching a user's unredeemed coupons so that the email matching is case-insensitive. If the user has a product coupon assignment with an email that was entered with differently-"cased" letters, they should still see a notification to redeem their coupon.
**Confirm that you can see the notification:**
- In Django admin, create a product coupon assignment for your user, enter the email with different combinations of uppercase and lowercase, and leave "redeemed" unchecked
- Log in as that user
You should see the unused coupon notification when you complete login. 
**Confirm that order completion sets the assignment to redeemed:**
- Complete an order using the coupon from the assignment you created above
- Check the product …
> Changed product coupon assignment match to be case-insensitive

- ecommerce/admin.py
#1245 
Adds search on product and product version admin. For product admin:
- `title`
- `readable_id`
are searchable. For product version:
- `title`
- `readable_id`
- `text_id`
- `description`
are searchable.
Go to the Django admin for Product and ProductVersion. You should be able to search through the objects using any of the attributes defined above.
> #1245 Add search to product and version admin

- app.json
- courseware/api.py
- mitxpro/settings.py
No ticket – [relevant sentry issue](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1234039550/) 
Makes the edX API client timeout configurable via settings, and sets the default timeout to 60s (rather than the library default of 25s)
Run some of our management commands that use the API client (e.g.: `sync_grades_and_certificates`) and make sure it isn't broken. You can also use `courseware.api.get_edx_api_client` or `courseware.api.get_edx_api_grades_client` in a Django shell and make sure requests are successful. 
See sentry issue
> Added setting for controlling edx API client request timeout

- cms/templates/certificate_page.html
- static/scss/certificates/certificate.scss
#1301 
Modifies the certificate template to show up to 4 signatures per row for desktop- and table-width screens, 3 signatures per row for intermediate width and 1 signature per row for small width screens.
Visit any certificate view, the UI should behave as described above.
> #1301 Fix certificate view (4 signatures inline)

- app.json
- mitxpro/envs.py
- mitxpro/settings.py
- mitxpro/settings_test.py
#1276 
Adds a configurable `CSRF_TRUSTED_ORIGINS` environment variable and comma separated list parser method.
Set `CSRF_TRUSTED_ORIGINS` environment variable to a comma separated string for domains and verify that `django.conf.settings.CSRF_TRUSTED_ORIGINS` value is a list of all the domains listed in the env var.
> #1276 Configurable CSRF_TRUSTED_ORIGINS env var

- ecommerce/serializers.py
- ecommerce/serializers_test.py
Fixes #1307 
Adds logic to filter out invalid selected runs from the basket API. This fixes the issue because when checkout happens, the basket is first patched with the new list of run ids, which now excludes the invalid one.
To reproduce on master:
- Go to the checkout page for a program product
- Select course runs in a program and attempt to checkout. You should see the Cybersource form. Don't fill it out, we don't need to fulfill the order.
- Make a course run invalid in some way. Setting `live=False` is probably easiest, or change the dates so it is invalid.
- Go to /checkout, select some runs, and click "Place your order". You should see a validation error "Only one run per course can be selected"
Check out this branch and repeat the above steps. You should not see the validation …
> Filter invalid runs from selected runs list

- users/utils.py
- users/utils_test.py
#1259 
Fixes the `users.utils._reformat_for_username` method to replace invalid Turkish characters with a suitable substitute so that user onboarding does not fail on Open edX.
Try to sign up with a user with any of the following characters in the "Full Name" attribute, as many times as required:
`iiıIİI`
The user signup should be successful and user should also be created on the Open edX instance. In both xPRO and Open edX the username should have all of these characters replaced with a lowercase `i`.
> #1259 Usernamify fix for Turkish characters

- static/js/components/Header.js
#1243 
Adds user context to Sentry so error reports provide more insight into the user that is having the issue.
Set up a Sentry instance and try to reproduce a bug (raising an `Http404` from the `ecommerce.views.BasketView` is a quick way to do that) and verify that the errors logged in Sentry include the user context as shown in the screenshot below.
> #1243 Set user context for Sentry

- static/scss/certificates/certificate.scss
fixes #1302 
(Required)
**EARLIER**
**NOW**
**FIREFOX**
**CHROME**
> make Firefox Certificate print stylesheet makes page elements size identical to Chrome

- app.json
- ecommerce/views.py
- ecommerce/views_test.py
- mitxpro/context_processors.py
- mitxpro/serializers.py
- mitxpro/settings.py
- mitxpro/templates/base.html
- mitxpro/templates/partials/gtm_body.html
- mitxpro/templates/partials/gtm_head.html
- mitxpro/views.py
- mitxpro/views_test.py
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/DashboardPage.js
- static/js/flow/declarations.js
- static/js/global_init.js
#1173 
Adds a GTM container trigger/tag for tracking purchases. This PR includes carrying UTM variables through the session for proper source/medium attribution for the marketing platforms. The tag registers the purchase event with UA ecommerce.
Setup the GTM CI container in your settings and complete a purchase with Cybersource. You should be able to see the events/purchases in GA and GTM debugger (if enabled).
> #1173 Purchase event tracking through GTM

- courses/management/commands/defer_enrollment.py
- courses/management/commands/transfer_enrollment.py
fixes #1234 
fixes #1256
Allow learners to be tranfered or enrolled into expired course runs 
Try to run defer an user to an expired course run. Should not check for expired run if `--f` flag is there.
`./manage.py defer_enrollment`
> Not check for expired run if there is --force flag

- sheets/api.py
No ticket
Fixes file watch request failures for a file that exists in a shared drive
Run the management command for our enrollment code request sheet, which is in a shared drive
> Fixed Google Sheets file watch request

- sheets/api.py
- sheets/tasks.py
No ticket – this was noticed while testing on RC
When coupon assignment spreadsheets are fetched and processed to create new coupon assignments, those spreadsheets are now fetched and loaded into memory one at a time.
I tested this using ngrok locally. Further functional testing can be done on RC
This is the library method that was being used to fetch spreadsheet data before this PR: https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/client.py#L160-L170. It fetches all of the spreadsheets that match a query and immediately creates object representations of all of them in memory. This was causing issues with worker memory in RC. Loading/serializing these objects one-by-one should help with that memory issue
> Changed coupon assignment sheet handling to fetch one at a time

- hubspot/management/commands/configure_hubspot_bridge.py
- hubspot/serializers.py
- hubspot/serializers_test.py
You will need to run the management command `configure_hubspot_bridge` on production before these changes take effect.
To backfill data, run the management command `sync_hubspot`.
closes #1352 
This PR adds product_id to the hubspot line item
1. Create an ecommerce Line (easiest way is with a factory).
2. Sync the Line, Order, Purchaser, Product with hubspot (run the sync_hubspot management command)
3. Find the Order associated with the line in the hubspot deal interface and note down the Deal Id (its in the URL)
4. Send a get request to `https://api.hubapi.com/crm-associations/v1/associations/{deal_id}/HUBSPOT_DEFINED/19?hapikey={settings.HUBSPOT_API_KEY}`. This will return the ids of the line items associated with the deal.
5. Then send a get request to …
> Add product_id to hubspot line item

- app.json
- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- mitxpro/settings.py
closes #1351 
This PR adds a new step to the user creation pipeline. After a user confirms their email address, the email and a hubspot cookie (if it exists) are sent to the hubspot forms API.
Create a new account and once you confirm your email address, check that the email shows up on hubspot.
You should visit any page other than the create account page to pick up the cookie. I don't know if adblockers block that type of cookie but to be safe turn them off if you have them. The form_id for the dev hubspot account is `9c823b8c-5db8-42b9-8a93-c411ceb55aaf`.
> Send cookie to hubspot when a user creates a new account

- app.json
- courses/management/commands/sync_courseruns.py
- courses/tasks.py
- courses/utils.py
- courses/utils_test.py
- courseware/api.py
- mitxpro/settings.py
#1246 
Adds a management command (scheduled task to be included as well) that allows syncing course run information from Open edX instance for any course runs that exist on the xPRO side. Information that is fetched and updated is:
- title
- start date
- end date
- enrollment start date
- enrollment end date
Run the management command:
`docker-compose exec web python manage.py sync_courseruns`
> #1246 sync course runs from edx

- sheets/api.py
- sheets/management/commands/setup_request_sheet_file_watch.py
- sheets/tasks.py
No ticket. This fixes a bug found on RC
- Fixes a bug where the channel ID of a file watch record in the database was not being updated when a new file watch was created via API. This resulted in file watch requests from Google being incorrectly rejected for having the wrong channel ID.
- Fixes a bug in the the task to renew the file watch (forgot to change the number of values to unpack from an API method)
- Adds a couple options to the file watch management command to help us address situations where the file watch isn't working as expected.
Code review only. I tested this locally with ngrok, and this will be tested further in RC
> Fixed file watch bug and added management command options

- sheets/tasks.py
No ticket. This avoids a potential bug I noticed during RC testing
In our running job that creates/renews a file watch on the coupon request sheet, changes the logic so that the file watch is always renewed even if the current one is unexpired.
> Forced spreadsheet file watch renewal in running job

- mitxpro/settings.py
- sheets/api.py
- sheets/utils.py
Closes #1381 
Supports the addition of a requester email column in the coupon request spreadsheet. When the requester email column has been added to the spreadsheet, we can flip a feature flag and the row parsing will continue to work correctly.
> Modified request sheet handling to allow for requester email column

- app.json
- mitxpro/settings.py
- mitxpro/settings_test.py
Similar to #902
Disables server-side cursors by default, because they can cause invalid cursor errors when query iterators are used in conjunction with pgbouncer.  Adds an optional .env setting to override this.
- Nothing should break and tests should pass.
https://code.djangoproject.com/ticket/28062
> Disable server-side cursors by default to avoid invalid cursor errors

- app.json
- mitxpro/settings.py
N/A
With the introduction of Fastly to production the `HOST` header isn't the actual domain that we want SSL redirects sent to. Adding override of that value through an environment variable.
> Added setting for overriding host used in SSL redirect

- courses/models.py
Fixes #1404 
Displays product's readable id when selecting the connected course/program for a `CoursePage`/`ProgramPage` in CMS.
Go to the CMS to add/edit any `ProgramPage` or `CoursePage`. The course/program drop down should display the readable id as well as the title.
> #1404 display readable id when selecting courseware in cms pages

- app.json
- courses/tasks.py
- mitxpro/settings.py
Fixes #1395 
Adds a `CERTIFICATE_CREATION_DELAY_IN_HOURS` environment variable which defines how long (in number of hours) is the automated certificate creation delayed for all courses.
Have course runs end less than the configured (default: 48) delay from current time. Run the task. The task should exclude all course runs that have ended more recent than the delay period.
> #1395 Delay automated certificate creation by a number of hours

- static/js/components/forms/CouponForm.js
- static/scss/ecommerce-admin.scss
No ticket - this is in response to a mistaken intention of this option in some production coupon codes
Adds clearer messaging around the 'automatic' option for the bulk coupon creation form
Make sure the form looks reasonable and still works as expected
> Added warning for 'automatic' option in coupon creation form

- courses/serializers.py
- courses/utils.py
#1434 
- If user earned a ProgramCertificate then corresponding ProgramEnrollment should be present in the system for that user and program.
- On the dashboard, there should be a link to each courserun's certificate, as well as a link to the program certificate.
- Execute the scenarios that mentioned in #1434 
- Test all other scenarios as well e.g. Receipt functionality etc.
> Create a ProgramEnrollment along with ProgramCertificate

- sheets/api.py
- sheets/api_test.py
- sheets/conftest.py
- sheets/exceptions.py
- sheets/utils.py
- sheets/utils_test.py
- sheets/views_test.py
Closes #1417 
Attempts to use Google Drive API batch requests to share coupon assignment sheets with a list of emails, and defaults to individual sharing requests (as we had before) if that fails
There is some detail in the `share_drive_file_with_emails` and `batch_share_callback` function docstrings regarding the decision to attempt a batch share, then default to individual sharing requests if that fails.
> Added batch Drive file sharing

- app.json
- courses/utils.py
- mitxpro/settings.py
- requirements.in
- requirements.txt
#1418 
Updates the sync course run method to include the username in the request for course details in edX in order for the requesting service worker user to be identified correctly. This should fix any issues with edX configured to display course details only to `staff` users.
Make sure:
- edX is configured to display course details only to `staff` users (details in #1418 ). 
- `OPENEDX_SERVICE_WORKER_USERNAME` is set in the environment to the username of the user whose api token is set in `OPENEDX_SERVICE_WORKER_API_TOKEN`.
Run the `sync_courseruns` management command. It should be able to sync titles and dates from edX to xPRO given matching courses (runs) exist on both sides (matching readable_id).
> #1418 Fix course run sync from edX

- package.json
- yarn.lock
https://trello.com/c/P0gpXVnP/36-fix-build
Upgrade `autoprefixer` to fix builds
Build should pass.
Site should run without any errors.
Builds were failing because of this error.
```
Error output found:
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
End of output
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mitxpro@0.0.0 codecov: `CODECOV=1 ./scripts/test/js_test.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mitxpro@0.0.0 codecov script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-08T06_30_47_691Z-debug.log
```
> upgrade autoprefixer to fix builds

- mitxpro/settings.py
No ticket. Related to repeated Sentry errors regarding expired webhooks (aka file watches)
Changes the default renewal period for file watch/webhook renewal to 12 hours instead of 23.5 hours
This is a stop-gap solution for the many expired file watches we're experiencing in all environments due to unreliable scheduled task execution. https://github.com/mitodl/mitxpro/issues/1458 will address the reliability, at which point this can be reverted.
> Changed default renewal period for Drive webhooks to 12hrs

- cms/embeds_test.py
N/A
No ticket - reverts some test cases introduced in #705
Removes test cases that test the 'get_embed' Wagtail library function
Build should pass
These test cases should not exist for at least 2 reasons:
1. They test a library function
1. They make live HTTP requests to an external service
> Removed 'get_embed' Wagtail library function tests

- ecommerce/api.py
- ecommerce/api_test.py
Fixes #1481
Fixes situations where a bulk enrollment coupon was redeemed that was _not_ created in a bulk enrollment sheet (i.e.: created in the ecommerce admin form)
- Create a coupon and assign it via the ecommerce admin (`/ecommerce/admin/`)
- Redeem it
The product coupon assignment for that coupon should be set to redeemed=True, and there should be no error in your logs
> Fixed coupon redemption handling to account for non-spreadsheet bulk enrollments

- courseware/api.py
- courseware/api_test.py
- courseware/exceptions.py
- courseware/management/commands/repair_missing_courseware_records.py
- ecommerce/api_test.py
- mitxpro/test_utils.py
- mitxpro/test_utils_test.py
- mitxpro/utils.py
- mitxpro/utils_test.py
- users/utils.py
Closes #1461 
Streamlines handling and messaging for responses to failed HTTP requests
The easiest way to test the error handling for the issue described in the linked issue is this:
- Delete the courseware user for one of your users (http://xpro.odl.local:8053/admin/courseware/coursewareuser/)
- Also delete the user in edx (http://edx.odl.local:18000/admin/auth/user/)
- Change the OAuth application client ID value in edX so it doesn't match the client ID in your xpro settings anymore (http://edx.odl.local:18000/admin/oauth2_provider/application/)
- Run `courseware.api.repair_faulty_courseware_users` in an xpro django shell
You should see a log message like this: `Failed to repair faulty user gavin-sidebottom (gwsidebottommit+2@gmail.com). Response - code: 400, url: …
> Streamlined failed HTTP response messaging

- sheets/tasks.py
Fixes #1493
Fixes an issue where if a user enrolled in a coupon assigned via an assignment sheet, that status would be reflected one row below the correct cell in the assignment sheet
> Fixed off-by-one error with coupon assignment sheet enrolled status

- package.json
- requirements.txt
- yarn.lock
https://github.com/mitodl/mitxpro/network/alerts
Tried to fix the handlebar and django version conflicts
Handlebars version was already updated previously to `4.5.3` but `yarn.lock` contains the both `4.5.3` and `4.1.2` and another package `istanbul-reports@^2.2.4:` was dependent on `handlebar@4.1.2` so the PR added the required version under `resolutions` section of `package.json` file. 
Please let me know if anything needs to update here.
> handlebars plus django version update

- ecommerce/api.py
- ecommerce/api_test.py
No ticket – related to Zendesk ticket [44392](https://odl.zendesk.com/agent/tickets/44392)
Adds error logging if a program order is being completed and no course run selections are found
Tests passing should be enough
This obviously isn't intended to fix the underlying problem in the Zendesk ticket linked above. We're not positive about what caused that issue. The intent behind the logging in this PR is to help us narrow down the cause if a similar issue happens again in the future.
> Add error logging for program orders with no run selections

- cms/templates/partials/enroll_button.html
- cms/templates/partials/hero.html
- cms/templates/partials/subnav.html
- static/scss/detail/subnav.scss
[HEROKU](https://xpro-ci-pr-1512.herokuapp.com/courses/course-v1:SEED+SysEngBx3/)
[sticky-enroll-now-button](https://trello.com/c/mPpk0Ox5/40-sticky-enroll-button)
Fix the position of `Enroll Now` button in navigation bar.
- Visit Product detail page and verify the position and behavior of `Enroll Now` button.
- Verify the `Enoll Now` button behavior for anonymous users.
- Verify the `Enroll Now` button look & feel for smaller screens. 
- `Enroll Now` button has different states based on these [condtions](https://github.com/mitodl/mitxpro/blob/master/cms/templates/partials/hero.html#L41-L62) so verify the other states of the button is also rendering on the sab navigation bar correctly.
> Sticky Enroll Button Changes

- sheets/utils.py
No ticket - Fixes bug introduced in #1503 
Fixes status column definition for the refund spreadsheet so it's an integer again, not a generator
> Fixed bug with column definition for refund request sheet

- mail/templates/course_run_unenrollment/body.html
No ticket. Discovered during spreadsheet enrollment testing
Changes unenrollment email template text to respect course runs that have no start date
In a Django shell, run `ecommerce.mail_api.send_course_run_unenrollment_email` using an enrollment for a course run with and without a start date value.
> Fixed unenrollment email start date text

- cms/forms.py
Fixes an issue caused by argument auto-positioning by pylint that resulted in `CertificatePage` not being able to be saved.
Any `CertificatePage` should be saved without throwing an error, with/without CEU overrides.
> Fix Course Certificate CEUs Override

- ecommerce/api.py
- ecommerce/serializers.py
- ecommerce/views_test.py
- static/js/components/forms/CheckoutForm.js
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/flow/ecommerceTypes.js
https://trello.com/c/8pmf7Bnk/32-pass-readable-product-id-to-checkout-page-in-url
Pass readable product id to checkout page in URL
Just try to load the Checkout out page with `?product={product_id}/{readable_id}`.
**In Active Course**
http://xpro.odl.local:8053/checkout/?product=course-v1:edX+DemoX+Demo_Course
http://xpro.odl.local:8053/checkout/?product=2
**Offer courses that are open for enrollment**
> Pass readable product id to checkout page in URL

- static/js/containers/App.js
https://trello.com/c/ZbfEpf7L/68-bug-account-settings-page-displays-to-the-anonymous-user
Make Account Settings private, it should not be accessible to Anonymous User
Log out and go to the page [Account Settings](http://xpro.odl.local:8053/account-settings/)
> Make Account Settings page private

- ecommerce/serializers.py
- ecommerce/views.py
- static/js/containers/pages/b2b/B2BPurchasePage.js
- static/js/containers/pages/b2b/B2BPurchasePage_test.js
- static/js/factories/ecommerce.js
- static/js/flow/ecommerceTypes.js
https://trello.com/c/a8HfV6Hi/74-bug-setting-visible-in-bulk-form-to-false-hides-product-from-ecommerce-coupons-form
Setting "Visible in Bulk Form" to false, the product should still appear in the coupons form, because /ecommerce/admin/coupons/ is not the bulk form.
Just set the "Visible in Bulk Form" to false on /admin/product/ and it should not hide the product from coupon page but on /ecommerce/bulk/ page
> Load products on coupon page with visible_in_bulk_form=false

- courses/api.py
- courses/management/utils.py
[Ticket](https://trello.com/c/dsdx9q4h/71-bug-user-with-bad-edx-auth-can-complete-orders-and-end-up-with-no-enrollment-records)
Fix if the course run enrollment in edX fails, but a CourseRunEnrollment record in xpro should exist.
Yet just introduced to catch the `NoEdxApiAuthError` that seems as a blocker to the xPro flow. 
- If `OpenEdxApiAuth` model does not have the corresponding user entry then raising `NoEdxApiAuthError` in code base.
> asadiqbal08/mitxpro: Users with bad edX auth can complete orders

- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/lib/util.js
https://trello.com/c/dQDZAb4f/39-on-checkout-page-for-program-all-courseruns-should-be-from-the-same-run
On checkout page for program, all courseruns should be from the same  run
- Create a Program with multiple courses and multiple runs.
- Go to the program page.
- Try enrolling in next run from "more dates"
- Preselected course runs should be selected
- All course runs should be selected according to first course run. (all other course runs should start at the same time or after the first select course run)
As a user, when I check out I expect the dropdown for course dates to default to a set of dates in order. In other words, if the next available run of the first course is R5, I expect all the course runs to default to R5. It is confusing if, for example, the second course has a start …
> course run on program checkout page

- Dockerfile
- docker-compose.yml
- hubspot/conftest.py
None
- Fixes test failures due to mismatching postgres versions. Since the current postgres version used by heroku is 11.6, this PR will pin the docker  container to the same version
- Upgrades to python 3.7. With postgresql-client-9.6 no longer needed it was easiest to specify the Python 3.7 docker container which includes an updated postgresql-client version
Website should load correctly. docker-compose.yml is only used in testing and development so there should not be any change in production
> Upgrade postgres version in docker-compose, and update to Python 3.7

- static/js/components/forms/CheckoutForm_test.js
- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/CheckoutPage_test.js
No ticket. This is related to a bug that #1515 only partially fixed
Initializes all course run selection boxes in the checkout page such that there is no selection
Go to the checkout page with a program or course run. You can also test using a `preselect` querystring param to indicate a preselected course run. In all cases, the course run select boxes for a program in the checkout page should _not_ have a selection, even if `preselect` was provided.
We've had a lot of issues with users enrolling in a program, having incorrect/unexpected course runs preselected, and completing checkout without changing them. The cause of the underlying bug is that we have always considered the soonest unexpired course run to be the one that should be preselected for each course, when we should have been …
> Removed course run preselect logic in checkout

- sheets/api.py
- sheets/constants.py
- sheets/enrollment_change_api.py
- sheets/management/commands/setup_file_watch.py
- sheets/utils.py
- sheets/views.py
No ticket
Solves a problem that PR #1548 didn't quite fix. This fully sets up deferral requests to be processed when the enrollment change spreadsheet is changed.
Code review only. No manual testing needed.
The problem with the PR mentioned above is that file watch requests (aka webhooks) are sent when anything in an entire spreadsheet changes, and those requests are not limited to specific worksheets within the spreadsheet. In the PR above I conflated spreadsheets and worksheets, and during testing I was looking for the wrong changes.
> Actually fixed enrollment change sheet file watch renewal

- courses/urls.py
- courses/views/v1/__init__.py
- courses/views_test.py
[Ticket](https://trello.com/c/vfPJO16Y/45-add-version-number-to-course-and-program-apis)
Adds the course/program APIs to `/api/v1/` path as well. The existing `/api/` URLs still work.
The new `/api/v1/` URLs should work as expected as well as the old `/api/` ones.
> API v1 routes

- static/js/containers/pages/CheckoutPage.js
- static/js/containers/pages/b2b/B2BPurchasePage.js
- static/js/containers/pages/b2b/B2BPurchasePage_test.js
- static/js/lib/queries/ecommerce.js
- static/scss/checkout.scss
- static/scss/common.scss
[Ticket](https://trello.com/c/ftyJTt7s/82-bulk-purchase-add-loading-spinner-to-form)
Bulk Purchase: add loading spinner to form until products are ready to list down
Just load the `/ecommerce/bulk/` page and see if right on loading it list downs the products.
> add loading spinner to bulk purchase page

- mitxpro/sentry.py
- mitxpro/settings.py
Closes #1527 
Adds code to filter out shutdown errors from sentry
The app should run, otherwise this is best tested in CI/RC since the exact conditions can't be replicated under docker.
> Suppress system shutdown sentry errors

- ecommerce/migrations/0029_bulk_assignment_date_fields.py
No ticket. The build on master was broken b/c of a name conflict in ecommerce migration files
Run migrations
> Fixed conflicting ecommerce migration file names

- static/js/components/notifications/index.js
- static/js/components/notifications/index_test.js
- static/js/constants.js
- static/js/containers/pages/b2b/B2BReceiptPage.js
- static/js/containers/pages/b2b/B2BReceiptPage_test.js
- static/js/reducers/notifications.js
[Ticket](https://trello.com/c/YoqSYlC5/93-bulk-purchase-change-error-message-to-an-href-instead-of-a-mailto)
Bulk Purchase: change error message to an HREF instead of a MAILTO
(Required)
(Optional)
(Optional)
> Bulk Purchase: change error message to an HREF instead of a MAILTO

- docker-compose.yml
[Ticket](https://trello.com/c/mPKs84cj/112-pin-redis-version-to-505-in-docker-config)
Pins `redis` to version `5.0.5` in docker config in order to avoid unintentional upgrades.
App should function as expected, redis should report version number `5.0.5`.
> Pin redis version to 5.0.5 in docker config

- docker-compose.yml
[Ticket](https://trello.com/c/etErLc2S/111-pin-nginx-to-1161-in-docker-configuration)
Pins `nginx` version to `1.16.1` in order to avoid unnecessary updates.
Application should function as normal. Version of the `nginx` service should now always be `1.16.1`.
> Pin nginx to 1.16.1 in docker config

- users/management/commands/retire_users.py
- users/management/commands/retire_users_test.py
https://trello.com/c/gshJi9u0/108-retire-users-by-email-address-in-addition-to-username
Update retire_users management command to retire users by email address in addition to username.
```
Retire one or multiple users. Username or email can be used to identify a user.
For single user use:\n
`./manage.py retire_users --user=foo` or do \n
`./manage.py retire_users -u foo` \n or do \n
`./manage.py retire_users -u foo@email.com` \n or do \n
For multiple users, add arg `--user` for each user i.e:\n
`./manage.py retire_users --user=foo --user=bar --user=baz` or do \n
`./manage.py retire_users --user=foo@email.com --user=bar@email.com --user=baz` or do \n
`./manage.py retire_users -u foo -u bar -u baz`
```
> Retire users by email address in addition to username

- cms/models.py
- cms/views_test.py
https://trello.com/c/Xuu2fpzc/113-bug-suggest-future-program-run-on-a-program-catalog-page-instead-of-a-currently-active-one
On a program detail page (as accessed from the catalog), this fixes the "Enroll Now" link so that a future program run is set as the product in checkout instead of a currently-active one
- Create 2 `ProgramRun` objects for one `Program`. One with a start and end date that are before and after todays date, and one with a future start date
- Visit that program's detail page and click "Enroll Now"
The `product` param in the checkout URL should match the `full_readable_id` for the future program (`full_readable_id` can be seen in Django admin, e.g.: `program-v1:xPRO+DgtlLearn+R2`)
> Choose future program run from catalog instead of active one

- mail/templates/password_reset/body.html
https://trello.com/c/Ejl8HRwy/102-add-a-text-only-link-on-password-change-emails
Add a text-only link in the password change email
- Goto sign-in page
- Click on forgot password
- Enter your email.
- You should see an email with a text-only link.
> Add a text-only link in password change email

- mail/templates/verification/body.html
[Ticket](https://trello.com/c/RKAYqY01/117-add-a-text-only-link-on-verification-emails)
Add a text-only link on verification email.
- Create an account and visit inbox to verify your email.
> asadiqbal08/Add a text-only link on verification emails

- ecommerce/serializers.py
- ecommerce/views_test.py
- static/js/containers/pages/CheckoutPage.js
https://trello.com/c/4oHTPMeZ/104-bug-cant-choose-an-active-course-run-when-the-current-product-is-expired
Fix Bug: can't choose an active course run when the current product is expired.
**Steps**
- Create a two course runs associated with the same course. R1 should have an enrollment end date and course end date in the past (i.e. the run is not available for enrollment). R2 should have an enrollment end date and a course end date in the future (the run is available for enrollment.
- Create a product for R1 and R2.
- Go to the checkout page for the product for R1. Since R1 is no longer open, it shouldn't appear in the drop down. But R2 should.
- Select R2.
- Click Place Order **(You should proceed to CyberSource for checkout)**
(Optional)
> Choose an active course run when the current product is expired.

- cms/models.py
- cms/templates/home_page.html
- cms/templates/partials/hero.html
- cms/templates/partials/subnav.html
- cms/templates/product_page.html
[Ticket](https://trello.com/c/4mqeJWn6/96-xpro-503-errors)
Reduces redundant queries on product and home page due to templates not using cache/prefetch.
NB: This PR does not completely fix the related error, only makes an incremental change. Mainly the timeout issues are coming from the way Wagtail fetches pages and image renditions. That will need some in-depth changes to the code base.
Use Silk or Debug Toolbar to verify number of queries goes down on home and course/program page when you switch to this branch.
> Reduce redundant queries on templates

- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- authentication/views_test.py
Fixes #948
Fixes an edge case where a user logs in but is inactive and should be activated.
On master, verify you see the behavior:
- For an existing user whom you can login with, set `is_active = False`
- Attempt to login, verify that you see the described behavior
On this branch, verify that you are able to successfully login and the user is activated.
> Fix user login for non-new, not yet activated users

- b2b_ecommerce/admin.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- mail/templates/b2b_receipt/body.html
[Ticket](https://trello.com/c/hGlWDI7b/85-bulk-purchase-update-receipt-email-to-match-single-purchase-receipt)
Update the UI for B2B receipt page as described in the ticket. 
- Visit `/ecommerce/bulk/`
- Purchase some seats for a product 
- Execute a flow with discount code 
- Execute a flow with Cybersource payment.
```
from b2b_ecommerce.models import B2BOrder
order = B2BOrder.objects.get(id=7)
```
> B2B Bulk Receipt UI Updates for Email

- sheets/conftest.py
- sheets/coupon_request_api.py
- sheets/utils.py
Closes #1587 
Adds support for ignored rows in a coupon request spreadsheet. This means that an admin can set a simple value in the spreadsheet data to ensure that xpro does not attempt to process the row and create enrollment codes. This is useful when a user has entered a request for enrollment codes that is invalid and we have no intention of "repairing" the entry.
Like other xPro sheets features, this is code review only. This will be manually tested in RC
The coupon request sheet was my first attempt at spreadsheets-as-an-admin-tool. A bunch of lessons were learned (i.e.: the fact that rows can't be deleted and should instead be set to ignored) and they were applied to the change of enrollment spreadsheets. This PR just applies that same functionality to the coupon request sheet.
> Added support for ignored rows in a coupon request spreadsheet

- cms/templates/certificate_page.html
- cms/templates/partials/faculty-carousel.html
- cms/templates/partials/image-carousel.html
- cms/templates/partials/learning-techniques.html
- cms/templates/partials/testimonial-carousel.html
- courses/models.py
- mitxpro/urls.py
- static/js/containers/pages/ReceiptPage.js
Closes #1566
Uses Wagtail's [dynamic image serve view](http://docs.wagtail.io/en/v2.0/advanced_topics/images/image_serve_view.html) to generate URLs for many of our different image renditions. See background context for an explanation.
- Fill in CMS data that will render images in each one of the subpage types that use the templates that were changed in this PR
- Visit the CMS pages and confirm that the images still show up exactly as they did 
- From [Wagtail docs](https://docs.wagtail.io/en/v2.8/advanced_topics/images/image_serve_view.html#generating-dynamic-image-urls-in-python): "One advantage of using dynamic image URLs in the template is that they do not block the initial response while rendering like the {% image %} tag does.". These periodic 503s were likely caused by Wagtail's …
> Used dynamic image loading for select CMS pages

- requirements.in
- requirements.txt
[#132](https://trello.com/c/L5FsIbjl/132-upgrade-pillow-to-version-622-or-later)
Upgrades Pillow to `6.2.2`. Cannot go any higher right now because Wagtail requires `<7.0.0`.
Use image specific functionality, nothing should break.
> Pillow upgrade - #132

- courses/utils.py
[Ticket](https://trello.com/c/9b1Mu17D/126-bug-no-program-enrollment-created-when-user-passed-all-courses-in-a-program)
Modifies `generate_program_certificate` to ensure that a `ProgramEnrollment` exists if a `ProgramCertificate` already exists.
This edge case happens if a `ProgramCertificate` has already been created for a user manually before they have passed all courses in a program. In that scenario once the user passes all the courses and the certificates are being generated, the method ejects early without looking at `ProgramEnrollment` being present. Given the way certificate links are displayed on the dashboard, an enrollment is necessary for the link to be returned from the API. The change in this PR takes care of the potential bug.
Create a program with course A and course B. …
> Program certificate fix for missing enrollment - #126

- ecommerce/admin.py
No ticket
Fixes the `Receipt` admin class to work with receipt objects that have null orders
Ensure that you have some receipt record with a null order, then visit the receipt admin page. It should load
> Fixed Receipt admin class

- courses/models.py
- voucher/utils.py
https://trello.com/c/2JJKQIqu/129-bug-dont-display-courses-that-have-ended-in-boeing-voucher-upload
Don't display courses that have ended in Boeing voucher upload
Just try to upload `voucher/.test` on `/boeing/upload` page
(Optional)
(Optional)
**Before**
**After**
**No Course Avaialble**
**One Course with `end_date = None`**
(Optional)
> Don't display courses that have ended in Boeing voucher upload

- ecommerce/admin.py
https://trello.com/c/2ndIBWMy/123-application-error-attempting-to-access-admin-ecommerce-dataconsentagreement-2-in-production
Removed the users from the page
Just visit the dataconsentagreement page on admin like http://xpro.odl.local:8053/admin/ecommerce/dataconsentagreement/
**Before**
**After**
> remove users from the dataconsentagreement admin page

- ecommerce/views.py
- ecommerce/views_test.py
- static/js/lib/queries/ecommerce.js
[Ticket](https://trello.com/c/2TjIRf2V/137-bulk-purchase-alphabetically-list-courses-in-the-drop-down)
Adds sorting capabilities to the product API and uses that to alphabetically list products in the drop downs on the bulk purchase page.
Visit `/ecommerce/bulk/` and verify the changes are correct.
> Bulk purchase form product alphabetic sorting - #137

- uwsgi.ini
https://trello.com/c/upfutK0A/44-update-all-uwsgi-configs-with-recommendations-from-bloomberg-article
It removes one problematic uWSGI configuration setting from uwsgi.ini.
The uWSGI process would run in one case that we observed (Micromasters), but would generate an exception on startup.
See
https://github.com/mitodl/micromasters/pull/4569#issuecomment-611130601
and the other related comments in that thread.
If you examine the log output from your Docker container, you should not see any exception saying "cannot release un-acquired lock."
> Remove py-call-osafterfork setting from uwsgi.ini

- cms/templates/certificate_page.html
- cms/templates/partials/card_details_top.html
- cms/templates/partials/courseware-carousel-base.html
- cms/templates/partials/faculty-carousel.html
- cms/templates/partials/for-teams.html
- cms/templates/partials/hero.html
- cms/templates/partials/image-carousel.html
- cms/templates/partials/learning-techniques.html
- cms/templates/partials/target-audience.html
- cms/templates/partials/testimonial-carousel.html
- cms/templatetags/image_version_url.py
- cms/templatetags/image_version_url_test.py
Closes #1645 
Adds a new templatetag that produces dynamic image urls in the same way that Wagtail does, but adds a querystring parameter to indicate the version of the file. If an image is replaced by a new upload, that querystring param value will change. This allows us to support image caching via our cloud provider
Visit pages that include all the templates that were updated in this PR (home page, catalog page, catalog detail pages). Make sure the images are all still visible. It would be best to use a detail page that has data for all of the affected sections (learning techniques, who should enroll, learners, faculty, etc.)
This will help to mitigate the periodic 502/503 errors we've been seeing in prod, but it will not solve what we believe is the core issue: during certain times of …
> Added versioned image URL template tag to enable CMS image caching

- config/nginx.conf.erb
None
Fixes fastly cache behavior so `static/hash.txt` is not cached. This will fix Doof's behavior so that he looks up the right hash and gets the right version number.
Go to https://xpro-ci-pr-1658.herokuapp.com/static/hash.txt on the PR build. Open up the network tab and verify that you are receiving a header "Cache-Control: private". If you go to https://xpro-ci.odl.mit.edu/static/hash.txt you should see something like "Cache-Control: max-age=..." instead.
> Move static/hash.txt rule before the generic static rule

- cms/models.py
- cms/views_test.py
fixes #1647  , https://trello.com/c/JscVy4nk/142-change-url-routing-to-allow-for-program-run-ids
fixes #1647  
Just visit the following page
http://xpro.odl.local:8053/programs/<Program Run id>/
e.g.
http://xpro.odl.local:8053/programs/program-v1:xPRO+DgtlLearn+R1/
**Now**
**Before**
> Change URL routing to allow for program run ids

- ecommerce/views.py
- ecommerce/views_test.py
[Trello Ticket](https://trello.com/c/sFpsFNeq/146-fix-sorting-attribute-on-bulk-purchase-form)
Fixes the sorting on Product API to sort on `(parent.title, title)` when flat results are requested, and sort on `title` when nested results are requested.
Go to `/ecommerce/bulk/` and verify both programs and courses are properly sorted in the dropdowns.
> Fix product title/nested sorting on Product API - #146

- ecommerce/api.py
- ecommerce/api_test.py
Closes #1772 
Adds `distinct()` to the global coupon version subquery
See https://mitodl.slack.com/archives/GG8B4C3JP/p1589301132281200
> Filter out old coupon versions

- compliance/api_test.py
- scripts/test/js_test.sh
No ticket. Fixes build failures
Changes `mocker` usage in tests to stop using context processors (`with mocker...:`)
> Changed pytest mocker usages to stop using context processors

- test_requirements.txt
fix build error because of isort
```
Linting files
..INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_pylint.py", line 238, in pytest_collection_finish
INTERNALERROR>     result = lint.Run(args_list, reporter=reporter, exit=False)
INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'exit'
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", …
```
> pin isort to fix the build error

- cms/templates/certificate_page.html
- mitxpro/templates/base.html
- mitxpro/templatetags/startswith.py
#1762 
#fixes #1762, remove the header from the certificate page
Just visit the certificate page
**Before**
**Now**
> remove sharing header from the certificate page

- static/js/components/forms/B2BPurchaseForm.js
- static/js/containers/pages/b2b/B2BPurchasePage.js
> Update the purchase link to support URL parameters and save data properly. 

- b2b_ecommerce/models.py
- hubspot/api.py
- hubspot/api_test.py
N/A
Adds a prefix to `B2BOrder` integratorObjectId's sent to Hubspot to ensure they do not overlap with `Order` integratorObjectId's.
- Set `HUBSPOT_API_KEY` to the same value as CI in your .env
- Set `HUBSPOT_ID_PREFIX` to something unique like `xpro-2020-07-20a`
- On master, create an `Order` and a `B2BOrder` with the same id if you don't have them already.
- Run `manage.py sync_hubspot --deals`, then `manage.py sync_hubspot --b2bdeals`
- Log in to hubspot and search deals for `XPRO-B2BORDER-<id>`.  Check out the earliest history.  You should see `XPRO-ORDER-<id>` as the first property set, indicating the `Order` info was overwritten with the `B2BOrder` info.
- Switch to this branch and restart docker instances.
- Run `manage.py sync_hubspot --deals`, then `manage.py sync_hubspot …
> Make sure B2BOrders have unique integration ids

- courses/api.py
- courses/api_test.py
- courses/management/commands/create_enrollment.py
- courses/management/commands/defer_enrollment.py
- courses/management/commands/refund_enrollment.py
- courses/management/commands/transfer_enrollment.py
- courses/management/utils.py
- courses/management/utils_test.py
- ecommerce/api.py
fixes #1012
Create / Defer / Transfer / Refund enrollment commands rollback xPRO enrollments on edX failure or don't rollback with `keep_failed_enrollments ` flag.
Run all the enrollment management commands (`create, deffer, refund and transfer`) with `-k / --keep-failed-enrollments ` for admin which will enroll xPRO even on edX enrollment failures and vice versa.
**Create Enrollment (Course Run)**
**Defer Enrollment (Course Run)**
**Transfer Enrollment (Course Run)**
**Transfer Enrollment (Program Run)**
**Refund Enrollment (Course Run)**
**Refund Enrollment (Program Run)**
> make create, defer, transfer and refund enrollment commands atomic with the edX enrollments

- b2b_ecommerce/api.py
- hubspot/api.py
- hubspot/api_test.py
- hubspot/serializers.py
- hubspot/serializers_test.py
Fixes #1835 
Uses correct integration id for b2b product syncing
- Assign `HUBSPOT_API_KEY` in your .env file
- Create a new B2B order if you don't have one, otherwise run `manage.py sync_hubspot`
- Search for your B2B deal(s) on hubspot, a product should be associated with them.
> Fix hubspot b2b product sync id

- sheets/coupon_assign_api.py
No ticket. Related to these sentry errors: [1](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1815360075/?project=1413655), [2](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1815360105/?project=1413655 )
Fixes a case sensitivity bug that happens when a coupon assignment sheet is being processed and some existing product coupon assignments have non-lowercase emails
N/A
> Fixed case-sensitivity bug with coupon assignment sheets

- static/js/components/forms/B2BPurchaseForm.js
- static/js/components/forms/B2BPurchaseForm_test.js
- static/js/containers/pages/b2b/B2BPurchasePage.js
fixes #1831 
B2B/Bulk: Automatically Apply Coupon Codes Passed in URL
Just pass the coupon in the link 
[http://xpro.odl.local:8053/ecommerce/bulk/?contract_number=abcd&code=hii&product_id=1&seats=3](http://xpro.odl.local:8053/ecommerce/bulk/?contract_number=abcd&code=hii&product_id=1&seats=3)
> B2B/Bulk: Automatically Apply Coupon Codes Passed in URL

- static/js/components/input/ProductSelector.js
- static/js/lib/queries/ecommerce.js
Fixes #1849 
Fixes #1850 
Fixes inconsistent behavior relating to the course/program dates selector on bulk purchases page.
Visit `/ecommerce/bulk/` and play around with the controls. Everything should work as expected. Now visit `/ecommerce/bulk/?contract_number=abcd&code=hi&product_id=1&seats=3` and make sure the controls work as expected, the loading spinner does not stay on screen after data has been loaded and the dates dropdown should not be hidden when it should be visible.
> #1850 inconsistent behavior on bulk purchase page

- static/js/components/forms/B2BPurchaseForm.js
Fixes #1844 
Modifies `B2BPurchaseForm` to:
- only apply a coupon if the `product.id` and `couponStatus.product_id` match
- reset `couponStatus` and `values.coupon` if the coupon isn't for selected product
Go to `/ecommerce/bulk/?contract_number=abcd&code=ANLG&product_id=17&seats=3` (change values as needed) and verify the coupon code is applied, the discount shows up. Change the program/course selected and verify the coupon code field is reset and the discount is removed.
> Fixed bug b2b coupon applied to all products - #1844

- static/js/components/ScaledRecaptcha.js
Closes #1859
Switches the source domain of the recaptcha script from google.com to recaptcha.net
- Set `RECAPTCHA_` variables in your .env
- Go to `/create-account` and verify that the main recaptcha script comes from `recaptcha.net` instead of `google.com`
Looks like some associated scripts/images still come from `gstatic.com`, hopefully no one is blocking that domain.
> Change recaptcha domain

- hubspot/serializers.py
- hubspot/serializers_test.py
Closes #1860 
When syncing a B2B contact, check to see if there is an existing user with the same email.  If so, the hubspot id is generated from the user id.  Otherwise, it is generated from the B2B order email.
- Set `HUBSPOT_API_KEY` in your .env file
- Create 2 B2B orders, one with an email of an existing user, the other with a new email not associated with any users.
- Wait a few minutes then login to Hubspot and find these `XPRO-B2BORDER-*` deals.  Check that both have a contact with the expected email address.
> Sync B2B contact with existing user if it exists

- courseware/api.py
- courseware/api_test.py
Fixes #1873 for retired users
Adjusts the enrollment retry code to not perform retries for inactive users
Unit tests should be enough here, the existing functionality is known to work and we're just adding an additional query filter.
> Only retry enrollments for active users

- static/scss/notification.scss
fixes: #1879 
Fix the bug as described in the issue.
Add a notification via CMS along with some links in it and link should appear with same color of text, white and underlined.
> Links in site notification with same color

- static/scss/certificates/certificate.scss
fixes #1808 
certificate layout: line up signatures and their underline
Just add a certificate page and 5 signatories on it.
**Before**
**Now**
> certificate layout: line up signatures and their underlines

- package.json
- yarn.lock
Fixes #1863 
Upgrades jQuery to version `3.5.1` from `3.5.0`, the latter has compatibility issues with bootstrap `4.4.1` that we are using.
Force dependency install from `watch` service. Go to catalog page and click on the "+ Detail" link. The link should behave as expected (opening/closing the accordion) and there should be no errors in the console.
> Upgrade jQuery to 3.5.1 - #1863

- b2b_ecommerce/views.py
- b2b_ecommerce/views_test.py
- mitxpro/utils.py
fixes #1876
B2B/Bulk: Add Instructions to downloadable enrollment sheet and remove enrollment code column 
Just create b2b order and download the enrollment codes
> B2B/Bulk: Add Instructions to downloadable enrollment sheet and remove enrollment code column

- cms/wagtail_hooks.py
Closes [#17](https://github.mit.edu/xpro/xpro-issues/issues/171)
Modifies wagtail admin to display all page lists sorted alphabetically.
Browse the CMS and make sure all page lists are sorted alphabetically.
> Sorting pages in CMS admin by title - #171

- static/js/components/input/ProductSelector.js
- static/js/components/input/ProductSelector_test.js
- static/js/factories/ecommerce.js
#1866 
Do not show user past dates in selection.
- Steps to Reproduce
Got to B2B/Bulk CC checkout page ecommerce/bulk/
Select Course. Select Architecture and Systems Engineering: Models and Methods to Manage Complex Systems
Note: Past dates are shown. It should only show dates for future runs.
- Expected Behavior
Only show dates for future runs
> asadiqbal08/Do not show user past dates option for course runs.

- b2b_ecommerce/api.py
- b2b_ecommerce/api_test.py
closes https://github.com/mitodl/mitxpro/issues/1895
The pr updates the payment name for coupons created for B2B orders to include the conract number and b2b coupon code
Create a b2b coupon through the admin
Go to http://localhost:8053/ecommerce/bulk/?contract_number=test_contract, fill out the form with the coupon code and place an order
From the shell run
```
from b2b_ecommerce.models import *
from b2b_ecommerce.api import *
complete_b2b_order(B2BOrder.objects.last())
```
The generated coupons should have coupon payment name `test_contract <b2b coupon code>`
> change b2b order coupon name

- courses/management/commands/sync_grades_and_certificates.py
- courses/utils_test.py
none
none
makes it clear that the `sync_grades_and_certificates` can be used to block the creation of certificates, instead of using the phrase "blacklist" 
run `python manage.py sync_grades_and_certificates --help`
> clarify management command

- b2b_ecommerce/api.py
- b2b_ecommerce/api_test.py
fixes #1922 
B2B/Bulk: Update coupon payment name to fix name collisions
Just create a reusable coupon and try to create bulk enrollment with that coupon. It should create the coupon payment with a different name as the top two records in the screenshot.
> B2B/Bulk: Update coupon payment name to fix name collisions

- sheets/coupon_request_api.py
- sheets/coupon_request_api_test.py
Fixes #1925 
Makes it so that enrollment code assignment sheets have a local DB record as soon as the sheet is created
N/A. Code review only
In the past, we've been able to rely on a file watch (webhook) being set up as soon as an assignment sheet is created. When we got the first request after the assignment sheet was edited, our code would create a new `BulkCouponAssignment` record for that sheet. Since the file watch API is more volatile lately, we've had a few of those initial file watch requests fail, leaving those assignment sheets in an un-processable state
> Fixed bug where coupon assignment sheets didn't have local DB record

- mitxpro/templates/base.html
- mitxpro/templates/footer.html
- static/scss/icomoon.scss
fixes #1920 
Makes resource usage changes to the product page to partially fix issues described in #1908
Use Lighthouse or Google Pagespeed to test before/after performance score. There should be an increase in the overall score and speed for the page.
Devops needs to increase the cache expiry limit on media resources for xPRO (probably on the CDN level if it's being controlled from there or the server if that's the original source of the cache header).
> product page performance tweaks

- ecommerce/views.py
- ecommerce/views_test.py
Closes #1928 
This PR adds the Course name alphabetical ordering on courses list populated on the B2B bulk order page. [Link](https://xpro.mit.edu/ecommerce/bulk/)
- Go to [B2b Bulk Order](https://xpro.mit.edu/ecommerce/bulk/) page and select course dropdown, Verify the courses list ordering.
- Use any Http client and hit `<XPRO_HOST>/api/products/` and verify the response
**Old behavior**
**New behavior**
> Added courses list ordering for B2B Bulk order page

- mail/templates/b2b_receipt/body.html
- mitxpro/templates/footer.html
- static/js/containers/pages/ReceiptPage.js
Fixes #1945 
This PR changes the copyright year to 2020, in an attempt it makes the year calculation dynamic depending upon current date.
This can be tested on multiple pages e.g. :
1. Go to the home page and have a look at the footer part.
2. Go to the receipt's detail page and have a look at the receipt bottom & page footer
3. Check overall in the app where ever there is a copyright text and its not updated to 2020 as of now.
Footer/Coomon throughout the app:
Receipt detail page:
> Fixed copyright year text and made it dynamic

- b2b_ecommerce/api.py
- b2b_ecommerce/api_test.py
fixes: [B2B/Bulk Credit Card Purchases is not descriptive in Combined Revenue Recognition report](https://github.com/mitodl/mitxpro/issues/1946)
It prioritizes `contract_number` over `reference_number` (i.e: xpro-bulk-production-##) when assigning to `ecommerce_couponpaymentversion.payment_transaction` 
* Create a bulk order from `/ecommerce/bulk` using a b2bcoupon or payment via cybersource.
* Through admin panel got to `/admin/ecommerce/couponpaymentversion` and check `payment_transaction` in the coupon, it should be B2Border.contract_number or B2Border.reference_number depending upon the fact that if contract_number was given while placing the order or not. 
Note: Contract_number is not shown in `/ecommerce/bulk` in the default interface so we need to add query_param to it like …
> prioritize contract_number to be used as payment_transaction

- sheets/api.py
- sheets/management/commands/setup_file_watch.py
- sheets/tasks.py
Fixes an issue with #1952
- Properly defines the file watch renewal task (😬 )
- Fixes exception handling so file watch renewal errors are properly saved to the database
No manual testing needed. Test should pass and we should stop seeing [this sentry error](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1990515434/?environment=rc&project=1413655&query=is%3Aunresolved)
> Added task decorator to file watch renewal task and fixed exception handling

- cms/templates/partials/enroll_button.html
Fixes https://github.com/mitodl/mitxpro/issues/1986
Changes button text for external course pages from "Apply Now" to "Learn More".
Open any external course page, you will observe the "Learn More" button instead of the "Apply Now".
> change button text from 'apply now' to 'learn more' for external course pages

- courses/api.py
- courses/api_test.py
- sheets/admin.py
Fixes #1962 
Fixes a bug where we weren't properly validating attempts to defer a course run enrollment to a course run that was outside of its enrollment period (e.g.: the `enrollment_end` date is in the past)
Probably doesn't need manual testing since the test case tests the validation. If you want, you can set up a course enrollment, then run the `defer_enrollment` management command to try to defer the enrollment to another course run with an `enrollment_start` in the future or `enrollment_end` in the past
The bug issue describes buggy behavior in our spreadsheets, but the bug exists in an API function that is used in a few different places, including the management command I mentioned above
> Added validation for enrollment deferrals to an unenrollable course run

- conftest.py
No ticket
Adds a pytest flag that allows us to run Python tests only without pylint and coverage, and with warnings suppressed
Run bash in a web container, then run `pytest --simple`. You should see the test suite run without pylint, without a coverage report, and with no warnings output
This flag will be particularly helpful while hacking on tests in a local branch. Most of the time you just need the tests to run and to have the console output limited to which tests passed and failed.
> Added flag to run python tests only without pylint/cov/warnings

- .github/workflows/ci.yml
- .zap/rules.tsv
Add OWASP Zed Attack Proxy (ZAP) security scanning via Github Actions.
See https://www.zaproxy.org/
There are different types of scans for commits to `master`, `release`, and `release-candidate` branches; the latter two get a "full" scan.
The repo is checked out in order to get access to the `.zap/rules.tsv` file, which governs which tests are run or ignored. We're ignoring the "Suspicious comments" and "Unix timestamps" scans because I've only seen false positives coming from them; and they're labeled "informational," anyway.
> Add OWASP ZAP scan

- .github/workflows/ci.yml
- .github/workflows/scanning.yml
* Remove ZAP Github action's release tag so that we can always pull down the very latest release
* Rename the ZAP-related workflow, because it's not really CI-related.
> Get latest release of ZAP actions, rename ZAP workflow

- .github/workflows/scanning.yml
In the "scanning.yml" workflow, add '@ref' notation to the 'uses'
properties. This is required by Github and we are getting errors without
them. I'm adding '@master' to the zaproxy actions in order to get the
latest vulnerability definitions without having to update this file
whenever they do a new release.
This is the same thing that I just did in [this Micromasters PR](https://github.com/mitodl/micromasters/pull/4696).
> Add git ref to Github action 'uses' specifier

- static/scss/detail/subnav.scss
fixes #1976
remove unused padding from the enrollment button
**Before**
**Now**
> enroll button design fixes

- cms/templates/product_page.html
- mitxpro/urls.py
Partially addresses #2019 
Adds a Cache-Control header to wagtail image renditions so they are cached for a year on users' browsers. This should help alleviate some of the issues we've had with uncached Wagtail images.
Check various images across the site in your browser's Network tab and observe the Cache-Control header
502s under high traffic will still be possible with this fix, but this is a good idea to implement whether or not it helps alleviate those failures. These wagtail images have version tags built into their URLs, so they can be cached indefinitely. These images shouldn't need to be pulled down from a Fastly cache if they have been loaded once
> Added far-future cache control header to wagtail images

- courseware/api.py
- courseware/api_test.py
- courseware/constants.py
- requirements.in
- requirements.txt
Fixes #1964 
Removes the API implementation for updating the user's name from xPRO and uses the API from `edx-api-client`.
**Note:** This PR will need an update to use the latest `edx-api-client` once we merge [Update User name API PR](https://github.com/mitodl/edx-api-client/pull/70).
**UPDATE ON NOTE:** [edx-api-client 0.10.0](https://pypi.org/project/edx-api-client/0.10.0/) contains this change now.
- Login to your xPRO
- Go to profile/update
- Change the full name
- Open edX instance (e.g open any course from xPRO and you will be redirected to edX) and verify the changed name on edX profile
This functionality was implemented some time ago and at that point we decided to enhance it and use API from `edx-api-client` and remove native API Implementation. …
> Use user name update api from edx-api-client

- cms/template_tags_test.py
- cms/templates/product_page.html
- cms/templatetags/image_version_url.py
Fixes #2025
Gracefully handles cases where course pages have no thumbnail image configured in the CMS, and improves the templatetag we use for Wagtail images so that it can generate full URLs instead of just relative ones
Configure a course page in the CMS such that it has a thumbnail image, then load the product page for it (e.g.: `http://xpro.odl.local:8053/courses/course-v1:SEED+SysEngBx3/`). It should load properly, and the `<meta og:image>` tag should have the correct URL as its value. Try again after setting that thumbnail image to nothing. The page should load and the `<meta>` tag should disappear
_Without a thumbnail image..._
> Fixed 404/500 error with missing course thumbnails

- ecommerce/admin.py
- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/serializers.py
- static/js/components/forms/CouponForm.js
fixes https://github.com/mitodl/mitxpro/issues/1775
adding max_redemption_per_user feature for promo coupons
* Go to `/ecommerce/admin/coupons/` and create a Promo coupon with `max_redemptions_per_user` greater then 1.
* Make sure that `max_redemptions` is greater than or equal to `max_redemptions_per_user`.
* Now use that coupon code multiple times with the same user on different products.
> adding max_redemption_per_user feature for promo coupons

- cms/wagtail_hooks.py
Fixes #2047 
It adds registers admin API for wagtail in the Router
Go to `/cms` and check that `pages` list populates correctly and doesn't give `Server Error`
xPRO CMS
A wagtail upgrade was recently done, and looks like we might have missed registering the Newly added ViewSet in WagtailAPIRouter.
> Added Viewset routing for wagtail hook

- static/js/components/forms/ProfileFormFields.js
- static/js/components/forms/RegisterDetailsForm_test.js
- users/serializers.py
- users/serializers_test.py
Fixes #2037 
It adds validation on the first and last name of the user in the registration form.
**Below details are taken from Bootcamp PR https://github.com/mitodl/bootcamp-ecommerce/pull/1096 and & confirmed in xPRO as well.**
1. Acceptable Special characters were ```~!@&)(+:'.?/,`-```
2. Non Acceptable special characters were: ```/^$#*=[\]`%_;<>{}"|```
**Cases**
1. Compliance API doesn't accept any character from the `Non-Acceptable` character set mentioned above.
2.  Compliance API accepts characters from the `Acceptable character set` mentioned above, But these characters cannot be at the start of the name
The `regex` used in the PR is created based on the above scenarios.
Follow the steps in the aforementioned issue and see check that field validation is working, based on the above …
> Added fields validation on user profile first & last name

- sheets/api.py
Closes #2054 
Removes pylint disable-all statements which seemed to be affecting the entire file.
Add an unused import to `sheets/api.py` then run `pylint sheets/api.py`, it should notify you of an unused-import error.
> Enable pylint in sheets/api.py

- app.json
- mitxpro/settings.py
- sheets/utils.py
Closes #2023 
Adds settings that allow for an optional admin-only auth code column in a refund spreadsheet
Code review only. This will be tested in RC
> Added optional auth code column to refund spreadsheet

- cms/api.py
- cms/models.py
- cms/templates/catalog_page.html
- cms/templates/partials/card_details_top.html
- cms/templates/partials/metadata-tiles.html
🛑  **NOTE: This PR should be tested/merged after #2056 is merged**
Related to #2044 (Should close the issue manually)
It adds design changes to the catalog page to support external programs
Create External Program(s) through CMS & Visit Catalog Page and verify:
- External programs fall under the `PROGRAMS` tab on the Catalog page
- External programs cards detail `MULTILINE COURSE ONLINE`
- External program card details show `VIEW PROGRAM`
- External Program cards show `Price`, `number of courses`, `duration` & `Next start date`
CMS - External Program - Catalog
> Catalog page changes to support external programs

- cms/templates/partials/courseware-carousel-base.html
None
It fixes the course redirection when clicked from a course carousel inside a Product Detail page. Before it would use full_url that would take the user to the base URL which was either `localhost` or `BASE:Port` hence not loading the page.
Open a program with a `Course Carousel`, Click on any card's(Area except `Card/course title` & `View Details`), and the course detail page should load without any errors.
Product page for a Program with carousel.
> Course card url redirection fix to use url instead of full_url

- courses/api.py
- courses/api_test.py
Fixes #2042
Adds exception handling to order completion so that local enrollment records will still be created if a request to edX results in an unexpected error (e.g.: the service is down or there's a bug on the server)
1. Run xPro without edX running
1. Complete checkout for some course run
Checkout You should see an exception logged, and a `CourseRunEnrollment` record should be created for the given user and run. Before this fix, this would have resulted in an unhandled exception and no local enrollment record would have been created
> Fixed error handling to save enrollments on edX HTTP errors

- mitxpro/templates/base.html
#2065 
- Combines google font imports into a single `<link>`
- Removes a font import for a font that we didn't appear to be using
- Sets non-essential font/icon imports to load asynchronously
Load the homepage, ensure that everything looks correct. Also try slowing down the connection to see if this PR introduces any UI weirdness while the page is loading
If the async loading is applied to the google font API `<link>` tag, there is a noticeable "blink" when the font on the home page changes over as the page is loading. That's why I decided not to use that async technique for that link tag
> Combined and reduced font imports, async loading non-essential fonts

- hubspot/api.py
- hubspot/conftest.py
- hubspot/tasks.py
- hubspot/tasks_test.py
Closes https://github.com/mitodl/mitxpro/issues/2074
Ignores B2B line sync errors in hubspot
To test manually:
Make sure the following .env values are populated:
HUBSPOT_API_KEY=<obtain from hubspot website or me>
HUBSPOT_ID_PREFIX=<something like 'xpro-localdev-2021'>
Manually create a new B2BOrder in django admin (to avoid triggering a sync task).  Fill out the bare minimum (product version, email, num seats, per item price, total price).  Note the id of the order.
In a shell, run:
```
from hubspot.tasks import *
sync_b2b_product_with_hubspot(<order_id>)`
```
After a minute or so, run:
```
for error in get_sync_errors():
if ("B2B-<order_id>" in error.get("integratorObjectId", "")):
print(error)
```
You should get a line printed that looks something like this:
``` …
```
> Ignore B2B line sync errors in hubspot

- cms/templates/product_page.html
- mitxpro/templates/base.html
- mitxpro/views_test.py
- static/js/entry/django.js
- static/js/entry/third-party.js
- static/js/product_detail.js
- webpack.config.shared.js
#2065 
- Merges `django.js` & `third-party.js` files since the usage of both files is only in one place `base.html`.
- Moves inline scripts from product_page.html to js files which in turn is now served through webpack.
- Make sure that `django.js` & `third-party.js` related scripts/functionality works fine & is now converted into one js file request which is `base.js`.
- Make sure that moved script changes in `product_page.html` works fine in this PR.
(Optional)
We had two had two separate files before for loading third-party plugins and out custom plugins. But both of these had only 
one place of usage e.g. in `base.html`
> Merge 3rd-party & django js files, Move HTML scripts to js files

- cms/models.py
- cms/templates/partials/faculty-carousel.html
- cms/templates/partials/learning-techniques.html
- cms/templates/partials/testimonial-carousel.html
- mitxpro/templates/footer.html
- static/js/components/TopAppBar.js
- static/js/components/UserMenu.js
- static/js/containers/pages/ReceiptPage.js
- static/scss/footer.scss
- static/scss/top-app-bar.scss
Related to #2065
Attempts to optimize the Catalog & Product Pages through suggestions provided by Lighthouse
- Sets fixed styling(height/width) for the elements where possible to avoid layout shifts.
- Adds lazy loading to the images where possible.
- Defers a Zendesk script
Open any of the Catalog/Product and check the statistics on `LightHouse`, Make sure that the page loads in a better amount of time than before. Make sure that we caught maximum possible suggestions through Lighthouse regarding images layout shifts, setting height/width of images.
> Reduce Layout shifts, Inline Styling - Set fixed height/width where possible

- .eslintrc
- static/js/lib/util.js
https://github.com/mitodl/mitxpro/issues/2065
It insists on importing `lodash methods` instead of the `whole lodash` plugin to reduce package size.
It reduces `header.js` size from `954 KB`  to `888 KB` and `root.js` size from `1.71 MB` to `1.64 MB` on my local machine.
> using module level lodash imports

- users/admin.py
N/A
Enables username update in Django admin with a conspicuous warning about requiring an edX username update immediately afterward
Change the username for some user via Django admin, then change it back. No errors = good
We've had a lot of username change requests lately and this is one step toward making it easier
**BEFORE**
**AFTER**
> Allowed username update in admin with warning

- authentication/urls.py
- authentication/views.py
https://github.com/mitodl/mitxpro/issues/1931
In `xpro's logout flow`, after the user is logged out from `xpro` it redirects User to its `edx` counterpart's logout URL using `LOGOUT_REDIRECT_URL` environment variable. This PR enhances the functionality and adds a `redirect_url` to `edx's logout URL` which helps User to get back to `xpro`.
Use the following flow to see the error or can watch the video https://www.dropbox.com/s/b7c1eimwj4yowt3/JuniperLoginStuckInEdx.mov?dl=0:
* Sign in to xpro devstack
* Sign out
* Sign right back in
* Sign out
After this PR, the bug shouldn't appear again.
This PR is dependent on https://github.com/mitodl/edx-platform/pull/238 as we have to add `xpro's URL` in `LOGIN_REDIRECT_WHITELIST`
> adding logout redirection

- cms/templates/product_page.html
- static/js/product_detail.js
https://github.com/mitodl/mitxpro/issues/2110
Makes sure that content of `product_detail.js` renders only on the Product Page. And also moves zendesk related code to django templates as `page.product.title` can only be found there.
I couldn't find this issue in chrome and safari browser consoles, but I believe it can be generated on some older versions of browsers.
**Update**: I was able to reproduce this issue on IE 11, and pretty hopeful about the solution provided by this PR.
> Fix product_page JS rendering issue

- courseware/api.py
https://github.com/mitodl/mitxpro/issues/2115
edX's grades APIs send user-email only if the course's enrollment mode is `masters` (https://github.com/edx/edx-platform/commit/68ec2e184d1b4ed7824954e34c97bef39647ebe2)
So this PR replaces the usage of user-email to user's username for our grade processing.
We can go to xPRO's shell and run the `sync_grades_and_certificates` command for `non-masters` enrollment. If the issue is fixed then you won't see any error in syncing.
> fix: filtering user on the basis of username because of non-masters courses

- authentication/serializers.py
- authentication/utils.py
- authentication/views_test.py
- requirements.in
- requirements.txt
- static/js/containers/pages/register/RegisterConfirmPage.js
- static/js/containers/pages/register/RegisterConfirmPage_test.js
- static/js/lib/auth.js
#1885 
It add proper messages for more user readability on validation fail. Adds two more states to support the error messages:
1. If the user already has an account/partial account created and he clicks the confirmation link again he will be shown a message to login again. (`You already have an xPRO account. Please [click here] to sign in.`)
2. If a user doesn't have an account and he clicks on the confirmation link again he shown invalid/expired link message. (`This invitation is invalid or has expired. Please [click here] to register again.`)
Testing instruction are added in the associated ticket.
Account Registration
**Screenshot when User has partial/full profile created with us -- 'Click Here' Link will take him to login page**
**Screenshot when User doesn't have a profile created …
> Show appropriate messages on Registration Confirmation link failure

- compliance/admin.py
#2130 
Adds country name in Admin display of `ExportsInquiryLogAdmin`.
Have a look at the `ExportsInquiryLogAdmin` page and verify that you can see the user's country for each record, Additionally, you should also be able to filter data on the basis of the country.
Django admin
The associated ticket has the details as to why we need to add this value in the admin.
> Added country name in compliance admin

- cms/factories.py
- cms/views_test.py
- cms/wagtail_hooks.py
#2134 
- Fixes the wagtail hook for sorting items on CMS
Add different cms pages and then open the pages tab from the CMS side menu, the list of items in this should be alphabetically sorted.
- CMS
We did some upgrades to the wagtail recently and during that process, our hooks for wagtail broke. Which indeed broke the sorting of the pages on Wagtail Admin's side menu.
**(HomePage)**
**(Courses Sub Pages)**
> Fixed wagtail admin pages list ordering

- cms/models.py
- cms/models_test.py
https://github.com/mitodl/mitxpro/issues/2133
Fixes `Course order in carousel` under Program-page w.r.t `position_in_program` variable present in course model.
Create a `Program` and its `ProgramPage`.
Create `Courses` and their `CoursePage`s under that Program.
Change the order of Courses by changing `position_in_program` through Admin Panel.
Now go to the live version of ProgramPage, you will notice that the course carousel has reordered according to `position_in_program` variable
> fix course order in carousel w.r.t position_in_program

- authentication/pipeline/compliance.py
#2135 
- It changes the compliance validation-related emails to ADMIN_EMAIL instead of EMAIL_SUPPORT.
- Changes both the sender and recipient, The reference to this change can be seen in the conversation on reference ticket https://github.com/mitodl/bootcamp-ecommerce/issues/1161
- Before applying this PR, Try to generate the email for compliance failure
- If you are confused about generating a compliance failure email, You can use this [Cybersource doc](https://developer.cybersource.com/library/documentation/dev_guides/Verification_Svcs_SO_API/Verification_Svcs_SO_API.pdf#page=25&zoom=100,192,100).
- Verify that you are now receiving compliance failure email on ADMIN_EMAIL instead of EMAIL_SUPPORT.
> Send compliance emails to ADMIN_EMAIL instead of EMAIL_SUPPORT

- ecommerce/serializers.py
- static/js/containers/pages/ReceiptPage.js
fixes: #2139
`card_type` and `card_number` are not the part of PayPal checkout.
> HotFix: PayPal Information Rendering

- pytest.ini
- test_requirements.txt
None
`pylint` is now being run separately from pytest so we don't need `pytest-pylint` anymore
> Remove pytest-pylint

- app.json
- mitxpro/settings.py
- mitxpro/utils.py
- mitxpro/utils_test.py
- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/js/flow/declarations.js
https://github.com/mitodl/mitxpro/issues/2181
Adds a configuration-based list of courses and programs run Ids that would support digital credentials if the feature is turned on.
- Create course/program certificate(s)
- Enable `FEATURE_DIGITAL_CREDENTIALS` feature flag
- Setup newly added configuration key `DIGITAL_CREDENTIALS_SUPPORTED_RUNS`, the value of this key should contain a comma-separated list of run Ids that we want to support digital credentials.
- Visit the dashboard and notice that the `Digital Credential` link is only available for courses/programs for whom we have added run Ids in `DIGITAL_CREDENTIALS_SUPPORTED_RUNS`.
We recently added changes for Digital Credentials on the dashboard, You can visit https://github.com/mitodl/mitxpro/pull/2168 and …
> Digital credentials for configuration based specified runs

- static/js/containers/pages/DashboardPage.js
fixes: #2162
Showing receipt Link in case of individual courses run purchases of a program over the dashboard.
Three Scenario: 
1-  The case where the learner purchases the entire program. (Receipt link be appeared on program and for individual courses)
2- The case where the learner hasn't enrolled in all courses in the program yet. (Receipt Link should appear on individual courses over the dashboard)
3- The case where the learner purchased the courses individually and was enrolled in the program when they were awarded the certificates. ((Receipt Link should appear on individual courses over the dashboard for all course runs order)
> Showing receipt Link in case of individual courses run purchases of a program

- courses/README.md
N/A
Removed reference to updating the professional track when creating course runs. This is no longer necessary as edX now defaults to `no-id-professional`
View the readme
> Removed reference to Professional Track in course readme

- package.json
- yarn.lock
https://github.com/mitodl/mitxpro/issues/2211
Removes `handlebars`.
`handlebars` was previously used by `istanbul-reports@^2.2.4` but with the updated version `istanbul-reports@^3.0.2` the dependency is no more required.
Check that the templates are working fine, but majorly we rely on coverage for this one.
> Remove unused handlebars dependency

- cms/embeds.py
- mitxpro/templates/base.html
https://github.com/mitodl/mitxpro/issues/2154
- Adds a script to defer youtube video iframes to run scripts until the `DOMContentLoaded` event.
- Add a youtube video URL in a Course or Program page in CMS and visit that page in the app. Now visit any of the program or course pages and verify that the youtube script was loaded after that page load.
- Add a `Text-Video` section in CMS in HomePage. Visit the home page and verify the script deferring as I the above point.
- In the above process it would be good to notice google's `LightHouse` stats and some improvement in the performance result.
We tried to improve the performance of xPRO and for that, we opted and discussed many solutions that can be found on https://github.com/mitodl/mitxpro/issues/2065. In this PR, we added one more step …
> Performance Optimization: Defer youtube iframe's script loading

- authentication/exceptions.py
- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- authentication/serializers.py
- authentication/utils.py
- mitxpro/settings.py
- static/js/containers/pages/register/RegisterEmailPage.js
- static/js/containers/pages/register/RegisterEmailPage_test.js
fixes: #2226 
As an xPRO administrator, I want the ability to add a user to a blocklist that will prevent that user from registering. The user will need to speak to customer service to complete their registration.
- Blocked a user email first running the `retire_users` management command
- `./manage.py retire_users --user=foo@email.com --block`
- Visit the xPro create account page for registration process.
- Enter the blocked email in the text field.
- It show a message to user `Please contact customer support to complete your registration.`
> Blocklist: Check for blocked emails when registering users

- .github/workflows/ci.yml
N/A
Updates github action ci.yml to allow codecov to fail softly.
Github actions should succeed, especially if the codecov upload fails.
> fix: don't fail CI on coverage

- package.json
- yarn.lock
#2236 
- Bumps `react-markdown` to minimum possible `5.0.3` to fix the `trim` transitive dependency through `remark-parse`
**NOTE:** 
Now markdown links don't work if they have a space between the syntax. e.g. something like`[COMPANY] ([CO])` on RC generates a link but not in this `react-markdown` version. In this version you have to remove the space between `[]` and `()` e.g. something like this `[COMPANY]([CO])` will work.
- Mainly testing the usage of `Markdown` e.g. `Global Consent Messages` (The dialog that shows on checkout page)
Starting with a Global Consent would be about it.
> build: bump react-markdown for transitive trim dependency alert

- authentication/utils.py
- users/management/commands/block_users.py
- users/management/commands/unblock_users.py
- users/management/tests/block_users_test.py
fixes: #2261 
@briangrossman  found an issue, tried to run block_users on an email address that wasn't already registered with xPRO and got an error because the email didn't exists (below):
We actually need to account for this use case. There may be a time when we want to add a user to the blocklist before they register for the site. 
- Run the command with user email that is not exist in xPro.
- It should be added in block list.
> asadiqbal08/Update block_users on email address that wasn't already registered.

- b2b_ecommerce/views.py
- b2b_ecommerce/views_test.py
- static/js/components/forms/B2BPurchaseForm.js
#2258 
- Stops order creation is a duplicate reference number is provided
- Adds an error message about the duplicate reference number
Testing steps can be seen on the issue description itself
- B2b bulk orders with reference number `ecommerce/bulk/?contract_number=<contract_number>`
**The error that shows when we try to create an order with a reference number that has already been associated with a _Fulfilled Order_**
> fix: validation for duplicate contract_number in order creation

- package.json
- yarn.lock
https://github.com/mitodl/mitxpro/issues/2269
Upgrades trim-lines to v3.0.1
webpack should be able to compile sass files
> upgrade trim-newlines to v3.0.1

- package.json
- yarn.lock
#2272 
- Migrates from `node-sass` to `sass`
- Removes `node-sass/**/trim-newlines` resolution since it is no more required as we removed `node-sass`.
- Pins `sass` to `1.32.13` to get rid of unnecessary warnings from `bootstrap` which are currently not fixed even in the latest bootstrap 5. This should not affect us and we will update `sass` to 2.0.0 eventually when those warnings are fixed in a bootstrap update.
- Removes unused `babel-plugin-istanbul`.
- Check CI build is passing
- Check that CSS is working fine without error
> migrate from node-sass to sass

- cms/models.py
- cms/models_test.py
- cms/templates/partials/subnav.html
- cms/templates/product_page.html
fixes: #2276 
Add News and Events carousel functionality to product pages
- Go to cms
- Under Product Page create a News and Events Page
- Add the required fields and save
- A new section should appear below testimonial on your Product pages e.g. courses, programs, external courses and external programs.
> asadiqbal08/News and Events carousel to product pages

- b2b_ecommerce/views.py
- b2b_ecommerce/views_test.py
- static/js/containers/pages/b2b/B2BReceiptPage.js
- static/js/factories/ecommerce.js
- static/js/flow/ecommerceTypes.js
#2280 
- Fixes customer name on the order receipt page
- Fetches the customer name based on the existing user associated with the order email
- If there is no associated user in the system with order email. it tries to fetch the user from order receipt details
- If there is no name in the receipt it hides the customer name field.
Associated ticket's expected behavior part can be seen for further details on the priority of fetching the customer name. 
**Note:**
In the case of receipts the name that is fetched is basically the value for the keys `req_bill_to_forename` and `req_bill_to_surname` from receipt data
- Create a B2b bulk order
- Follow the steps mentioned on the ticket
- Bulk order
**No associated email account or receipt**
**No associated email found but we found name in …
> fix: customer name fixed on order receipt page

- package.json
- yarn.lock
https://github.com/mitodl/mitxpro/issues/2286
upgrades deep-extend to 0.6.0 by upgrading webpack-bundle-tracker to 0.4.3
A general test would be enough
> upgrading deep-extend to 0.6.0

- static/scss/detail/news-and-events-carousel.scss
Closes #2302 
This PR updates the news and event carousel styles in the following way
- Updated  the background of the carousel section to be the color: #ebebeb
- Updated background of the carousel cards to be while: #ffffff
This PR can be tested the following way
- Add News and Event carousel and items
- Verify Background color is #ebebeb
- Verify card color is white
(Optional)
> Updated styles for news and event carousel

- package.json
- yarn.lock
- Dependabot Alert
- Created this ticket in response to the Dependabot PR which bumps https://github.com/mitodl/mitxpro/pull/2320
Removed an unused package `validator`.
While looking at the dependabot PR(https://github.com/mitodl/mitxpro/pull/2320), I noticed that the package is not used anywhere. So, instead of the bump, I've created this PR to remove this unused package.
- tests passing
- Reconfirming that we aren't using it anywhere, not even dynamically.
Upon merging this PR i'll be closing https://github.com/mitodl/mitxpro/pull/2320, since it won't be needed anymore.
> chore: remove unused JS dependency (validator)

- ecommerce/views.py
fixes: #2367 
This change try to fix the query breakage with possibility due to Django Upgrade.
- Visiting the `bulk/ecommerce` should not be breakable.
- Query works fine to load the relevant data ( Expired courses/programs should out from the product list).
> Split the queries to evaluate

- .eslintrc
none
what it says on the can
run `yarn lint` locally on `master`, and then on this branch. on master there should be a warning message about configuring the react plugin, on this branch that should go away.
> set react version to get rid of an eslint warning

- mitxpro/urls.py
Fixes #2371 
This fixes a regex in the url routing that broke because django changed the internal implementation of its token generator.
I chose to switch this to django's builtin `slug` parser because it's more robust against future changes like this.
- Trigger a password reset email
- The link in your email should resolve to the reset UI and you should be able to complete the password reset process.
> Fixed password reset url

- ecommerce/views_test.py
fixes: #2378 
Add test to cover expired program runs in product list while visiting `/ecommerce/bulk`
> Added unittest for expired program runs

- cms/templates/certificate_page.html
- static/scss/certificates/certificate.scss
#2417 
(Required)
- Checkout the branch
- Open certificate page
- Open print preview or get the print (`command + p` on Macbook or `ctrl + p` on Windows PC)
- Validate the certificate content is centered vertically and horizontally
> Vertically center the certificate when printing

- cms/templates/certificate_page.html
#2420 
(Required)
- Open any certificate page
- Validate course start and end date on certificate page with and without CEUs
> display start and end date on certificate template

- cms/api.py
#2409 
The certificate page is a child of course this should not be moved from course child to certificate index page child
- Open any course with a Certificate Page available
- Run command in terminal `docker-compose run web ./manage.py configure_wagtail`
- Validate in CMS that the certificate page of the course is not removed from the course and not added to Certificate Index Page
(Optional)
(Optional)
(Optional)
(Optional)
> Certificate page should not be moved to Certificate Index Page child

- ecommerce/admin.py
Fixes https://github.com/mitodl/mitxpro/issues/2411
Fixes search for Data Consent Agreement list in Django admin.
- Visit admin/ecommerce/dataconsentagreement/ in xpro
- Search something in the search field.
- Search will work fine now.
> xPro-2411 Fix search for data consent agreements admin

- package.json
- webpack.config.prod.js
- yarn.lock
None
This PR adds [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to help us understand what's in the bundles generated by the webpack build process.
Right now it is configured only to run for the production webpack build. (It doesn't affect the production bundles, though, just generates a sibling report.html file.) 
1. Run
```sh
docker compose run --rm --env NODE_ENV=production yarn run postinstall
```
The build should succeed.
2. In yoour browser, open `/static/bundles/report.html`. It should show something like the diagram below.
We recently added this to mitxonline: https://github.com/mitodl/mitxonline/pull/1062
> add webpack bundle analyzer

- sheets/management/commands/process_coupon_assignment_sheet.py
Related to https://github.com/mitodl/mitxpro/issues/2415
The issue above was fixed, however there is a bug, where we check for BulkCouponAssignment to be created and that is causing a problem since the instance gets created in the previous command `process_coupon_assignments`. 
Instead of creation, we just need to check is the sheet was ever manually updated before.
As a result, we need to run this command `process_coupon_assignment_sheet` twice, since it fails on first run.
This PR fixes the issue, so that the command succeeds on first run.
`
Set up google sheets locally (here are the [instructions](https://github.com/mitodl/mitxpro/blob/master/sheets/dev-setup.md))
and then you would need to go through the whole [process](https://github.com/mitodl/mitxpro/blob/master/sheets/dev-setup.md# …
> bulk assignment instance already created

- courses/models.py
- ecommerce/models_test.py
- ecommerce/serializers_test.py
N/A
This hopefully fixes some performance issues, at the very least it avoids the possibility of it, by switching to a function that generates the image url rather than using `get_rendition` which can potentially cause a fetch from S3 if the image isn't cached.
I haven't been able to reproduce this locally, so for local testing just verify that with S3 storage configured you can upload image assets and they display without error on the catalog pages.
> Fixed improper usages of get_rendition

- requirements.in
- requirements.txt
Part of #2484 
This upgrades `django-storages` and `boto3`. `django-storages` has had [this issue](https://github.com/jschneier/django-storages/pull/358) fixed since the version we're using. The upgrade to `boto3` is being done since that library was almost 2 years behind.
- Verify you can still upload images
- Verify the catalog pages still work both with images uploaded on this branch and existing images.
> Upgrade django-storages

- config/nginx.conf
- config/nginx.conf.erb
- loadtest.js
Part of #2484 
This updates the nginx config to drop the `Vary` header on wagtail images. This will allow fastly to consistently cache these regardless of any headers present.
Browse around and verify wagtail images don't return this header anymore. Other resources like html pages should still have it.
> Updated nginx to drop Vary header on wagtail images

- ecommerce/api.py
- ecommerce/api_test.py
Closes #2508 
Makes the query for a user's unused coupons marginally more efficient, and fixes a bug that returns the same coupon multiple times if there are multiple `CouponPaymentVersion` objects for it.
On master branch:
- As a superuser, go to `../ecommerce/admin/coupons/`, create a new coupon code for a certain course, expiring sometime in the future.
- Find the `CouponPaymentVersion` for the coupon you just created, change the expiration date, and save as new.
- Create a csv file containing 1 email for a user (can be the superuser).
- Go to '../ecommerce/admin/enroll/',  choose the above csv file, the coupon course, and the coupon, then click 'Enroll Learners'
- Log in as the enrolled user if you aren't already (refresh the page if you are).  You should see a "You have an unused …
> Fix unused coupons query

- cms/models.py
- cms/models_test.py
https://github.com/mitodl/mitxpro/issues/2484
- Attempts to reduce the number of queries we are hitting on home page
- Refactors the HomePage and Product Page common functionality into a mixin
- Reduces the number of queries on HomePage
Before testing it might be a good idea to setup [django-silk](https://github.com/jazzband/django-silk) to see the performances of the pages since I've been testing it with that.
- Make sure to add a HomePage and all the child pages in it through `/cms`
- Make sure that you have enough program and course, external program, external course pages, and all their child pages through `/cms`
- Make sure that your HomePage `http://xpro.odl.local:8053/` works fine and shows all the child pages
- Make sure the number of queries on HomePage has been reduced w.r.t to …
> fix: enhance home page queries wagtail

- .github/workflows/ci.yml
- cms/models.py
- scripts/test/python_tests.sh
None
Adds a separate step for black formatting check. It is better to add an extra step as we did for Pylint.
MOTIVATION: Black formatting check is added with the `Tests` step. If there is any issue with the formatting and everything else is fine then it is a bit difficult to find the cause of failure of the `Tests` step as happened [here](https://github.com/mitodl/mitxpro/actions/runs/3695611774/jobs/6258212803).
Maybe commit a formatting issue with these changes and push the change. CI should fail at the newly added formatting step.
> Adds a separate step for black formatting check

- docker-compose.override.yml
- docker-compose.yml
- mitxpro/settings.py
- mitxpro/urls.py
- requirements.in
- requirements.txt
N/A
Adds `django-silk` and makes it available when `DEBUG=True`, this will initially be just for local and possibly RC debugging.
- With `DEBUG=True`, verify you can go to `/silk/` and see profiling results as you navigate the app
- With `DEBUG=False`, verify `/silk/` is unreachable
> Setup django-silk when DEBUG=True

- mitxpro/wsgi.py
Closes #2526 
Based off a gist, loads the xpro home page (or another url defined by `DJANGO_WARMUP_URL` env variable) after uwsgi starts the app and/or restarts workers.
Everything should still work as before.
You can set `MITXPRO_LOG_LEVEL=DEBUG` and then repeatedly reload the `/catalog` page (manually or via load test), eventually you should see this in the logs:
```
web_1     | worker 2 killed successfully (pid: 250)
web_1     | Respawned uWSGI worker 2 (new pid: 379)
web_1     | spawned 2 offload threads for uWSGI worker 2
web_1     | [2022-12-14 17:35:44] DEBUG 379 [root] wsgi.py:40 - [583ea7151673] - warming up
.....
web_1     | [2022-12-14 17:35:44] DEBUG 379 [root] wsgi.py:56 - [583ea7151673] - starting warmup response
``` …
> Force django app to load ASAP after uwsgi workers are restarted/forked

- courses/models.py
- courses/serializers.py
- courses/views/v1/__init__.py
Fixes https://github.com/mitodl/mitxpro/issues/2520
Reduces queries for the following APIs:
1. `api/programs/`
2. `api/course_runs/`
3. `api/courses/`
1. Make sure that you have enough data for Programs, Courses and Course runs.
2. Hit the endpoints mentioned above.
3. Monitor Django-Silk at `/silk/requests/`
4. There should be no N+1 queries.
(Note: `api/course_runs/` still contains a few N+1 queries as I could not figure out a good fix. It still reduces queries by 80%-90%)
> Reduce API queries

- mitxpro/templates/404.html
- mitxpro/templates/500.html
- static/js/components/Header.js
- static/js/components/TopAppBar.js
- static/js/components/TopAppBar_test.js
- static/js/containers/App.js
- static/js/containers/HeaderApp.js
#2518 
Revoke user profile API call on `404 not found` and `500 internal server error` pages
- Checkout to this branch
- Run the project and visit any random invalid URL to get the `404 page`
- Validate in the browser development network tab that there is no `/api/users/me` call
- Validate on the `404 page` header has no `user info` section or `signing` or `create account` buttons
Logged-out page header
Logged-In page header
> fix: 404 page doesn't need authentication

- hubspot_xpro/management/commands/configure_hubspot_properties.py
- hubspot_xpro/management/commands/sync_db_to_hubspot.py
- hubspot_xpro/management/commands/sync_hubspot_ids_to_db.py
- hubspot_xpro/serializers_test.py
- hubspot_xpro/tasks.py
- hubspot_xpro/tasks_test.py
Closes #2463 
Copies the more efficient batch syncing functions for deals/lines/associations from bootcamps & mitxonline to xpro.
Follow the README on hubspot integration.  You can use the same value for `MITOL_HUBSPOT_API_PRIVATE_TOKEN` as RC, but your `MITOL_HUBSPOT_API_ID_PREFIX` value should be unique to your instance.
Assuming you already have some data, run the following:
```python
manage.py sync_hubspot_ids_to_db --users
manage.py sync_db_to_hubspot  --users create
manage.py sync_db_to_hubspot  --products create
manage.py sync_db_to_hubspot  --deals create
manage.py sync_db_to_hubspot  --lines create
manage.py sync_db_to_hubspot  --associations create
```
Then check the hubspot UI (I can provide a login) to verify that all your deals are synced, and have associated products and …
> Hubspot batch sync improvements

- courses/serializers.py
- courses/serializers_test.py
Closes #2539 
Adds the course CMS page to catalog API results
Go to "http://xpro.odl.local:8053/api/courses/", there should be a populated `url` field for every course that has a CMS page.
Ditto for all the courses listed under each program at "http://xpro.odl.local:8053/api/programs"
> Course urls in catalog API

- cms/factories.py
- courses/views/v1/__init__.py
- courses/views_test.py
Closes #2542
Excludes courses/programs without live CMS pages from the catalog API results
Go to http://xpro.odl.local/api/programs and http://xpro.odl.local/api/courses.  Only results with live CMS pages should be returned.
> Only return courses/programs with live cms pages in the catalog API response

- mitxpro/wsgi.py
This reverts commit 76f315fd2f7cec97546838903fc3c92711139d97 because it does not play nice with heroku.
#2526
Reverts a previous PR
Will need to be tested on RC, but your local instance should still start up
> Revert "Force django app to load ASAP after uwsgi workers are restarted"

- hubspot_xpro/tasks.py
- hubspot_xpro/tasks_test.py
Closes #2550 
Modifies the `hubspot_xpro.tasks.task_obj_lock` function so that it properly handles cases where the object id is passed in a kwargs dict instead of an args list (for example, `hubspot_xpro.task_helpers.sync_hubspot_b2b_deal`)
- Set `MITOL_HUBSPOT_API_PRIVATE_TOKEN` to the same as RC and `MITOL_HUBSPOT_API_ID_PREFIX` to something unique to you in your .env file.
- From the UI, you can create an `Order` (just buy something) and a `B2BOrder` (https://xpro.odl.local/ecommerce/bulk/) if you don't already have one of each.  If you do and don't want to create more, you can run this in a shell instead:
```python
from b2b_ecommerce.models import *
from ecommerce.models import *
from hubspot_xpro.task_helpers import *
sync_hubspot_deal(Order.objects.last()) …
```
> Fix bug with calling b2b deal sync function from helper task

- cms/templates/home_page.html
- cms/views_test.py
Fixes https://github.com/mitodl/mitxpro/issues/2521
- Adds frontend caching for the homepage.
- Caching reduces about 50%+ queries.
- Cache invalidates after 24hrs.
- Make sure that you have enough data on the home page
- Visit the home page with these changes.
- Monitor Django Silk at `/silk/requests/`. Note the number of queries.
- Check out these changes and visit the home page several times. Caching should be done for the home page and the query count is also less.
- Make changes to the child pages of the home page.
- Make sure that the changes are visible on the home page.
I went through a couple of things to improve the Home page. It seems like caching is our best bet. Wagtail invalidates the cache when there are any changes in the pages and that keeps invalidating the cache …
> Add frontend caching for homepage

- users/utils_test.py
Fixes #2556 
Tests `users.utils.format_recipient` against `Users` with specified names and emails, with and without prefixes and titles.
Unit tests should pass, functionality is unaffected
`format_recipient` calls `email.utils.formataddr` which sometimes surrounds the name with double quotes (typically when the name includes a prefix or title).  This would cause the previous version of the unit test to fail if the randomly generated user name had a prefix.
> Fix flaky test

- sheets/tasks.py
- sheets/tasks_test.py
Closes #2456
Stops treating celery task metadata kwargs as a serialized string, because it is now a proper dict (maybe as a result of a prior celery upgrade?)
In a shell run the following:
```python
from sheets.tasks import schedule_coupon_assignment_sheet_handling, _get_scheduled_assignment_task_ids
schedule_coupon_assignment_sheet_handling.delay("1xMmUnWm95uyMKXQm-_262tARY0uGYLcSay0qKhud1Zo")
print(_get_scheduled_assignment_task_ids("1xMmUnWm95uyMKXQm-_262tARY0uGYLcSay0qKhud1Zo"))
```
On this branch, the print statement should show a list with one value.  On master branch, it will throw an error (`AttributeError: 'dict' object has no attribute 'replace'`)
> Fix processing of scheduled sheet coupon assignment tasks

- ecommerce/api.py
- ecommerce/api_test.py
https://github.com/mitodl/mitxpro/issues/2558
Adds logic to prevent applying a global promo code to a product that requires an enrollment code, applying the enrollment code created for the product should be allowed
- Create a product if not exist
- Create a product version http://xpro.odl.local:8053/admin/ecommerce/productversion/, and check "Requires enrollment code"
- Create a promo coupon "XPRO23" from http://xpro.odl.local:8053/ecommerce/admin/coupons/ (Promo), check "Global coupon" but don't check "Automatically apply coupon to eligible products in basket"
- Create an enrollment code  from http://xpro.odl.local:8053/ecommerce/admin/coupons/ (Coupon codes), and select the course run or program associated with the product you just created
- Verify the two codes you just created …
> Prevent promo code from applying to products that require enrollment code

- courseware/api.py
- courseware/api_test.py
#2473 should be merged before this one
Closes #2470
Marks an xpro enrollment as enrolled in edx too if the enrollment exists there and is active
You will need devstack up and running for this.
- In xpro, modify the course run "course-v1:edX+DemoX+Demo_Course" (which should also exist in your devstack edx instance) so that the enrollment start date begins now, and the run start/end dates are in the future.
- As any user, register for the course.
- As admin, go to the details page for that new enrollment in django admin, and uncheck 'Edx enrolled'
- Modify `courseware.api.enroll_in_edx_course_runs` to always raise an Exception:
```python
for course_run in course_runs:
raise EdxApiEnrollErrorException(user, course_run, MockHttpError())
```
- In a shell, run:
```python
from courseware.api …
```
> Check if edx enrollment already exists for failed enrollments

- courses/utils.py
#2568 
The certificate job suspending due to an error where the `ProgramEnrollment` model has multiple entries for a user in a single program. This PR will ignore this error and continues to generate certificates
In order to test before and after this change
- **Open the terminal from running the xpro app and run these commands**
- `python manage.py shell`
- `from django.contrib.auth import get_user_model`
- `from courses.models import Program, ProgramEnrollment, ProgramCertificate`
- `from courses.utils import generate_program_certificate`
- `User = get_user_model()`
- `user = User.objects.get(id=<EXISTING_USER_ID>)`
- `program = Program.objects.get(id=<EXISTING_PROGRAM_ID>)`
- `ProgramEnrollment.objects.create(user=user, program=program)` **_Run this command two times to create …
> fix: certificates jobs should continue on errors rather than halting

- courseware/api.py
- courseware/api_test.py
#2471 
Partially fixes issue #2471
- If a user exists on edx with the same username and email this error will not be raised as an exception
- This PR will fix the `CoursewareUser` model entry and generate the token for that user
- Added migration for the `max_length` character check on the `name` in the `user` model
- So that a fake user like this https://xpro.mit.edu/admin/users/user/72642/ will not be created
- This user should be deleted before migrations are applied or before merging this PR
- If there is a user on xpro with a different username but the same email from on edx or vice versa will not be fixed
- as discussed in the above ticket
- Change or add this `REPAIR_COURSEWARE_USERS_FREQUENCY=10` variable's value in the `.env` file
- Run this command `python manage.py …
> fix: Error creating Open edX user. user already exists or invalid name

- cms/models.py
- courses/models.py
- courses/models_test.py
None, It was noticed during the testing of https://github.com/mitodl/mitxpro/pull/2585, 
**What was the Issue?**
What was actually happening was that I was getting the marketing URL from `first_unexpired_run` for both Courses, Programs. This worked fine for courses but failed for programs because `first_unexpired_run` for a program returns a course run and not a program run as I'd have assumed. So, For an external program with child courses, the `Learn More` button would show the course's marketing URL instead of the Program's.
See https://rc.xpro.mit.edu/programs/program-v1:xPRO+externalprogram/ on RC to notice this behaviour.
- Fixes the issue with the external Program's marketing URL 
- Create a program, in Django Admin, and create an associated page in CMS
- Create a course in Django, …
> fix: external program url on Program Details/Product page

- sheets/coupon_assign_api.py
#2414 
Invalid message type. changed `error` to `info` type message ([details](https://github.com/mitodl/mitxpro/issues/2414#issuecomment-1478568191))
> fix: Cannot create ProductCouponAssignments for codes that have already been redeemed error message to info message

- cms/migrations/0054_create_external_courseware_asociations.py
For reference take a look at [this Slack thread](https://mitodl.slack.com/archives/GG8B4C3JP/p1680709865870479?thread_ts=1680708663.243279&cid=GG8B4C3JP).
Take a look at the failing logs on prod [here](https://mitodl.slack.com/archives/GG8B4C3JP/p1680708336267129).
This was noticed when we deployed the last release to production https://github.com/mitodl/mitxpro/pull/2606. The existence of this data was unexpected because we would not expect any `Course, CourseRun, Program, ProgramRun, or Product` entries for External courseware that were present before the release.
Since this data wasn't expected to be there, so now this PR makes the data migration less aggressive in these ways so that the production release goes out:
1. If there is an existing course with the same `readable_id` value as …
> fix: data collision issue with existing Readable Ids

- test_requirements.txt
None, Noticed an issue with PyPi with this in a build failure https://github.com/mitodl/mitxpro/actions/runs/4679245915/jobs/8289469070
Temporarily removed the `codecov` because it's PyPI distribution is gone.
**NOTE:** I didn't remove the codecov action from `ci.yml`.
All the actions should pass.
See [this](https://mitodl.slack.com/archives/GG8B4C3JP/p1681310383242929) Slack thread.
(Optional)
(Optional)
> fix: temporarily remove codecov until it's PyPI package distribution is fixed

- courses/api.py
- courses/api_test.py
- courses/management/commands/create_enrollment.py
- courseware/exceptions.py
- sheets/deferral_request_api.py
#2432 
Fixes the errors where
- No error was recorded in the sheet if the enrollment failed
- The deferral was only attempted once. The learner was unenrolled from the "from" course, but never successfully enrolled in the "to course"
- edX and xPro should be working locally
- Follow this [sheet](https://docs.google.com/spreadsheets/d/1Ldmnp3_czm3JjiOo3DGUVUkedGHV2zqXVFwi63KupEE/edit#gid=1358082255) pattern and make one in your `gdrive` for local testing
- Enroll the user in `from course run` in any course mode except `audit` mode on edX
- Make sure that enrollment mode is not available for `to course run` on edX
- Setup your sheet with your local project
- Open the xPro shell (`./manage.py shell`) and run these commands as follows
- `from sheets.tasks import …
> fix: Sheets deferral failed but no error was recorded in sheet

- cms/models.py
- cms/models_test.py
- cms/templates/partials/card_details_top.html
- courses/models.py
None, Noticed this while testing https://github.com/mitodl/mitxpro/pull/2598. Actually a bug from before but we just noticed it in this release.
The program Detail page and in the Catalog page also link to the draft courses that resolve to be 404 for the users.
- Updates the logic on Catalog, To show only those subcourses link under program details that are published and visible to users.
- First reproduce, Create a program and create three or more associated courses in Django Admin
- Create a CMS page for one of the courses above, and create another CMS page for the other courses but this time keep it `Draft`. Keep the third course as is in Django Admin.
- Make sure you see that program in the catalog
- Click `Details` and notice that you should only see one course link here that should …
> fix: Only link courses in programs that have live CMS page

- cms/models.py
- courses/models.py
- courses/serializers.py
- courses/serializers_test.py
- courses/views/v1/__init__.py
Last part of https://github.com/mitodl/mitxpro/issues/2546
#2582 
- Enable certificate pages to be added under external courseware pages
- Updates `api/courses` and `/api/programs` to return external courseware as part of the response
- Add additional fields mentioned in https://github.com/mitodl/mitxpro/issues/2546 to the API response
**NOTE:** You should create the topics through CMS now. Also, you should associate the topics to courses pages moving onward, The topics can't be added or associated with courses through Django Admin.
**Case 1 APIs**
- Check that '/api/courses' and `/api/programs` APIs return data as per expectations
- Ideally, the course and program details should include fields such as:
- `is_external`
- `time_commitment`
- `duration`
- `video_url`
- `format`
- `credits` …
> feat: update APIs to support external courseware data and additional fields

- static/scss/catalog/body.scss
- static/scss/detail/catalog-topics.scss
None
Fixes topic height when line length increases.
- Add a topic with line length that goes over multiple lines.
- Verify that the height is fine.
AFTER:
BEFORE:
> fix: fix topic height when line length increases

- courseware/api.py
- courseware/api_test.py
#2471 
Follow up of #2579. Fixes issue #2471. Where the email is the same and the xPro username is different from edX
- If an xPro user exists on edX with a different username but the same email this error will not be raised as an exception anymore
- This PR will fix the `CoursewareUser` model entry and generate the token for that user by updating the username on xPro
- This also fixes the edge case when another user already exists on xPro with an edX username
- Change or add this `REPAIR_COURSEWARE_USERS_FREQUENCY=10` variable's value in the `.env` file
- Run this command `python manage.py createsuperuser` on `xpro` and `edx` and create a user with a different username but the same email
- Run the `xpro` and `edx` and check the celery logs of xpro
- You can test it without creating a new …
> fix: Error creating Open edX user. user already exists or invalid name (follow-up)

- cms/views_test.py
- courses/models.py
None
- Orders the topics list on HomePage and Catalog page alphabetically.
- Add some topics randomly, Visit the Catalog Page, they should be sorted alphabetically.
- Visit Home Page and check that the topics are sorted alphabetically as well.
- An additional thing you can do is to update topic name(s) and make sure that the ordering still works accordingly
We added the topics filtering in https://github.com/mitodl/mitxpro/pull/2629, Afterward we decided to order them alphabetically.
**Catalog After**
**Catalog Before**
**HomePage After**
**HomePage Before**
(Optional)
> feat: order topics alphabetically on HomePage and CatalogPage

- b2b_ecommerce/views.py
- b2b_ecommerce/views_test.py
- hubspot_xpro/tasks.py
- static/js/components/forms/B2BPurchaseForm.js
- static/js/components/forms/B2BPurchaseForm_test.js
#2555 
fixes the issue `Some B2BOrder email values have trailing spaces, carriage returns, and other invalid values that get rejected by Hubspot`
- Open `/ecommerce/bulk/`
- Enter the email with spaces
- Validate it should display an error message
- and you'll not be able to submit the form
Before:
After:
> fix: Bad B2BOrder email values cause exceptions when syncing to Hubspot

- courses/serializers.py
- courses/serializers_test.py
https://github.com/mitodl/hq/issues/1418
- Adds a check to fetch course topics only when there is a course page
I'd recommend recreating this issue on Master before testing this PR. 
To recreate the issue, You need to create a Program in Django Admin, Also create a course in Django Admin. Create products for both. Note that you should not create any CMS pages for these.
Associate the course with the program in Django Admin. Now, Manually enter the URL `http://xpro.odl.local:8053/checkout/?product=<your_program_id>` and `http://xpro.odl.local:8053/checkout/?product=<your_course_id>` You should notice [this error](https://mit-office-of-digital-learning.sentry.io/issues/4120830727/?project=1413655).
- Now to test the fix, Move to this PR and run the checkout URL again, the page should work, …
> fix: checkout when there is a course without course page

- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- authentication/serializers.py
- static/js/constants.js
- static/js/containers/pages/register/RegisterConfirmPage.js
- static/js/containers/pages/register/RegisterDetailsPage.js
- static/js/containers/pages/register/RegisterDetailsPage_test.js
- static/js/flow/authTypes.js
- static/js/lib/util.js
- users/serializers.py
#2633 
Fixes the two account issue with one email #2633 
1. Checkout to this branch and run xpro locally
2. Open `Create Account` on local `xpro`
3. Enter an email, with lowercase letters in the address
4. In another tab, open `Create Account` again and enter the same email, but all uppercase 
5. You should get two verification emails, with different links. 
6. Follow one of the links and complete the first screen of the account creation process
7. In a private window or another browser open the 2nd verification link and complete the first screen of the account creation process
8. You should see an error screen as the screenshot below on submit that a user already exists
> fix: Two accounts with the same email

- courses/api.py
- courses/api_test.py
- courseware/api.py
- courseware/api_test.py
- requirements.in
- requirements.txt
#2631 
A site admin can run the `defer_enrollment` management command to transfer a user to a course run even after the enrollment period ends
- `edX` and `xpro` should be working on the local machine
- Try to enroll a user in an enrollment-expired course run using the `defer_enrollment` command using `-f` argument
- Validate the user is enrolled in the given course run on `xpro` and `edX` on your localhost
> feat: Update management command for user deferrals to include courses with closed enrollments

- static/js/components/TopAppBar.js
None, Hot fix
- Hides the `Webinars` link from the Top App bar
- Just check that there is no `Webinars` link in the app bar and the design stays intact 
(Optional)
(Optional)
This PR is based on master which has some other functionalities e.g. Courses drop-down but it won't be there in production.
(Optional)
> hotfix: hide the Webinars link from top app bar

- hubspot_xpro/tasks.py
- hubspot_xpro/tasks_test.py
- requirements.in
- requirements.txt
- Uses the new version of mitol.hubspot_api which can handle conflicts caused by a Hubspot contact having 2 emails associated with different bootcamps users
- Modifies the batch create/update tasks to try syncing contacts individually (to hit code above) if any API exceptions occur when running batch sync operations.
- Ask for access to the xprodev sandbox account for hubspot if you don't already have it.
- Copy the `HUBSPOT_*` settings values from RC to your .env file
Part 1:
- Create a new user in xpro, something like `fake_user+1@gmail.com`
- Find the contact in hubspot (may take a minute or so to show up) and add a secondary email to that contact: `fake_user+2@gmail.com`
- Register another new user with that same email - `fake_user+2@gmail.com`
- Check back on hubspot, that secondary …
> Use new hubspot_api version and try to sync contacts individually if a batched sync chunk fails

- requirements.txt
https://github.com/mitodl/mitxpro/security/dependabot/78
Fixes the issue https://github.com/mitodl/mitxpro/security/dependabot/78. Also, rebase was not working on this PR https://github.com/mitodl/mitxpro/pull/2567 So created a manual PR with the latest version
All tests should be passed, Register, Login, Enrollment, and Cubersource testing would be enough.
> Manually bump cryptography from 38.0.3 to 40.0.2

- requirements.in
- requirements.txt
fixes https://github.com/mitodl/mitxpro/security/dependabot/91
This fix is related to uploading multiple files using one form field and has never been supported by [forms.FileField](https://docs.djangoproject.com/en/4.2/ref/forms/fields/#django.forms.FileField) or [forms.ImageField](https://docs.djangoproject.com/en/4.2/ref/forms/fields/#django.forms.ImageField) as only the last uploaded file was validated.
- This is a minor upgrade from `3.2.18` to `3.2.19`
- We currently do not have a form supporting multiple files or image uploads
- Smoke tests would be enough
> Django bypasses validation when using one form field to upload multiple files

- courses/api.py
- courses/api_test.py
https://github.com/mitodl/hq/issues/1487
Creates enrollment in xPro if edX enrollment fails due to the missing user account on edX.
This issue exists when a user does not exist in edX but exists in xPro and we try to enroll.
On Master Branch:
- Create a new user in xPro that does not exist on edX. Maybe stop edX and create your user in xPro. OR Delete a user from edX.
- Enroll in a course. Complete Cybersource payment.
- You will get an exception OpenEdXOAuth2Error.
- Order is successfully created with Fulfilled State but course run enrollment is not created.
Now repeat the above steps with the changes in this PR. You won't get any exceptions and the course run enrollment is created with edx_enrolled=False.
NOTE: If you are not able to reproduce OpenEdXOAuth2Error on the master branch due …
> fix: create enrollments when token creation fails

- ecommerce/management/commands/invalidate_payment_coupons.py
n/a
Adds a new command, `invalidate_payment_coupons`, to bulk invalidate coupons. It accepts:
- A coupon payment name, which it will iterate over to deactivate active codes within
- A plain text file, with each coupon listed as the code on one line
This is mainly for convenience; I sometimes have to invalidate batches of codes and this would be easier than doing it from a database shell.
Create a couple batches of codes in two payments. Save one of the batch's coupon codes to a file - one per line, just the coupon code, no headers. 
1. Run `invalidate_payment_coupons` with no arguments. It should complain that you haven't specified a payment name or a file to process.
2. Run `invalidate_payment_coupons --payment` with an invalid payment name. It should complain that you haven't specified …
> Adding command to invalidate coupons

- courses/management/commands/sync_grades_and_certificates.py
#2675
This PR adds a try except block ensuring the certificate creation process continues despite some failed entries too
1. Enroll some users in a course
2. Explicitly set `override_grade` in `sync_grades_and_certificates` to value `> 1.0`
3. Run the command `sync_grades_and_certificates --run="course-run" --force`
4. You should see multiple errors for all enrolled courses
5. (Optional) Randomly tweak `override_grade` values for users
6. (Optional) Run the command again, and you will see successful message for the ones which had correct values and errors for the others
> fix: Certificates creation does not halt entire process

- courses/management/commands/manage_program_certificates.py
- courses/management/commands/test_manage_program_certificates.py
https://github.com/mitodl/mitxpro/issues/2676
This PR introduces a new management command which helps making program certificates for user(s) on the fly.
1. En-roll a user in a program
2. Complete courses for that program (directly from the admin panel)
3. Once courses are updated, run `docker-compose run --rm web ./manage.py sync_grades_and_certificates --user=user_email --run=<course_run>`
4. Run the following command,  
5.  `docker-compose run --rm web ./manage.py manage_program_certificates --readable_id=<program_id>`
6. You should see message in console, indicating success of certificate creation
> Manage Program Certificates Command

- courses/api.py
- courses/tasks.py
- courses/tasks_test.py
Closes #2671
This PR resolves the errors logged in sentry regarding missing courses in edx
1. Mark some courses external locally via local admin
2. Execute the python shell in mirxpro-web docker container, `docker exec -it mitxpro-web-1 ./manage.py shell`
3. Fetch the courses via new queryset and either compare the lengths of objects returned or the is_external propertry of the objects
> fix: course not found errros on sentry

- sheets/deferral_request_api.py
Related to https://github.com/mitodl/hq/issues/1895
Set 'force' flag when processing deferral requests.
This would proceed with enrollment if:
1) from enrollment not active
2) if course run is outside of the enrollment window
Have google sheets set up locally, for setup follow [instructions](https://github.com/mitodl/mitxpro/blob/master/sheets/dev-setup.md).
Submit a request for a deferral where the "To Course" is not within enrollment window. The enrollment should succeed.
> Force enrollment when deferring enrollment

- cms/api.py
- cms/api_test.py
Fixes https://github.com/mitodl/hq/issues/2037
Updates the catalog course ordering. Moves the courses with no start date to the end.
- Create some external courses.
- Create some internal courses with the start date in the past but the end date should be in the future.
- Create some courses with start dates in the future.
- Catalog will display the start date for only future start dates. Verify that courses without a start date are at the end of the catalog.
> feat: update catalog ordering

- cms/templates/partials/metadata-tiles.html
https://github.com/mitodl/hq/issues/2035
- Fixes a bug with external course links from within More dates
- Clicking any date from more dates should behave like `Learn More` button and should take the user to the external website instead of the checkout page.
- Setup some external courses, Programs
- Setup multiple enrollable runs
- Check that you see the `More Dates` link in the Course details page's tiles
- Now click on any date from the more dates, and they should all resolve to the external marketing site URL defined in the CMS page of the course or program instead of the checkout page.
- Setup external courseware
> fix: more dates links for external courseware

- cms/models.py
A small fix for https://github.com/mitodl/mitxpro/pull/2704
Includes upcoming webinars with a start date equal to the current date.
Create an upcoming webinar with the start date  = today's date and verify that it shows up on webinar list page at `/webinars`
> fix: include todays webinars in upcoming webinars list

- mitxpro/settings.py
Related to #2453 
Remove certain default HubSpot values from `settings.py` file, and you can find these values in the [salt-ops](https://github.com/mitodl/salt-ops) repository [here](https://github.com/mitodl/salt-ops/blob/cafbf0fe6bca95c55a90e8d5cdcd14388483913f/pillar/heroku/xpro.sls).
To test this change locally, follow these steps:
- Access/open the Django shell.
- Import the settings.
- Attempt to fetch the `HUBSPOT_CONFIG` key.
- Initially, it should return with the empty strings (default).
Next, add the necessary configuration details related to `HUBSPOT_CONFIG` to the `.env` file, including:
- HUBSPOT_NEW_COURSES_FORM_GUID
- HUBSPOT_FOOTER_FORM_GUID
- HUBSPOT_PORTAL_ID
After adding the configuration details, run the test again. 
Verify that you can now successfully retrieve the …
> fix: update hubspot settings default values

- courses/api.py
- courses/api_test.py
- courseware/api.py
- courseware/api_test.py
Fixes https://github.com/mitodl/hq/issues/2380
(Required)
Forces all of the enrollments in edX as we have marked courses as invite-only to avoid direct edX enrollments.
(Required)
- Make sure that the MITxPro / edX integration is working
- Enable `COURSES_INVITE_ONLY` in edX.
- Check out this branch in MITxPro.
- Verify that the Enrollment/Unenrollment is working fine.
- Verify the following management commands:
- defer_enrollment
- transfer_enrollment
- refund_enrollment
- retry_edx_enrollment
- create_enrollment
> feat: force all enrollments

- ecommerce/api.py
- ecommerce/mail_api_test.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
mitodl/hq#2575
Updates the receipt serializer to format tax paid and total paid for two decimal places.
Updates the `create_unfulfilled_order` call to only look at active TaxRate objects.
1. Create an inactive tax rate for your country, then attempt to check out. You should not be charged tax.
2. View the receipt for an order that has had tax assessed. The Tax and Total Paid should be formatted with two decimal places.
Tax here is 17% so the actual tax charged is $21.675.
> Fixing formatting errors on receipt page, should not charge tax if TaxRate

- static/js/lib/ecommerce_test.js
Tests for https://github.com/mitodl/mitxpro/issues/2769
Adds tests for https://github.com/mitodl/mitxpro/pull/2773
Checks should pass.
> tests: adds frontend tests for the taxes

- mail/templates/product_order_receipt/body.html
- static/js/components/forms/CheckoutForm.js
- static/js/components/forms/CheckoutForm_test.js
- static/js/containers/pages/ReceiptPage.js
- static/js/flow/ecommerceTypes.js
- static/js/lib/ecommerce.js
- static/js/lib/ecommerce_test.js
- yarn.lock
https://github.com/mitodl/mitxpro/issues/2788
- Adds tax rate display on Checkout 
- Adds tax rate display on In-app Receipt 
- Adds tax rate display on Email Receipt 
- Fixes some failing tests
- Adds some missing tests for frontend in for CheckoutForm
- Upgrades `caniuse-lite` to fix frontend/JS tests
- Start setting up things for taxes as per https://github.com/mitodl/mitxpro/pull/2772 If you have not worked with taxes in xPRO before
- Add/Enable `FEATURE_ENABLE_TAXES_DISPLAY=True` so that taxes can be displayed on the frontend
- Make sure you have added an entry for `TaxRate` in Django Admin for your country
- Since your IP would be from a docker network, it would not be related to a country, An easy solution is to get your actual IP address and hardcode it in …
> feat: display tax rate on checkout, receipt and email

- courses/admin.py
Fixes [This Sentry error](https://mit-office-of-digital-learning.sentry.io/issues/4545153479/?project=1413655&query=is%3Aunresolved&referrer=issue-stream&stream_index=0).
Fixes a bug when searching courses or programs with platform names.
- Check that you can search courses and programs through Django Admin based on the platform name.
> fix: platform name search in Django Admin Courses/Programs

- mail/templates/product_order_receipt/body.html
- mail/templatetags/format_discount.py
- mail/templatetags/format_discount_test.py
- static/js/components/forms/CheckoutForm.js
- static/js/components/forms/CheckoutForm_test.js
- static/js/containers/pages/ReceiptPage.js
- static/js/lib/ecommerce.js
- static/js/lib/ecommerce_test.js
https://github.com/mitodl/mitxpro/issues/2787
- Displays the discount amount as negative in CheckoutPage, ReceiptPage, and receipt email
- Adds a new template tag to mimic discount behavior in other templates as well
- Refactors `ecommerce.js` to have the functionality to show discounts in a specific format
- Create a couple of Courses, Programs, and products with enrollable runs
- Create a couple of discounts using `/ecommerce/admin` (e.g. 0%, 50%, 100%)
- Add a product in the basket (e.g. by clicking `Enroll Now` on course page)
- Apply different discounts to your basket and make sure you see a `-` sign e.g. `-$50` for the discount amount in the checkout. (Please Note: For $0 there will be no `-` sign)
- Now, Perform the checkout and view your receipt through `/dashboard` and check that …
> fix: display discount amount as negative

- mail/templates/b2b_receipt/body.html
- mail/templates/product_order_receipt/body.html
None, There was a typo in the receipt email. 
It used to say `Below you will find a copy of you receipt:` instead of `Below you will find a copy of your receipt:`
- Do a single checkout and check that the email typo is fixed
- Do a B2B Checkout and check that the email typo is fixed
**Regular checkout:**
--- 
**B2B Checkout**
> fix: receipt email typo

- cms/templates/webinar_page.html
fixes https://github.com/mitodl/hq/issues/2762
Add a link to the catalog page in Webinar page when there is no course/program link.
- Create an on-demand webinar.
- Associate a course/program.
- Verify that the courseware link is visible.
- Now remove the course/program from the already created webinar or create a new webinar without courseware.
- Verify that a link to the catalog page is there in place of the courseware link.
> feat: add xpro catalog link when no courseware is associated

- static/js/containers/pages/ReceiptPage.js
- static/js/lib/ecommerce.js
- static/js/lib/ecommerce_test.js
Part of https://github.com/mitodl/hq/issues/2605
- Unifies the decimal places for amount-related fields i.e. price, discount etc.
- Add any course or program to the cart and visit the checkout page
- Check that all the prices and discounts are in two decimal places even when the remainder part is zero or something else
- Below are some of the examples to test this so that we don't leave any unintended display with unexpected data
**Scenarios you might want to create**
- Order amount 0, discount 100%, tax None
- Order amount any, discount 0%, tax None
- Order amount any, discount 50%, tax any
- Order amount any, discount 0%, tax any
**Checkout**
**Receipt**
**Email Receipt**
> fix: Unify decimal places for price and discount

- docker-compose.yml
None. Started seeing this error after postgres version upgrade `11.6->11.16`. Done by Renovate through https://github.com/mitodl/mitxpro/pull/2815 
```db_1      | Error: Database is uninitialized and superuser password is not specified.
db_1      |        You must specify POSTGRES_PASSWORD to a non-empty value for the
db_1      |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
db_1      | 
db_1      |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
db_1      |        connections without a password. This is *not* recommended.
db_1      | 
db_1      |        See PostgreSQL documentation about "trust":
db_1      |        https://www.postgresql.org/docs/current/auth-trust.html
```
- Disables the password locally, allows `trust`
- Once you …
> fix: postgres startup error without password

- cms/models.py
- static/js/components/TopAppBar.js
- static/scss/top-app-bar.scss
(Required)
Fixes https://github.com/mitodl/hq/issues/3080
(Required)
Disables new and events section on the Home Page if Blog or Webinars feature is enabled.
Makes a few design adjustments.
(Required)
- Enable Blog and Webinar features by turning on FEATURE_WEBINARS and FEATURE_ENABLE_BLOG in .env
- Enable FEATURE_COURSE_DROPDOWN in .env
- Verify that you can see the updated header links for blog, webinar and courses dropdown and they are working fine.
- Verify that new and events is not visible on homepage.
> feat: enable header links and disable new and events on homepage

- cms/models.py
- cms/views_test.py
- courses/models.py
- courses/views/v1/__init__.py
A small enhancement for https://github.com/mitodl/mitxpro/issues/2614
Shows topics having more than zero courses on the course catalog page.
- Create a few parent topics with / without courses.
- Verify that only topics with Catalog Visible courses are visible.
We somehow missed adding an extra filter for the catalog page topics and I noticed it. This PR adds it.
> fix: return topics with more than zero courses

- hubspot_xpro/management/commands/configure_hubspot_properties.py
https://github.com/mitodl/mitxpro/issues/2847
- Adds the VAT ID property in HubSpot properties sync command
- Fixes sync issues with choice group order
- Setup a test account on HubSpot
- Add a private app in integrations (`settings->Integrations->Private Apps`)
- Copy the access token secret and place it as a value for `MITOL_HUBSPOT_API_PRIVATE_TOKEN`
- Copy the client secret and place it as a value for HUBSPOT_PIPELINE_ID
- I would suggest reproducing this issue on `master` first:
- Run `./manage.py configure_hubspot_properties` once above configs are done
- Notice error about duplicate orders in field choices of deal
- Create a new user and also notice that you see 400 errors from `sync_contact_with_hubspot`
-  Shift to this branch, And run `./manage.py configure_hubspot_properties` …
> fix: Add vat id in hubspot properties sync

- cms/models.py
None
Hides the child pages from the sitemap.
1. Create some child pages for the homepage and a courseware page.
2. Verify sitemap at `/sitemap.xml`, child page URLs should not be visible.
Local Sitemap **before** these changes:
[before.xpro.odl.local_8053_sitemap.xml.pdf](https://github.com/mitodl/mitxpro/files/14034764/before.xpro.odl.local_8053_sitemap.xml.pdf)
Local Sitemap **after** these changes:
[after.xpro.odl.local_8053_sitemap.xml.pdf](https://github.com/mitodl/mitxpro/files/14034765/after.xpro.odl.local_8053_sitemap.xml.pdf)
> fix: hide child page urls in sitemap

- static/scss/detail/enterprise/learning-journey.scss
- static/scss/detail/enterprise/learning-strategy-form.scss
None
Fixes issue with the path of an enterprise banner background. Image exists at `/images/enterprise/` but `enterprise/` was missing and resulted in 404.
- Setup enterprise page
- Verify the dotted banner for the learning journey and the learning strategy form.
Failing request on RC
After fix:
Before Fix:
> fix: fix static image path for enterprise page

- app.json
- mitxpro/settings.py
- mitxpro/templates/base.html
- mitxpro/views.py
Final updates for https://github.com/mitodl/hq/issues/3366 
Removes configurable changes for a single Zendesk Site Verification tag.
Hard codes 2 tags for the Sandbox and Prod.
- Checkout this branch.
- Visit any page.
- Verify that 2 meta tags exist for `zd-site-verification`.
- Verify the Values
- ZD Production Snippet: `<meta name='zd-site-verification' content='7e22kzikbruclk2jjomono' />`
- ZD Sandbox Snippet: `<meta name='zd-site-verification' content='o0itxdfh369m1bw4cuz9' />`
> feat: add prod zd-site-verification and hard code it

- voucher/admin.py
Closes https://github.com/mitodl/hq/issues/3795
Uses raw_id_fields for the `user` FK field in the voucher admin.
1. Timeout cannot be replicated without creating a lot of users.
2. We need to verify the Voucher admin at `/admin/voucher/voucher/`. The user should be a raw id field.
> fix: use raw id for voucher admin to avoid timeout

- courses/admin.py
[#3734](https://github.com/mitodl/hq/issues/3734) 
This PR autopopulates the datetime fields for start_date and end_date in the Django admin interface. It sets a default time of 23:59:00 and the default date to the current date for start_date, while end_date is autopopulated to the next day.
1. Checkout to this branch, and log in to the Django admin interface.
2. Create or Edit CourseRun Instance:
- Create a new CourseRun instance or edit an existing one.
- Observe that if the instance is new (not yet saved to the database), the start_date field defaults to the current date with a time of 23:59:00, and the end_date field defaults to the next day with a time of 23:59:00.
- If editing an existing instance, ensure that the default values are not applied to the start_date and end_date fields, …
> chore: set time fields for start/end date in Django with a default time

- cms/templates/partials/hero.html
- cms/templates/partials/keep_me_updated_button.html
- cms/templates/partials/subnav.html
- static/scss/detail/header.scss
- static/scss/detail/subnav.scss
- static/scss/variables.scss
Following up: https://github.com/mitodl/mitxpro/pull/2906#issuecomment-2025162702
This PR adds styling for the hubspot forms fields available in the [list provided](https://docs.google.com/spreadsheets/d/14iYQ61sktb1At32b9-KrO0yk8DZoaB4Nc98U04eUdyo/edit?pli=1#gid=457117068):
**desktop:**
**Mobile:**
**Mobile design(**keep me updated buttons**):** 
Mobile - header buttons:
Ipad:
Mobile subnav - collapse view (with `keep me updated` button):
Mobile subnav - collapse show view (with `keep me updated` button):
**Old mobile snapshots(header and subnav buttons):**
- Design to be validated: https://www.figma.com/proto/WE9AiQWwhDXe2W4jGTZL8Q/%F0%9F%93%90-MIT-xPro?type=design&node-id=154-2575&viewport=-782%2C262%2C0.18&t=QRs4HRUCF1F26rwP-0&scaling=min-zoom&starting-point-node-id=154%3A2575&show-pro …
> Styling for the hubspot forms fields available in the list provided

- mitxpro/settings.py
This commit adds two Celery client configurables necessary for monitoring.
- CELERY_TASK_TRACK_STARTED
- CELERY_TASK_SEND_SENT_EVENT
For: https://github.com/mitodl/ol-infrastructure/issues/2290
These two celery client configurables are necessary to allow celery tasks for this product to be monitored by [MIT OL Celery Monitoring](https://celery-monitoring.odl.mit.edu/).
Tasks for mitxpro heroku should appear in celery monitoring.
> Fix: This commit adds two Celery configurables for celery monitoring

- static/scss/voucher.scss
- voucher/templates/enroll.html
- voucher/utils.py
- voucher/utils_test.py
- voucher/views.py
- voucher/views_test.py
Closes https://github.com/mitodl/hq/issues/3809
Update the voucher parsing to do exact matching. The existing process was to match the vouchers partially in case when there were no exact matches. Moving forward, we will only do exact matches and show a confirmation screen with the exact match.
**_BEFORE:_**
_**AFTER:**_
- Set following values in `.env`
```
VOUCHER_DOMESTIC_DATE_KEY=UNIQUE01
VOUCHER_DOMESTIC_EMPLOYEE_KEY=UNIQUE02
VOUCHER_DOMESTIC_EMPLOYEE_ID_KEY=UNIQUE03
VOUCHER_DOMESTIC_KEY=UNIQUE04
VOUCHER_DOMESTIC_COURSE_KEY=UNIQUE05
VOUCHER_DOMESTIC_CREDITS_KEY=UNIQUE06
VOUCHER_DOMESTIC_DATES_KEY=UNIQUE07
VOUCHER_DOMESTIC_AMOUNT_KEY=UNIQUE08
VOUCHER_INTERNATIONAL_EMPLOYEE_KEY=UNIQUE09
VOUCHER_INTERNATIONAL_PROGRAM_KEY=UNIQUE10
VOUCHER_INTERNATIONAL_COURSE_KEY=UNIQUE11 …
```
> feat!: remove partial voucher matching

- ecommerce/mail_api_test.py
- ecommerce/utils.py
- ecommerce/utils_test.py
- ecommerce/views_test.py
- static/js/components/forms/CheckoutForm.js
- static/js/components/forms/CheckoutForm_test.js
- static/js/containers/pages/CheckoutPage.js
- voucher/views.py
- voucher/views_test.py
Followup on https://github.com/mitodl/mitxpro/pull/2940 due to this comment https://github.com/mitodl/mitxpro/pull/2954#issuecomment-2069371773
Hide extra course runs if checkout is made through a voucher. We had payment issues with Boeing when vouchers are used to enroll in different runs than the ones in the voucher. This PR hides extra runs from the checkout page when checkout is made through a voucher.
With Voucher:
Without Voucher:
- Set following values in `.env`
```
VOUCHER_DOMESTIC_DATE_KEY=UNIQUE01
VOUCHER_DOMESTIC_EMPLOYEE_KEY=UNIQUE02
VOUCHER_DOMESTIC_EMPLOYEE_ID_KEY=UNIQUE03
VOUCHER_DOMESTIC_KEY=UNIQUE04
VOUCHER_DOMESTIC_COURSE_KEY=UNIQUE05
VOUCHER_DOMESTIC_CREDITS_KEY=UNIQUE06
VOUCHER_DOMESTIC_DATES_KEY=UNIQUE07
VOUCHER_DOMESTIC_AMOUNT_KEY=UNIQUE08 …
```
> feat: hide extra course runs if voucher is applied

- courses/tasks_test.py
[#3774](https://github.com/mitodl/hq/issues/3774)
This PR should fix intermittent/flaky test assertion failure in test_sync_courseruns_data.
CI / python-tests should be passed
> fix: intermittent/flaky test assertion failure in test_sync_courseruns_data

- cms/models.py
- cms/models_test.py
Fixes [Sentry error](https://mit-office-of-digital-learning.sentry.io/issues/5393946540/?project=1413655&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=4) 
Using an invalid UUID to get a course run or program certificate results in a 500 server error. It should return 404.
Steps to reproduce:
- Checkout master branch
- fetch `/certificate/f5ab714b-a7ee-498f-bbec-/`
- It will raise a validation error
- Create Course Certificate and Program Certificate Pages in CMS
- Create Course Run Certificate and Program Certificate in Django Admin for a user
- Fetch the course certificate at `/certificate/<uuid>/` and the program certificate at `/certificate/program/<uuid>/`. You should see the valid certificates.
- Now Fetch course and …
> fix: invalid certificate uuid should raise 404

- courses/serializers.py
- courses/serializers_test.py
https://github.com/mitodl/hq/issues/4373
- FIxes the Programs API dates to match with the program CMS page dates
- Create a program and some courses under a program
- Create some course runs along with some expired runs
- Create a course with some expired course runs
- At this point, It would be a good idea to reproduce this issue
- Check `/api/programs` and `api/courses` APIS & check the start date of a program is not from an expired run
- The start date on Course/Programs pages should match the start dates in both `/api/course` & `/api/programs`
- Also, Smoke test other things e.g. Checkout & `/api/products` for any impacts of this change
**NOTE:**
1. With this change the start dates should be equal to the start date of the earliest reactive course run from the first course in the …
> fix: sync start dates for programs & courses between Program/Course pages & APIs

- .github/workflows/ci.yml
- docker-compose-notebook.yml
- docker-compose.yml
[#4440](https://github.com/mitodl/hq/issues/4440)
This PR upgrades the docker-compose & CI PostgreSQL version to 15.
- Check out this branch and follow one of the solutions below to upgrade the PostgreSQL version in your local environment (with or without data migration):
Follow these steps to upgrade PostgreSQL with data migration:
```sh
docker-compose exec -T db pg_dumpall -h db -U postgres > db_backup.sql
docker-compose stop
docker-compose rm -sv db
docker-compose up db -d
docker cp db_backup.sql $(docker-compose ps -q db):/tmp/backup.sql
docker-compose exec -T db psql -U postgres -d postgres -f /tmp/backup.sql
docker-compose up
docker-compose exec -e PGPASSWORD=postgres db psql -h db -U postgres
```
**Note**: If you encounter `password authentication failed for user "postgres"` in …
> refactor: upgrade docker-compose & CI postgres version to 15

- poetry.lock
- pyproject.toml
None, Reverts https://github.com/mitodl/mitxpro/pull/3010
In https://github.com/mitodl/mitxpro/pull/3016,  We noticed that django hijack was not working because they did major changes in how they serve the CSS & JS assets. As that happened, the JS started failing. We should do that as part of a separate ticket.
Install deps locally, and try to hijkack a user.
> revert: downgrade django-hijack 3.5.1 to 3.4.5

- docs/configure_open_edx.md
https://github.com/mitodl/hq/issues/4416
This PR replaces `mitxpro-openedx-extensions `with `openedx-companion-auth` in readme. More details in the ticket
- Validate the changes [here](https://github.com/mitodl/mitxpro/blob/anas/update-readme/docs/configure_open_edx.md)
> docs: replaced mitxpro-openedx-extensions with openedx-companion-auth in readme

- courses/sync_external_courses/emeritus_api.py
Follow up fix for https://github.com/mitodl/mitxpro/pull/2998
Course run dates were not updating If an external course run ID is added for a run and dates are null but the API has dates.
- Checkout master branch
- Run command `./manage.py sync_external_course_runs --vendor-name emeritus`
- Go to Django Admin, filter Emeritus course runs.
- Remove start and end date for a course run. The external course run ID should exist.
- Now run the management command again `./manage.py sync_external_course_runs --vendor-name emeritus`
- The start and end date won't update.
- Checkout this branch and run the command again.
- Dates should sync.
> fix(external course sync): sync course run dates if they are missing

- .env.example
None
Adds EMERITUS_API_KEY to .env.example
> chore: add fake EMERITUS_API_KEY to .env.example

- cms/templates/partials/text-video-section.html
None
In pre-commit linting PR https://github.com/mitodl/mitxpro/commit/dfcc79767f92d7403df229935a0444ea1e559d0b#diff-f5e2f8fa45e40f3cf5f0bba328204a9f365241ba1a7fbfd85db75ee89429257a, prettier converted double quotes to single quotes and it resulted in the broken video URL on xPro Home page. Instead of the video source, it contained a random iframe string. This PR reverts the Prettier change.
Check testing instructions for the steps to reproduce.
BEFORE:
AFTER:
- Checkout master or go to the prod homepage.
- For local, add a text video section for the homepage
- Click on the `Watch Now` button
- You will get an error.
- Now checkout this branch and test the same. Video should load.
> fix: homepage watch now video

- courses/api.py
- courses/management/utils.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- ecommerce/utils.py
- mail/constants.py
- mail/templates/welcome_course_run_enrollment/body.html
- mail/templates/welcome_course_run_enrollment/subject.txt
[#2470](https://github.com/mitodl/hq/issues/2470)
This PR implements the welcome email feature, which sends a welcome email based on each user's course enrollment.
1. Checkout to this branch and make sure openedx is configured.
2. Try to enroll any user to any course through frontend, or you can use create enrollment command to enroll a user.
- docker-compose exec web ./manage.py create_enrollment --user "<email>" --run "<course_run>" --code="test7e91c44ea5a999beasdfadsfadfadfwer"
3. Check if you receive welcome email along with enrollment email.
4. Verify the content of the email with welcome letter provided in the the ticket https://github.com/mitodl/hq/issues/2470#issue-1912198810 or you can see the link here: https://docs.google.com/document/d/1gGdXSVT4U34_bIADqGzZvcEyWuulM6VK8VDbqyDF1 …
> feat: welcome emails for xPRO Learners 

- package.json
- static/js/components/forms/ProfileFormFields.js
- static/js/containers/pages/profile/ViewProfilePage.js
- static/js/lib/api.js
- yarn.lock
Reverts mitodl/mitxpro#3013,
We will retry this PR after the product addition enhancement in data ingestion work. We will need to release that quickly so I am reverting this PR to decrease the scope of change set and testing.
> Revert "fix(deps): update dependency ramda to ^0.30.0"

- hubspot_xpro/management/commands/sync_db_to_hubspot.py
https://github.com/mitodl/hq/issues/4192
This PR adds the code to log the task ids of all the celery tasks which are started by the `sync_db_to_hubspot` management command  
- Create a developer account on hubspot using https://developers.hubspot.com/beta-docs/getting-started/account-types#create-a-developer-test-account
- Create a private app in your developer account with the following scopes:
- CRM: everything except quotes and feedback
- Standard: crm.export, crm.import, e-commerce, integration-sync
- Set `MITOL_HUBSPOT_API_PRIVATE_TOKEN` to the private app token in your .env file
- In the web container, run `./manage.py sync_db_to_hubspot update` 
- Validate that the task id is being logged
> feat: added task id logs for sync_db_to_hubspot command

- cms/models.py
- cms/models_test.py
- courses/management/commands/sync_external_course_runs.py
- courses/sync_external_courses/emeritus_api.py
- courses/sync_external_courses/emeritus_api_test.py
None
- If ExternalCoursePage is unpublished for Emeritus, the updates do not work as expected. We need to save the revisions in this case.
- If WhoShouldEnroll or LearningOutcomes Page exist and are unpublished, the command does not look by default, this PR makes room to fetch the draft pages.
- Sync Emeritus Course Runs with `./manage.py sync_external_course_runs --vendor emeritus`
- Now unpublish a course page in CMS and remove one of the `external_marketing_url`, `duration`, or `description`.
- Now save the page in Draft
- Run the above command, you won't see the updated data(the one you removed should be added again from the API. The logic is to add the data in case it is missing.)
- Now unpublish WhoShouldEnroll or LearningOutcomes page for one of the Emeritus …
> fix: draft page issues in API ingestion

- cms/forms.py
- cms/models.py
- cms/models_test.py
- cms/wagtail_hooks.py
- ecommerce/models.py
- ecommerce/models_test.py
- ecommerce/wagtail_views.py
- localdev/seed/api.py
https://github.com/mitodl/hq/issues/4851
ProductVersion.description is required for Cybersourse. It was not added for products created via CMS. This PR fixes the issue and also adds a Validation to make sure that description cannot be empty.
- Create a course, course run
- Create a course page through CMS and add a price
- Notice that the created product versions do not have a description
- Now checkout this branch and repeat the steps. The description should be set to CourseRun.courseware_id OR Program.readable_id for the programs.
- Go to the Django shell.
- Try to create a ProductVersion with description with:
- `from ecommerce.models import ProductVersion`
- `ProductVersion.objects.create(product_id=1, price=199)`
- It should raise a validation error
> fix: add productversion description for CMS products and raise error if empty

- courses/sync_external_courses/emeritus_api.py
- courses/sync_external_courses/emeritus_api_test.py
Fix for https://github.com/mitodl/mitxpro/pull/3048
When a course page already exists, we save the revision. It saves the draft revisions and does not publish them. This PR publishes a page revision if it has unpublished changes and the page is live.
Steps to reproduce:
- Check out the master branch.
- Run `./manage.py sync_external_course_runs --vendor emeritus`
- Pick any course and see that it has an external URL, description, and duration.
- Visit the course detail page. All the data should be updated.
- Now go to CMS and change an external course page, i.e. remove duration, external URL, or description. Publish it.
- Now visit the course details and the changes should reflect.
- Now rerun the above command, and you will see that the fields you updated in the above steps are …
> fix(external course sync): publish revision if course is live and has unpublished changes

- courses/sync_external_courses/emeritus_api.py
Fix for https://github.com/mitodl/mitxpro/pull/3048
if a course page is published the first time and then saved as draft. The command `./manage.py sync_external_course_runs --vendor emeritus` will publish it. This PR adds a check for that.
- Run `./manage.py sync_external_course_runs --vendor emeritus`
- Now visit any Emeritus course page in CMS.
- It should be in Live state. You check this in course list.
- Now remove external course URL and publish it. You will see this change in live version as learn more link is hidden now.
- Now change the title of course page and save it as draft.
- Now run the command again.
- It will update the external URL but it will also publish the course page. You will see that the Draft title is visible on live page and external link is …
> fix: do not publish external course if saved as draft

- courseware/factories.py
None
OpenEdxApiAuthFactory sets `access_token_expires_on` to a random time between now and +1 hour. It could generate a random datetime that can expire before we get the object. This PR fixes the factory to get a datetime after 1 day in future.
https://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html#faker.providers.date_time.Provider.date_time_between
https://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html#faker.providers.date_time.Provider.future_datetime
- Checks should pass
> test: fix flaky test

- cms/models.py
None
We optimized the catalog page a few months back. After that we change the course and program architecture for the external courseware. This has added a few extra queries that we can optimize very easily. This PR just does that.
For me, this has reduced the query count from 380s to 20s. The request time is reduced by half.
Before:
After:
- Create a few internal and external courses.
- You can use `./manage.py sync_external_course_runs --vendor emeritus` for external courses.
- Visit catalog page.
- Now check the query count in silk at /silk/requests/
- Now checkout this branch and visit the catalog page.
- Monitor the drop in query count and request time.
> perf: optimize catalog queries for external coursware

- courses/sync_external_courses/emeritus_api.py
- courses/sync_external_courses/emeritus_api_test.py
Closes https://github.com/mitodl/hq/issues/5013
Adds enrollment end date same as the start date for the emeritus courses. For emeritus courses enrollment is closed after the start date. Please go through the related ticket.
- Run `./manage.py sync_external_course_runs --vendor emeritus`. It will create the emeritus courses.
- go to the catalog page and note the Next Start Date
- Now go to the course detail page and see that there is a different date. Start date is in the past.
- For emeritus courses, enrollment is closed after the start date, we should not display such start dates.
- Now checkout this branch.
- Run the above command and verify that the part start dates are not appearing on the Course Detail Page. You can also verify that the `Next Start Date` on Catalog …
> feat: set enrollment end for emeritus courses

- courses/serializers.py
- courses/serializers_test.py
https://github.com/mitodl/hq/issues/4953
Adds the availability field in `/courses` and `/programs` APIs
Currently, We just send a hard-coded value because the calculation of the `anytime` value of availability is not possible in xPRO
- Create a couple of courses and programs
- Shift to this branch
- Check the responses of `/api/courses` and `/api/programs` and they should have an availability field in the response
- Check other APIs are not affected e.g. `/api/products`
> feat: add course and program availability in APIs

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/conftest.py
- ecommerce/tasks.py
- ecommerce/tasks_test.py
Followup for https://github.com/mitodl/mitxpro/pull/3021
We were getting [some errors](https://mit-office-of-digital-learning.sentry.io/issues/5715458782/?project=1413655&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=0) while testing the functionality of [this PR](https://github.com/mitodl/mitxpro/pull/3021) on RC. This PR fixes those errors.
- Validate that the checkout page is working properly
1 In the .env file set the value `BASKET_EXPIRY_DAYS=0` ( warning: this will delete all your baskets )
2 For any course, open the checkout page and don't complete the order. ( You can leave this step if you have existing basket and basket items )
3 Open the mitxpro shell by running `python manage.py shell` in the mitxpro directory
4 …
> fix: fixed basket deletion issue

- courseware/api.py
- courseware/exceptions.py
None
Silently fail if name validation on connection error(Will be helpful for local setups). Also, fixes an issue with the exception msg when the response is None.
- Test that the name is validated against open edX and an appropriate error is raised and displayed to the user.
- Test that registration is successful when ConnectionError is thrown(open edX is down).
> fix: silently fail name validation on connection error

- courses/models.py
- courses/views/v1/__init__.py
None
Improves API performance for courses, programs, and course_runs API.
- Verify the API Data has no changes.
There are still a few N+1 queries in courses and the course runs API due to the CMS Pages like CertificatePage and FacultyMembersPage. We cannot do anything simple to avoid those queries as there are no relational mappings.
> perf: improve API performance

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/mail_api.py
- mail/templates/product_order_receipt/body.html
- mitxpro/utils.py
- mitxpro/utils_test.py
- static/js/containers/pages/ReceiptPage.js
- static/scss/receipt.scss
Closes https://github.com/mitodl/hq/issues/5250
Hides tax details for countries where taxes are not enabled. This includes changes on the Checkout Page, Email Receipt, and Dashboard Receipt Details. It also updates the signature display in the receipt PDF and removes the zendesk help widget text from the receipt.
With Taxes Enabled:
With Taxes Disabled:
Receipt Signatures:
[MIT xPRO _ Receipt.pdf](https://github.com/user-attachments/files/16709938/MIT.xPRO._.Receipt.pdf)
- To test NO Taxes:
- Disable FEATURE_ENABLE_TAXES_DISPLAY in .env, You won't see any taxes in the checkout, receipt email, and dashboard receipt.
- Enabled FEATURE_ENABLE_TAXES_DISPLAY, Add a TaxRate in admin for any other country or your country but disable it. You should not see any taxes as there is no active tax rate …
> feat: display tax details for countries where taxes are enabled

- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- mail/templates/product_order_receipt/body.html
[#4841](https://github.com/mitodl/hq/issues/4841)
This PR uses support email address from configurations(settings) in order receipts template.
- Ensure that your XPro environment is properly configured.
- Perform an enrollment, and you should receive a "Purchase Order Receipt" email with the support email address pulled from the configurations (settings).
> fix: use support email address from configurations(settings)

- package.json
- yarn.lock
This reverts commit 11c79361f30bf36696f0c4cd72613a5ee5de3f02.
No ticket is created.
I've noticed some warnings on the xPro local environment, due to the auto-merged Renovate PR: https://github.com/mitodl/mitxpro/pull/3131.
```
watch-1   | LOG from ./node_modules/sass-loader/dist/cjs.js sass-loader ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/scss/layout.scss
watch-1   | <w> Deprecation Passing percentage units to the global abs() function is deprecated.
watch-1   | <w> In the future, this will emit a CSS abs() function to be resolved by the browser.
watch-1   | <w> To preserve current behavior: math.abs(100%)
watch-1   | <w> To emit a CSS abs() now: abs(#{100%})
watch-1   | <w> More info: …
```
> Revert "fix(deps): update dependency sass to ~1.78.0"

- mitxpro/settings.py
N/A
Django seems to be trying to load `settings.py` more than once now. I'm not exactly sure how/when this changed but it's causing the parsing of environment variables to fail because of an assertion that ensures an environment variable isn't parsed twice. So I've made two changes:
- Reset the parsed environment variables at the top of `settings.py`
- Move the two imports of ol-django settings modules into the `import_settings_modules()` call, which I moved to the top because of some dependencies on values from those earlier in `settings.py`
`docker compose run --rm web ./manage.py migrate` should succeed.
> Don't fail app init if settings.py is reloaded

- cms/models_test.py
- cms/templates/partials/faqs.html
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- mail/templates/product_order_receipt/body.html
- mail/templates/welcome_course_run_enrollment/body.html
- mitxpro/views.py
- voucher/templates/redeemed.html
Following up: https://github.com/mitodl/mitxpro/pull/3127#issuecomment-2358035425
This PR updates all templates to use the support email address from the configuration (settings) instead of hard-coded values.
FAQ page (on course details):
Boeing Redeemed page:
Purchase Order Receipt email:
Welcome Course Run Enrollment email:
- Ensure all templates now use the support email address from the configuration (settings) instead of hard-coded values:
- Check the FAQ page (on course details).
- Verify the support email on the Boeing Redeemed page.
- Confirm the email in the Purchase Order Receipt email.
- Verify the email in the Welcome Course Run Enrollment email.
> fix: support email address from configurations(settings) on all templates

- cms/models.py
- cms/views_test.py
https://mit-office-of-digital-learning.sentry.io/issues/5893848649/?project=1413655&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0&utc=true
Handles sort by tampered URLs. Applies Best Match by default.
- On master branch
- Go to the catalog page
- Apply any sorting.
- Now change the query param `sort-by` in the URL. You will get 500.
- Now checkout this branch
- Repeat the above steps to ensure you do not get the error.
> fix: handle tampered queryparam

- cms/models.py
- cms/views_test.py
- courses/models.py
- courses/views_test.py
- static/js/components/CatalogMenu.js
Closes https://github.com/mitodl/hq/issues/5627
Show homepage topics with courses.
- Associate topics with courses in the CMS course pages.
- Keep a few topics without associating the courses.
- Verify that the homepage shows topics with courses.
- Verify that the topics match the courses dropdown in the header.
> fix: display homepage topics with courses

- cms/models.py
- cms/templates/catalog_page.html
https://github.com/mitodl/hq/issues/5567
Puts the catalog filtering functionality behind the feature flag
When `FEATURE_ENABLE_CATALOG_SORTING=True`
When `FEATURE_ENABLE_CATALOG_SORTING=False` or the flag is not set
- Add `FEATURE_ENABLE_CATALOG_SORTING=True` in  your env file
- Run `docker-compose up` to restart the containers
- Visit `http://localhost:8053/catalog/`. You should see the catalog filter
- Set `FEATURE_ ENABLE_CATALOG_SORTING=False` and restart your containers
- Visit `http://localhost:8053/catalog/`. You should not see the catalog filter
> feat: add catalog filter feature flag

- cms/models.py
https://github.com/mitodl/hq/issues/5567#issuecomment-2385853303
Set the catalog sorting feature flag to True by default
- Remove `FEATURE_ENABLE_CATALOG_SORTING` from your env file if present.
- Run `docker-compose up web -d`
- Visit http://localhost:8053/catalog
- You should see the catalog filter
> fix: changed the default value of sorting featureflag

- ecommerce/views.py
None
While testing the release, I came across this issue that downloading the coupon codes after creation requires staff permission. This PR updates the permission to allow users with the `Add Coupons` permission to download the coupons  csv.
- Give a test user `Can add coupon` permission from the django admin
- Login with the test user account and visit `/ecommerce/admin`
- Create new coupons in the `Coupon Codes` tab
- On success page, click the `Download coupon codes` link
- A CSV file should be downloaded successfully
> fix: coupon code download view permissions

- README.md
- courseware/api.py
- localdev/seed/api.py
- mitxpro/management/commands/configure_instance.py
fixes https://github.com/mitodl/hq/issues/5772
- Add a `configure_instance` management command to partially automate the MITxPro configuration process
- Create superuser
- Create Application entry for OAuth Provider
- Configures wagtail by running `configure_wagtail` management command
- **Syntax**
- `configure_instance <platform> [--dont-create-superuser|-S] [--edx-oauth-client <client id>] [--edx-oauth-secret <client secret>] [--gateway <ip>] [--tutor|-T] [--tutor-dev]`
- **Options**
-  `<platform>` - One of macos, linux, or none. Specifying none will additionally stop creation of the OAuth2 application record for edX. Defaults to none.
- `--dont-create-superuser|-S` - Don't create a superuser account.
- `--gateway <ip>` - The Docker gateway IP. Required on Linux.
- Linux users: The …
> Add a `configure_instance` management command

- courses/sync_external_courses/emeritus_api.py
- courses/sync_external_courses/emeritus_api_test.py
Fixes https://github.com/mitodl/hq/issues/5991
Strip the Emeritus course titles to avoid trailing spaces in the course titles.
- Not sure if there is any bad data in the API. You can test the changes manually.
> fix: strip emeritus course title during sync

- package.json
- renovate.json
- yarn.lock
> Revert "fix(deps): update dependency sass to ~1.81.0"

- courses/serializers.py
- courses/serializers_test.py
New field prerequisites added in courses and programs API for MIT Learn
closes: https://github.com/mitodl/hq/issues/5752
New field prerequisites added in courses and programs API
1. Check courses and program APIs
a. /api/programs/
b. /api/courses/
2. `prerequisites` field should be in the response
Example response:
```
[
{
"id": 2,
"title": "SEED Architecture of Complex Systems",
"description": "<p>Course 1 of 4 that comprises the Architecture and Systems Engineering Professional Certificate Program.</p>",
"url": "http://localhost/courses/course-v1:xPRO+SysEngxB1/",
"external_marketing_url": null,
"marketing_hubspot_form_id": "",
"thumbnail_url": "http://xpro.odl.local:8053/static/images/mit-dome.png",
"readable_id": "course-v1:xPRO+SysEngxB1",
"courseruns": [],
"next_run_id": null, …
```
> feat(api): prerequisites field added in courses and programs API

- courses/urls.py
- courses/views/v1/__init__.py
- courses/views_test.py
Closes https://github.com/mitodl/mitxpro/issues/3328
Adds an API to list the Emeritus Course data.
- Test that the new API view returns the data at `api/emeritus_courses/`
> feat: add emeritus api list view

- courses/admin.py
https://github.com/mitodl/hq/issues/6330
This PR makes the course key searchable in CourseRun Admin
1. Go to xpro admin `/admin`
2. Add entry for `courseRun` `/admin/courses/courserun/add/`
3. click on course filed drop drown and search course
> feat: make course searchable in courseRun admin

- scripts/test/js_test.sh
JS tests were not running locally and throwing error:
```
Exception during run: SyntaxError[ @/src/static/js/components/B2BPurchaseSummary_test.js ]: Unexpected token '<'
```
The tests were failing to run locally and were throwing the error mentioned above. After investigation, it was identified that the issue began following the merge of the Node.js upgrade PR ([#3244](https://github.com/mitodl/mitxpro/pull/3244)), which upgraded Node.js to version 22.11.0. The root cause of the issue was the `--experimental-detect-module` flag, which is enabled by default starting from Node.js v22.7.0 ([Reference](https://nodejs.org/en/blog/release/v22.7.0#2024-08-22-version-2270-current-rafaelgss)).
This PR resolves the issue by explicitly disabling the `--experimental-detect-module` flag, ensuring …
> fix: npm tests locally

- .github/workflows/ci.yml
- docker-compose.yml
- package.json
- scripts/test/js_test.sh
None
This PR pins node version to 20.18.0 in both CI and docker image
Tests should pass locally and in CI
> revert: node version

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- mail/templates/product_order_receipt/body.html
- mitxpro/features.py
- mitxpro/utils.py
- mitxpro/utils_test.py
- static/js/components/forms/CheckoutForm.js
- static/js/components/forms/CheckoutForm_test.js
- static/js/flow/declarations.js
Closes https://github.com/mitodl/hq/issues/6369
Removes ENABLE_TAXES_DISPLAY feature flag.
- Enable ECOMMERCE_FORCE_PROFILE_COUNTRY and add TaxRate for your profile country in the admin.
- Checkout any product and see that taxes are displayed and applied at the checkout, email receipt and dashboard receipt.
- Now disable the tax rate and see that taxes are not visible.
> refactor: remove ENABLE_TAXES_DISPLAY feature flag

- cms/models.py
- cms/templates/catalog_page.html
Closes https://github.com/mitodl/hq/issues/6365
Removes ENABLE_CATALOG_SORTING feature flag.
- Catalog sorting dropdown should be visible and should work without a feature flag.
> refactor: remove ENABLE_CATALOG_SORTING

- cms/models.py
- cms/models_test.py
- cms/templates/home_page.html
- mitxpro/utils.py
- mitxpro/utils_test.py
- static/js/components/TopAppBar.js
- static/js/components/TopAppBar_test.js
- static/js/flow/declarations.js
Closes https://github.com/mitodl/hq/issues/6366 & https://github.com/mitodl/hq/issues/6367
Removes the ENABLE_BLOG, and WEBINARS feature flags as it has been active for some time now.
Check out this branch. The blog and webinar links in the header should work. The links should not depend on any flag.
> refactor: remove ENABLE_BLOG & WEBINARS feature flags

- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- mitxpro/features.py
Closes https://github.com/mitodl/hq/issues/6371
Migrates FEATURE_ENROLLMENT_WELCOME_EMAIL to posthog as `enrollment_welcome_email`.
- Checks should pass
- Configure posthog by following https://github.com/mitodl/mitxpro/pull/3207. I used my personal posthog account and keys.
- Create a flag in PostHog named `enrollment_welcome_email`
- Go to shell and run:
```
from ecommerce.mail_api import send_course_run_enrollment_welcome_email
from courses.models import CourseRunEnrollment
e = CourseRunEnrollment.objects.last()
send_course_run_enrollment_welcome_email(e)
```
- It should send an email. Now set the flag to false and it shouldn't send email. NOTE: Due to caching to flag values, you might have to restart you containers.
> refactor: migrate FEATURE_ENROLLMENT_WELCOME_EMAIL to posthog

- mitxpro/features.py
- mitxpro/utils.py
- mitxpro/utils_test.py
Closes https://github.com/mitodl/hq/issues/6373
Migrates ENABLE_ENTERPRISE to Posthog
- Set up Posthog by following https://github.com/mitodl/mitxpro/pull/3207. I used my personal posthog account and keys.
- Create a flag in Posthog named enable_enterprise in Posthog and set to True
- Visit the xpro and you should see enterprise link in the header.
> refactor: migrate ENABLE_ENTERPRISE to posthog

- mitxpro/features.py
- mitxpro/utils.py
- mitxpro/utils_test.py
Closes https://github.com/mitodl/hq/issues/6372
Migrates DIGITAL_CREDENTIALS flag to Posthog
- Set up Posthog by following https://github.com/mitodl/mitxpro/pull/3207. I used my personal posthog account and keys.
- Create a flag in Posthog named `digital_credentials`
- Enroll in a course run locally and create a certificate
- Create a certificate CMS page and then a certificate object in admin.
- Add course run id to DIGITAL_CREDENTIALS_SUPPORTED_RUNS in settings list
- Go to the dashboard and you should see `View Certificate` and `Digital Credential` links against the enrollment.
> refactor: migrate DIGITAL_CREDENTIALS flag to posthog

- Dockerfile
- apt.txt
- poetry.toml
https://github.com/mitodl/ol-django/pull/175
This PR adds `lxml` and `xmlsec` in no-binary config
> Install lxml and xmlsec without binary

- mitxpro/settings.py
None
We have completely switched to using the new `ol-social-auth `package for authentication with edX in all of our environments. This PR changes the default backend in mitxpro from `mitxpro-oauth2` to `ol-oauth2`
> config: changed default backend to ol-oauth

- courses/tasks.py
- courses/tasks_test.py
[#6813](https://github.com/mitodl/hq/issues/6813)
This PR enhances filtering on which course runs are to be synced sync_courseruns_data celery task. Any course run whose corresponding course isn't live shouldn't sync.
1. Checkout this branch
2. In your edX studio, make sure you have a course that can be synced
3. Create a corresponding course in xPRO
- Set `live=False` for this course
- Ensure at least one **course run** under this course is active (`live=True`)
5. Run the celery task to sync courses:  
```python
docker-compose exec celery ./manage.py shell
from courses.tasks import sync_courseruns_data
sync_courseruns_data.delay()
```
7. Verify the course did not sync because the parent course in xPRO is inactive (is_live=False).
> fix: non-live courses shouldn't sync

- courses/sync_external_courses/external_course_sync_api.py
- courses/sync_external_courses/external_course_sync_api_test.py
Follow-up PR of https://github.com/mitodl/mitxpro/pull/3386
While testing, it came into notice that the `updated_on` field is not updated for external course runs which are deactivated, due to [bulk_update](https://github.com/mitodl/mitxpro/pull/3386/files#diff-2ced998483e8958644e8ae749e2055bae58b599e2c37a4507e7013f21834c45bR867). This PR fixes this issue
- Follow the testing instructions in https://github.com/mitodl/mitxpro/pull/3386
- Validate that the updated_on field is updated properly
> fix: course run updated_on updation when deactivating external course run

- courses/tasks.py
- courses/tasks_test.py
[#6813](https://github.com/mitodl/hq/issues/6813)
This PR enhances filtering on which course runs are to be used when we run generate_course_certificates celery task. Course runs for external courses don't need to get grades from edx to generate certificates.
1. Checkout this branch
2. Create an external course in xPRO with any platform of your choice
- Set `external=True` for this course
- Create at least one corresponding **course run** for this course
3. Run the celery task to sync courses:  
```python
docker-compose exec celery ./manage.py shell
from courses.tasks import generate_course_certificates
generate_course_certificates.delay()
```
4. Verify the course run did not sync because the parent course in xPRO is external (external=True).
> fix: check for non-external courses before generating edx certificates

- courseware/api.py
- courseware/api_test.py
[#6813](https://github.com/mitodl/hq/issues/6813)
This PR enhances filtering on which course runs are to be used when we run retry_failed_edx_enrollments celery task. Enrollments based on inactive course runs should not be retried.
1. Checkout this branch
2. In your edX studio, make sure you have a course that can be synced
3. Create a corresponding course run in xPRO with `live=True`
4. Enroll a user in this course run (should be successfully enrolled)
5. In xPRO admin, set `edx_enrolled` for this enrollment to False
6. Set `live=False` on the course run created above
7. Run the celery task to sync courses:  
```python
docker-compose exec celery ./manage.py shell
from courseware.tasks import retry_failed_edx_enrollments
retry_failed_edx_enrollments.delay()
```
8. Verify this particular …
> feat: check for live courses for failed edx enrollments

- .secrets.baseline
- ecommerce/views.py
- ecommerce/views_test.py
- sheets/constants.py
- sheets/exceptions.py
- sheets/management/commands/process_coupon_assignment_sheet.py
- sheets/management/utils.py
- sheets/management/utils_test.py
- sheets/permissions.py
- sheets/urls.py
- sheets/utils.py
- sheets/utils_test.py
- sheets/views.py
- sheets/views_test.py
- static/js/components/forms/CouponSheetProcessForm.js
- static/js/components/forms/CouponSheetProcessForm_test.js
- static/js/constants.js
- static/js/containers/pages/admin/DeactivateCouponPage.js
- static/js/containers/pages/admin/EcommerceAdminPages.js
- static/js/containers/pages/admin/ProcessCouponAssignmentSheetPage.js
- static/js/containers/pages/admin/ProcessCouponAssignmentSheetPage_test.js
- static/js/containers/pages/admin/ProcessCouponAssignmentSheet_test.js
- static/js/lib/queries/ecommerce.js
- static/js/lib/urls.js
- static/scss/ecommerce-admin.scss
- static/scss/variables.scss
https://github.com/mitodl/hq/issues/6582
This PR adds the interface for processing product coupon assignment sheets in `ecommerce admin`. The UI will only be accessible to people having permissions to add and update [ProductCouponAssignment](https://github.com/mitodl/mitxpro/blob/b358a1b21b9c53804f2b5cd589705667509684a2/ecommerce/models.py#L840) model.
at 5 00 01 PM" src="https://github.com/user-attachments/assets/f9768519-864f-41c5-b40f-ae496582a6ed" />
- Create some test coupons on http://localhost:8053/ecommerce/admin/coupons/. Make sure you select only **one product** at the time of coupon creation to automatically create [CouponEligibility](https://github.com/mitodl/mitxpro/blob/b358a1b21b9c53804f2b5cd589705667509684a2/ecommerce/models.py#L710) object which is required for processing …
>  feat: added interaface for processing product coupon assignment sheets

- ecommerce/mail_api.py
[#6938](https://github.com/mitodl/hq/issues/6938)
This PR fixes a bug in `send_course_run_enrollment_welcome_email` where the function would throw a [Course.coursepage.RelatedObjectDoesNotExist](https://mit-office-of-digital-learning.sentry.io/issues/6575858732/?project=1413655&query=coursepage&referrer=issue-stream&sort=freq&stream_index=0) exception when trying to access `max_weeks` for courses that don't have an associated coursepage.
Changes made:
- Replaced the direct attribute access `enrollment.run.course.coursepage.max_weeks` with a safe getattr() chain
- When coursepage doesn't exist or doesn't have `max_weeks`, `run_duration` is now set to None instead of throwing an exception and a welcome email without duration is sent
1. Checkout this branch and make sure you have EdX, xPRO, …
> fix: check for coursepage before getting max_weeks

- cms/models.py
- cms/models_test.py
- cms/templates/catalog_page.html
- cms/views_test.py
- courses/api.py
- mitxpro/features.py
[#7122](https://github.com/mitodl/hq/issues/7112)
This PR removes the `CATALOG_LANGUAGE_FILTER` feature flag, making the language filter a permanent feature in the catalog. The feature flag was initially added in [#3384](https://github.com/mitodl/mitxpro/pull/3384) when the language filter was first implemented, allowing us to potentially revert to the previous UI if needed. After several months of successful use, we have gained confidence in the language filter functionality and are now removing the conditional behavior.
Changes include:
- Removing the CATALOG_LANGUAGE_FILTER feature flag check from the views and templates
- Updating the corresponding HTML to always show the language filter dropdown
- Updating tests to reflect the permanent language filter feature
- Removing the feature …
> chore: remove catalog language filter feature flag

- docker-compose.yml
- mitxpro/settings.py
Fixes the social auth issue of not creating `OpenEdxApiAuth` with tutor
This PR resolves an issue where social auth fails to create an `OpenEdxApiAuth` record when using Tutor.
Through investigation, I discovered that Tutor only preserves login sessions for requests coming from the `local.openedx.io` domain. If you attempt to log in from `localhost:8000`, authentication appears successful (no errors in the logs), but navigating to the dashboard reveals that the user is not actually logged in. The same issue occurs when requests originate from host.docker.internal.
During the `OpenEdxApiAuth` creation flow, the request is sent to edX with a session cookie, but the server treats it as anonymous and redirects to the login page rather than the intended redirect_uri.
To fix this, the PR maps …
> fix: use host-gateway for local.openedx.io to fix Open edX API auth creation

- ecommerce/permissions.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/urls.py
- ecommerce/views.py
- ecommerce/views_test.py
- static/js/components/ConfirmUpdateModal.js
- static/js/components/ConfirmUpdateModal_test.js
- static/js/components/forms/CouponForm.js
- static/js/components/forms/PromoCouponUpdateForm.js
- static/js/components/forms/PromoCouponUpdateForm_test.js
- static/js/constants.js
- static/js/containers/pages/admin/DeactivateCouponPage.js
- static/js/containers/pages/admin/DeactivateCouponPage_test.js
- static/js/containers/pages/admin/EcommerceAdminPages.js
- static/js/containers/pages/admin/UpdatePromoCouponPage.js
- static/js/containers/pages/admin/UpdatePromoCouponPage_test.js
- static/js/flow/ecommerceTypes.js
- static/js/lib/queries/ecommerce.js
- static/js/lib/urls.js
- static/js/lib/util.js
- static/js/lib/util_test.js
https://github.com/mitodl/hq/issues/7310
This PR adds the `Update Promo Code` option in the e-commerce admin. Users are required to have `ecommerce | coupon | Can change coupon` permission to access this feature
https://github.com/user-attachments/assets/75c91ca5-712e-4a13-98f4-94fef9943644
- Create some promo coupons from [`http://localhost:8053/ecommerce/admin/coupons/`](http://localhost:8053/ecommerce/admin/coupons/)
- From django admin, grant user `ecommerce | coupon | Can change coupon` permission.
- Visit [http://localhost:8053/ecommerce/admin](http://localhost:8053/ecommerce/admin). `Update Promo Coupon` button should start appearing. Click the button.
- On the `Update Promo Coupon` page, select a Promo Coupon to update.
- Change the activation, expiration dates, and products, and …
> feat: add update promo coupons self service

- app.json
- mitxpro/context_processors.py
- mitxpro/settings.py
- mitxpro/templates/base.html
- mitxpro/utils.py
- mitxpro/utils_test.py
- package.json
- static/js/components/forms/CheckoutForm_test.js
- static/js/containers/pages/CheckoutPage_test.js
- static/js/entry/root.js
- static/js/flow/declarations.js
- yarn.lock
[#7504](https://github.com/mitodl/hq/issues/7504)
This PR removes the Zendesk help widget (chatbot) functionality from the MIT xPRO website to comply with upcoming Zendesk contract changes.
- Changes Made:
- Removed React component integration (react-zendesk)
- Removed Django settings and context processors for Zendesk widget
- Removed template script loading and meta tags
- Removed package dependencies and environment variables
- Updated test files to remove Zendesk config references
The chatbot widget has been completely removed. Note that direct Zendesk support links in emails, footers, and other components remain unchanged as they are separate from the chatbot functionality.
1. Verify widget is gone: Load any page on the site and confirm the Zendesk chat widget no longer appears
2. …
> chore: remove zendesk chatbot widget and related components

- poetry.lock
- pyproject.toml
https://github.com/mitodl/mitxpro/security/dependabot/204
This PR upgrade the package `mitol-django-authentication` to `2025.2.12`
**NOTE**: This upgrade eventually upgrades `djoser` from 2.2.2 to 2.3.1 for security concerns
1. Rebuild the docker or run `poetry install` command in the web container
2. Verify registration and login flow is working as expected
> Upgrade mitol-django-authentication

- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/views.py
- ecommerce/views_test.py
https://github.com/mitodl/hq/issues/7310
This PR fixes the N+1 query issues in the update promo coupon feature to improve the performance.
- On the master branch, open http://localhost:8053/ecommerce/admin/update-promo-code/.
- Check the web container logs; you should see N+1 query warnings.
- Visit http://localhost:8053/silk/requests/ and inspect the query count for the /api/promo_coupons/ request.
- Switch to this branch and reload the [update promo code](http://localhost:8053/ecommerce/admin/update-promo-code/) page.
- You should no longer see any N+1 query warnings in the logs.
- The number of queries for the /api/promo_coupons/ endpoint should also be reduced.
> perf: improved update promo coupon performance by fixing N+1 issues

- package.json
- yarn.lock
[#3589](https://github.com/mitodl/mitxpro/pull/3589)
This PR removes the `serialize-javascript` package from our package.json and project dependencies. After a thorough search, it was confirmed that this package is not imported or used anywhere in our codebase.
- Run the application and ensure all JS builds and runs as expected.
- Confirm that serialize-javascript is no longer listed in the top-level dependencies.
> chore: remove seralize-javascript

- courses/models.py
https://github.com/mitodl/hq/issues/8197
This PR updates the condition of `is_external` in the course to allow updation of this field for bad course data.
- Checkout to master branch.
- Create a test course from django admin with `is_external=True`.
- Comment [these lines](https://github.com/mitodl/mitxpro/blob/master/cms/forms.py#L62-L66) from the code.
- Create a Course Page from CMS for the course created above.
- Change the course is_external to False and save, you will see a Validation error.
- Now checkout to this branch try to save again. This time, the course will be saved without any issues.
> fix: condition of is_external attribute change in course

- courses/constants.py
- courses/utils.py
- courses/utils_test.py
[#7160](https://github.com/mitodl/hq/issues/7160)
edX API rejects malformed course keys with 400 errors. Many courses in xPRO have invalid courseware IDs that don't follow the required format `course-v1:ORGANIZATION+COURSE_ID+RUN_ID`. This PR adds the validation to filter out malformed course keys before making API calls, preventing 400 errors and allowing the sync to continue with valid courses.
1. Add a course with an invalid course key via django-admin e.g. `course-v1:NotMITx-0.000x-4T2029`
2. Run management command: Execute `python manage.py sync_courseruns` to test bulk sync functionality
- Verify all valid course keys are sent to edX and some courses are updated 
- Verify invalid course keys are logged for identification
3. Check Celery task: Trigger the `sync_courseruns_data` task …
> fix: add course key validation and invalid course tracking

- courses/utils.py
- courses/utils_test.py
[#7160](https://github.com/mitodl/hq/issues/7160)
Course List API was returning empty results in RC, causing sync to show "No data received for requested courses" warnings for valid courses. This was because Courselist API requires username parameter for course access permissions.
This PR adds `username=settings.OPENEDX_SERVICE_WORKER_USERNAME` to the `get_courses()` call.
Note: This was working locally because the local edX instance had different API configuration/permissions than RC.
1. Run management command: Execute `python manage.py sync_courseruns` to test bulk sync functionality
2. Test specific course: Run `python manage.py sync_courseruns --run <courseware_id>` to test single course sync
3. Check Celery task: Trigger the `sync_courseruns_data` task and verify it uses bulk sync
4. …
> fix: pass service worker for course sync

- .yarnrc.yml
_This PR was generated automatically via a script._
This PR disables yarn's postinstall scripts by setting `enableScripts: false` in `.yarnrc.yml`. It is part of:
- https://github.com/mitodl/hq/issues/8676
Disabling postinstall scripts improves security by:
- **Preventing malicious code execution**: Stops potentially harmful scripts from running during package installation
- **Supply chain security**: Reduces risk from compromised packages that could execute malicious postinstall scripts
- **Controlled execution**: Allows manual review and execution of necessary scripts only when needed
- Added `enableScripts: false` to `.yarnrc.yml`
- Some packages may require manual script execution if they depend on postinstall hooks
- Improved security posture against supply chain attacks
- No …
> Security: Disable yarn postinstall scripts
