mitodl/mitxpro

docs/rfcs/0002-storing-course-data.md
[Rendered](https://github.com/mitodl/mitxpro/blob/b3896453565737cf74faf11544915d001308fce3/docs/rfcs/0002-storing-course-data.md)
This adds an RFC for storing program/course data and keeping it up to date
=> Added RFC for storing course data

courses/apps.py
Added missing files to make 'courses' a proper Django app
=> Fixed courses django app

docs/rfcs/0003-openedx-auth-integration.md
[Rendered](https://github.com/mitodl/mitxpro/blob/rfc/0001-openedx-oauth2-provider/docs/rfcs/0001-openedx-auth-integration.md)
This adds an RFC for MIT xPro -> Open edX authentication.
=> Added RFC for Open edX auth integration

docs/rfcs/0004-bot-friendly-front-end.md
[Rendered](https://github.com/mitodl/mitxpro/blob/b30e5007729a46b057eade6226571cd91fbb5727/docs/rfcs/0004-bot-friendly-front-end.md)
#1 
https://github.com/mitodl/open-discussions/issues/1801
https://github.com/mitodl/open-discussions/issues/1879
This RFC lays out some options for addressing the problem of rendering meaningful content for bots (the Facebook crawler in particular)
=> RFC: Bot-friendly front-end

courseware/apps.py, mitxpro/settings.py
No ticket - this will support some different issues we're working on that involve interactions w/ Open edX
Adds the `courseware` Django app, which will contain logic/models for communicating with courseware platforms
=> Added courseware Django app

docker-compose.travis.yml, mitxpro/settings.py, package.json, static/js/components/Header.js, static/js/components/Header_test.js, static/js/components/forms/register.js, static/js/components/forms/register_test.js, static/js/containers/App.js, static/js/containers/pages/LoginPage.js, static/js/containers/pages/register/RegisterConfirmPage.js, static/js/containers/pages/register/RegisterEmailPage.js, static/js/containers/pages/register/RegisterPages.js, static/js/containers/pages/register/RegisterProfilePage.js, static/js/flow/authTypes.js, static/js/lib/api.js, static/js/lib/queries/auth.js, static/js/lib/queries/auth_test.js, static/js/lib/sanctuary.js, static/js/lib/sanctuary_test.js, static/js/lib/selectors.js, static/js/lib/selectors_test.js, static/js/lib/test_utils.js, static/js/lib/urls.js, static/js/store/configureStore.js, yarn.lock
Closes #3
Adds the register pages and integrates with the backend
Go to /signup and complete the registration process, you should be signed in and redirected to "/"
@pdpinch
=> Added registration flow

mitxpro/settings.py
Fixes #83 
Corrects the url in settings
Hijack a user and release them, you should be redirect to the user list in django-admin
=> Fixed hijack release redirect url

docs/rfcs/0005-ecommerce-rest-api.md
Part of #75 
This describes some of the REST APIs which will be implemented for ecommerce.
=> RFC for ecommerce REST APIs

authentication/exceptions.py, authentication/pipeline/user.py, authentication/pipeline/user_test.py, mitxpro/settings.py
Closes #85 
Combines auth pipeline steps for creating a user and for setting the password and name for that user
Use the signup flow and make sure you can't create a user without a password and name
=> Combined auth steps for creating user and setting pw, name

app.json
N/A
Fixes app.json not being valid json
PR build shouldn't error with app.json error
=> Fix app.json validity

static/js/containers/pages/LoginPage.js
N/A
Fixes the broken login page byt using the transformed result
Got to /login and you should be prompted for a password instead of hitting an error.
(Optional)
(Optional)
(Optional)
(Optional)
=> Fixed binding error

courses/models.py, courses/models_test.py, ecommerce/admin.py, ecommerce/api_test.py, ecommerce/conftest.py, ecommerce/serializers.py, ecommerce/serializers_test.py, ecommerce/urls.py, ecommerce/views.py, ecommerce/views_test.py, mitxpro/urls.py, mitxpro/utils.py
Closes #71 
Adds a view for updating, validating, and clearing product items and coupons in a user's basket.
Unit tests should pass.
=> Basket REST API

ecommerce/serializers.py, ecommerce/serializers_test.py, ecommerce/views.py, ecommerce/views_test.py, mitxpro/urls.py
Part of #108 
Fixes a couple things with basket API:
- thumbnail added to product listing
- baskets are now created if they don't already exist
N/A
=> Add thumbnail to basket API, use get_or_create for Basket

static/js/lib/urls.js
N/A
Fixes a regression in register url routing
Complete a registration
=> Switched routes back to "details"

mitxpro/tests/app_tests.py
N/A
Adds a test to ensure app.json is parsable and has certain keys, this will avoid a recurring issue where we don't catch this because heroku only executes it for new apps
=> Added a test to verify app.json

travis/js_tests.sh, travis/python_tests.sh
No ticket 
Just fixes the ANSI colors for the travis output introduced in #202 (I reviewed the output on my machine and forgot to check how it looked in the travis log)
=> Updated travis script section ANSI colors

docker-compose.yml
**What are the relevant tickets?**
NA
**What's this PR do?**
fix BdbQuit exception while using pdb locally.
**How should this be manually tested?**
Put `import pdb; pdb.set_trace()` in code and run `docker attach mitxpro_web_1` to debug code.
=> update docker compose for local debugging

Aptfile, Dockerfile, app.json, apt.txt, mitxpro/settings.py, requirements.in, runtime.txt
N/A
Hopefully fixes the heroku build by moving deps into apt.txt
Verify that heroku builds correctly (assuming there isn't another config issue breaking PR apps)
=> Move deps into apt.txt so heroku installs them too

cms/migrations/0014_termsofservicespage.py
N/A Fixing broken migrations.
Build should pass.
=> Fix migration dependency

mitxpro/context_processors.py, mitxpro/settings.py, mitxpro/templates/base.html, mitxpro/templates/partials/gtm_body.html, mitxpro/templates/partials/gtm_head.html
Fixes #63 
Add google analytics code to base.html
- Add `GA_TRACKING_ID` in .env. I am using `GTM-KG4FR7J` provided in issue detail.
- Visit any CMS page with opened network tab.
- You should request something like `https://www.google-analytics.com/r/collect?....`
=> add google analytics

static/js/containers/pages/CheckoutPage.js, static/js/containers/pages/CheckoutPage_test.js, static/js/lib/ecommerce.js, static/js/lib/ecommerce_test.js, static/scss/checkout.scss
Fixes #215 
Updates checkout page styling for desktop and mobile views (see screenshots)
Everything should look fine at all page widths. Compare with the mockups:
Desktop mockup:
https://invis.io/WDRNN8N2BT8#/360115707_Checkout_Page_W_Programs
Mobile mockup:
https://projects.invisionapp.com/share/5DRXZCK6PF3#/screens/362532387
Desktop:
Mobile:
=> Styling for checkout page

static/js/components/TopAppBar.js, static/scss/top-app-bar.scss
#294 
Fixes the issue with header links disappearing
Go to any page, the header should appear with links on the right
Catalog page was build using bootstrap 3 whereas other pages were already implemented on BS4. This resulted in some of the pages/sections not working properly. The catalog page was subsequently updated however it was overlooked that the same PR had updated the header structure to BS3 as well. This PR updates the header structure to BS4 compatible as well.
=> #294 Fix Header Navbar Structure

Dockerfile-nb
No ticket
See title
Build the notebook (`docker-compose -f docker-compose-notebook.yml build`) and run it ([README](docker-compose -f docker-compose-notebook.yml build))
At some point we got rid of the `python` service in docker-compose. This Dockerfile wasn't updated at that time to point at the `web` service in its place
=> Updated notebook Dockerfile to be based off correct image

Procfile
N/A
Enables the workers to use pgbouncer
N/A, will verify in environments
=> Added workers to pgbouncer

courses/templates/partials/hero.html, static/js/hero.js
#257 
The action button in header on home page (Watch Video) should scroll to "About MIT xPRO" section and play the video if it is available.
Add a `TextVideoSection` to the HomePage and set up a correct HLS video url for the subpage. Click on the "Watch Video" button in hero section on the home page and it should scroll to and play the video in that section.
=> #257: Home Page: Watch Video Button

static/scss/layout.scss
issue #374 
@gsidebo can you take a look now ?
=> asadiqbal08/mitxpro-374 Fix footer placement

mitxpro/templates/footer.html
=> asadiqbal08/mitxpro-386 fix TOS link in footer 

README.md
Closes #383 
Adds instructions to setup the home page.
=> #383 Add Home Page Instructions to Readme

cms/templates/home_page.html
=> asadiqbal08/mitxpro-381 Integrate HubSpot in HomePage

requirements.in, requirements.txt
N/A
Periodic bump of dependency
App should run and still be functional
=> Bumped drf version

.github/ISSUE_TEMPLATE/bug_template.md, .github/ISSUE_TEMPLATE/config_change_template.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
N/A
Adds an issue template for a config change request to devops and a corresponding checkbox on the PR template to ensure it gets created.
N/A
=> Added template for config change request and PR checkbox

mitxpro/urls.py, mitxpro/views.py, static/js/components/forms/ChangePasswordForm.js, static/js/components/forms/EmailForm.js, static/js/components/forms/LoginPasswordForm.js, static/js/components/forms/ProfileFormFields.js, static/js/components/forms/RegisterEmailForm.js, static/js/containers/pages/login/LoginForgotPasswordConfirmPage.js, static/js/containers/pages/login/LoginForgotPasswordConfirmPage_test.js, static/js/containers/pages/login/LoginForgotPasswordPage.js, static/js/containers/pages/login/LoginForgotPasswordPage_test.js, static/js/containers/pages/login/LoginPages.js, static/js/containers/pages/register/RegisterEmailPage.js, static/js/lib/form.js, static/js/lib/queries/auth.js, static/js/lib/urls.js, static/js/lib/validation.js, static/js/lib/validation_test.js, static/scss/common.scss
Closes #356  
Adds the forgot password UI
Go to /login, enter an email, then click "Forgot Password" and verify that completing the forgot password flow changes your password.
In order of user flow:
<details>
<summary>Forgot Password link on password form</summary>
</details>
<details>
<summary>Forgot Password form </summary>
</details>
<details>
<summary>Notification that email was sent</summary>
</details>
<details>
<summary>Forgot Password email</summary>
</details>
<details>
<summary>Change password form</summary>
</details>
<details>
<summary>Password changed notification</summary>
</details>
=> Forgot Password UI

app.json, cms/templates/catalog_page.html, cms/templates/home_page.html, cms/templates/product_page.html, courses/templates/subscription.html, mitxpro/context_processors.py, mitxpro/templates/footer.html, mitxpro/views.py, mitxpro/views_test.py, static/js/components/TopAppBar.js, static/js/containers/pages/profile/ViewProfilePage.js, static/js/containers/pages/register/RegisterDetailsPage.js, static/js/containers/pages/register/RegisterExtraDetailsPage.js, static/js/flow/declarations.js, voucher/templates/enroll.html, voucher/templates/redeemed.html, voucher/templates/resubmit.html, voucher/templates/upload.html
Fixes #467 
Use site name in registration flow for consistency.
Go through the registration process.
Hardcoded site name in emails should fix in #487
=> Fix site  MIT xPRO name everywhere

cms/templates/partials/catalog-card.html
=> asadiqbal08/mitxpro-465 Replace cost with price.

ecommerce/api.py, ecommerce/api_test.py, ecommerce/serializers.py, ecommerce/views_test.py, static/js/components/forms/CheckoutForm.js, static/js/components/forms/CheckoutForm_test.js, static/js/constants.js, static/js/containers/pages/CheckoutPage.js, static/js/containers/pages/CheckoutPage_test.js, static/js/flow/ecommerceTypes.js, static/js/lib/form.js, static/js/lib/form_test.js, static/scss/checkout.scss
Part of #216 
Refactors the checkout page to use Formik
Everything should work the same as before
=> Refactor checkout page to use formik

cms/models.py, cms/templates/partials/hero.html, courses/views_test.py
Fixes #340
Adds a enroll/view dashboard button to the program page.
View the program page. If you are logged in you should see either an enroll button or, if you already purchased a program bundle, a view dashboard button. If you are not logged in you should not see a button (to be changed in #441 )
Anonymous
Enroll
View dashboard
=> Add enroll/view dashboard button on program page

static/scss/catalog/body.scss
=> asadiqbal08-449Update the Multi/Single style text on catalog page

cms/templates/partials/course-carousel.html, static/scss/detail/courses-in-program.scss
=> asadiqbal08/mitxpro-451 Standardize button text

static/scss/detail/faculty.scss, static/scss/variables.scss
Closes #450 
Changes colors on faculty carousel to match updated design.
=> #450 Change yellow color because of accessibility

cms/models.py
####What are the relevant tickets?
Fixes #503 
Add live filter to CMS page and subpages.
- Try creating subpage as draft and unpublished state.
- You should not see them on user facing site.
=> add live filter to subpages of home and product and resource pages

mitxpro/templates/footer.html
=> asadiqbal08/mitxpro-Change ZenDesk link

ecommerce/serializers.py, ecommerce/serializers_test.py, package.json, static/js/components/Markdown.js, static/js/components/Markdown_test.js, static/js/components/forms/CheckoutForm.js, static/js/components/forms/CheckoutForm_test.js, static/js/containers/pages/CheckoutPage.js, static/js/containers/pages/CheckoutPage_test.js, static/js/factories/ecommerce.js, static/js/flow/ecommerceTypes.js, static/scss/checkout.scss, yarn.lock
Fixes #216 
Adds a data consent checkbox and UI to view the data consent agreement. The checkbox should not be visible if the data consent agreement coupon has not been applied. If the checkbox exists but is false, a validation error should tell the user to check it.
- Create a coupon which is attached to a company using the form at `/ecommerce/admin/coupons/`. Make it apply to some valid purchasable target.
- Check out with the same product. You should not see a data consent agreement checkbox.
- Apply the coupon at checkout. You should see the data consent agreement checkbox soon after.
- Submit the page without checking the box. You should see a validation error.
- Click the checkbox and submit the page. You should be redirected to Cybersource (or back to `/dashboard/` for a 100% off …
=> Data consent checkbox

static/js/containers/pages/DashboardPage.js, static/scss/dashboard.scss
=> asadiqbal08/mitxpro-453 Align dashboard text

static/js/components/TopAppBar.js, static/scss/top-app-bar.scss
Task: #380 
See different links in screenshots bottom.
=> asadiqbal08-mitxpro-380 Link MIT logo in header to web.mit.edu

mitxpro/urls.py, static/js/components/forms/CheckoutForm.js, static/js/components/forms/CheckoutForm_test.js, static/scss/checkout.scss
Fixes #387 
Adds links below the submit button on the checkout page.
Click the links and see that they go to the appropriate URL.
=> Add links to terms of service, privacy policy, refund policy

courses/migrations/0014_enrollment_blankable.py
N/A (fixes migration conflict on master)
=> Renumber migration

ecommerce/api_test.py
None
Fixes broken tests due to a merge
=> Fix broken tests for DataConsentUser

static/js/containers/pages/register/RegisterEmailPage.js, static/js/containers/pages/register/RegisterEmailPage_test.js
=> asadiqbal08/mitxpro-587 Replace "validate" with "verify"

static/js/containers/pages/login/LoginEmailPage.js, static/js/containers/pages/login/LoginForgotPasswordConfirmPage.js, static/js/containers/pages/login/LoginForgotPasswordConfirmPage_test.js, static/js/containers/pages/login/LoginPasswordPage.js
=> asadiqbal08/mitxpro-588 Replace "login" with "Sign in"

mitxpro/templates/footer.html
Task: #597 
@pdpinch take a look after removing text from footer. any suggestion for it or good to go ? 
?
=> Remove texts in footer.

package.json, requirements.txt, yarn.lock
N/A
Upgrades some deps
Tests should pass and you should be able to launch `ipython`
=> Upgraded deps

mitxpro/templates/footer.html
=> Updated the URL for blogs

mitxpro/templates/footer.html
#726 
Removes "blog" link from footer.
=> #726 Remove blog link from footer

mitxpro/templates/footer.html, static/scss/footer.scss
=> Removed phone number from footer

cms/templates/partials/subnav.html
Closes #739 
Removes all contractions from product page subnav.
=> #739 Remove contractions from subnav

mail/templates/verification/body.html
Fixes #722 
Updates wording on the verification email
Register and verify the wording is correct.
=> Updating wording on the verification email

voucher/views.py, voucher/views_test.py
Fixes #665 
Hopefully nothing new
Go through the voucher workflow
voucher views
(Optional)
(Optional)
(Optional)
=> Switch hardcoded url to reverse url

cms/templates/partials/featured_card.html
N/A
Remove hardcoded product page link
Featured product card should lead to its product page.
=> fix hardcoded product page url

docs/configure_open_edx.md
N/A
Update edx devstack installation steps.
Follow readme steps to setup devstack locally.
=> update edX devstack installation steps.

static/js/components/TopAppBar.js, static/scss/top-app-bar.scss, static/scss/user-menu.scss
Fixes #754 
Fix styling of header links for mobile view.
Header links should render aligned on mobile screens.
=> styling header links for mobile view

README.md
#800 
Updates the `README.md` regarding management command to fix course/program and their index pages.
=> #800 Update Readme regarding index page setup management command

app.base.json, app.json, docker-compose.travis.yml, docker-compose.yml, mitxpro/apps.py, mitxpro/envs.py, mitxpro/envs_test.py, mitxpro/management/commands/generate_app_json.py, mitxpro/settings.py, mitxpro/settings_test.py
N/A
This PR adds automation and some guardrails around environment variables. Specifically it does the following:
- `app.json` is generated from `settings.py` definitions
- A test to ensure `settings.py` and `app.json` are in sync
- if a var is required in `settings.py`, it is required in `app.json` and the app will also refuse to start (so required configuration should be in CI/RC/Prod before they are merged into those envs!)
- Environment vars can't be used multiple times
- Add a settings.py var, run `./manage.py generate_app_json` and verify the new var is defined in `app.json`.
- Verify the app will error if a required var is absent
- Look at the `app.json` in this PR and verify the changes make sense and nothing was lost
=> Automate environment variables

static/scss/slick.scss
Fixes #815 
Fix inconsistent color of navigation arrows.
See home page on smaller screens.
=> fix color of navigational arrows

voucher/admin.py
Closes #809 
Adds a Voucher section to django admin
Go to http://xpro.odl.local:8053/admin/voucher/voucher/ and make sure everything works (search, editing, etc).
=> Vouchers for django admin

cms/models.py
Task #363 
Instead of using FieldPanel("image") in wagtail models.py we should go with ImageChooserPanel.
=> asadiqbal08/mitx-pro363 Used ImageChooserPanel

mitxpro/urls.py, voucher/views_test.py
Closes #821 
Changes the base URL for vouchers from /voucher to /boeing
Go to http://xpro.odl.local:8053/boeing/upload, you should see the upload page.
=> Change URLs for vouchers to /boeing

cms/templates/partials/subnav.html
fixes #847
~~- [ ] Migrations~~
~~- [x] Migration is backwards-compatible with current production code~~
~~- [ ] Settings~~
~~- [ ] New settings are documented and present in `app.json`~~
~~- [ ] New settings have reasonable development defaults, if applicable~~
fixes #847 
s/For Teams/Enterprise/ in subnav
Can you make a screenshot for me, at desktop and in mobile? Then I can sign off on it.
=> change "For Teams" in subnav to "Enterprise"

cms/templates/partials/hero.html, mitxpro/settings.py, requirements.in, requirements.txt
Fixes #854 
Detect user agent, if its mobile don't load background video 
- Load home page on mobile.
- See network tab, video shouldn't be requested.
=> dont load hero banner video on mobile devices

users/serializers.py
Fixes #890 
Moves `sync_hubspot_user` out of atomic transactions
- Register a new user and/or update your profile.  It should work as before and the `sync_hubspot_contact` task should still be run via celery.
=> Move hubspot contact sync task out of atomic transactions

static/js/containers/pages/register/RegisterEmailPage.js, static/js/containers/pages/register/RegisterEmailPage_test.js
Follow up of #600 
Try creating an account with existing email.
=> Fix styling on account exists message

ecommerce/models.py, ecommerce/models_test.py, ecommerce/views.py, ecommerce/views_test.py
Fixes #210 
Adds information to OrderAudit which matches the fields listed in the comment on the issue
Purchase a product then look at the latest `OrderAudit`
=> Add more information to OrderAudit

package.json, static/js/constants.js, static/js/containers/pages/CheckoutPage.js, static/js/containers/pages/CheckoutPage_test.js, static/js/containers/pages/DashboardPage.js, static/js/containers/pages/admin/BulkEnrollmentPage.js, static/js/containers/pages/admin/CreateCouponPage.js, static/js/containers/pages/login/LoginEmailPage.js, static/js/containers/pages/login/LoginForgotPasswordConfirmPage.js, static/js/containers/pages/login/LoginForgotPasswordPage.js, static/js/containers/pages/login/LoginPasswordPage.js, static/js/containers/pages/profile/EditProfilePage.js, static/js/containers/pages/profile/EditProfilePage_test.js, static/js/containers/pages/profile/ViewProfilePage.js, static/js/containers/pages/profile/ViewProfilePage_test.js, static/js/containers/pages/register/RegisterConfirmPage.js, static/js/containers/pages/register/RegisterDeniedPage.js, static/js/containers/pages/register/RegisterDetailsPage.js, static/js/containers/pages/register/RegisterEmailPage.js, static/js/containers/pages/register/RegisterErrorPage.js, static/js/containers/pages/register/RegisterExtraDetailsPage.js, yarn.lock
#679 
Sets appropriate HTML titles on React rendered pages.
Go to any page that is rendered by React (login/enrollment/profile etc). The title of the document should change dynamically on each page.
=> #679 Set an HTML title on React pages

voucher/conftest.py, voucher/utils.py, voucher/utils_test.py
#927 
Matches voucher on partial course id input and partial title input.
Try searching for a segment of a course id and verify that 
(Optional)
(Optional)
(Optional)
(Optional)
=> Change exact search to contains search

webpack.config.shared.js
None
More specifically transpiles only libraries which have errored on IE11 in the past. See #956 for context.
View the site in IE11. You should see the "sign in" and "create account" buttons.
=> Include specific libraries which need transpiling

static/js/hero.js, webpack.config.shared.js
=> Release 0.16.2

RELEASE.rst, mitxpro/settings.py, static/scss/collapsible.scss
=> Release 0.16.4

cms/templates/partials/metadata-tiles.html
=> -fix for program

requirements.in, requirements.txt
N/A
Periodic bump of django
Tests should pass, app should run and be functional.
=> Bumped django

ecommerce/admin.py
No ticket
Improves Django admin UI for `ProductCouponAssignment`, `CouponEligibility`, and `Coupon` models
Test the admin for those 3 models and make sure the UI looks good (both list view and create/update view), and sorting/searching works.
=> Improved Django admin UI for several coupon-related ecommerce models

courses/management/utils.py
Closes #995
Fixes bug where 'edx_enrolled' flag was not being updated by the enrollment commands when the edX enrollment request succeeded
There are 2 commands that create new enrollments: `defer_enrollment` and `transfer_enrollment`. `transfer_enrollment` will be the easiest to test with:
```
manage.py transfer_enrollment --from-user "<SOME_ENROLLED_USER>" --to-user "<SOME_TARGET_USER>" --run "course-v1:edX+DemoX+Demo_Course"`
```
The CourseRunEnrollment created for the user you specified in place of "SOME_TARGET_USER" should have `edx_enrolled=True` if the edX request succeeded
=> Fixed bug where 'edx_enrolled' flag was not being updated by commands

static/js/components/forms/CheckoutForm_test.js, static/js/containers/pages/DashboardPage.js, static/js/containers/pages/DashboardPage_test.js, static/js/containers/pages/admin/CreateCouponPage.js, yarn.lock
N/A
Bumps some JS depenencies
These dependency updates are all for compile- or test-time dependencies so passing tests should be sufficient
=> Bump js dependencies

cms/factories.py, courses/serializers.py, courses/serializers_test.py
Fixes #926 
Updates the current program/course/course run API to return additional data needed for the discussions catalog.
Go to `/api/programs`
=> Update program api

courses/models.py, voucher/conftest.py, voucher/utils.py, voucher/utils_test.py, voucher/views_test.py
Fixes #992 
Update dropdown of courses while enrolling via voucher
1. Set following values in `.env`
```
VOUCHER_DOMESTIC_DATE_KEY=UNIQUE01
VOUCHER_DOMESTIC_EMPLOYEE_KEY=UNIQUE02
VOUCHER_DOMESTIC_EMPLOYEE_ID_KEY=UNIQUE03
VOUCHER_DOMESTIC_KEY=UNIQUE04
VOUCHER_DOMESTIC_COURSE_KEY=UNIQUE05
VOUCHER_DOMESTIC_CREDITS_KEY=UNIQUE06
VOUCHER_DOMESTIC_DATES_KEY=UNIQUE07
VOUCHER_DOMESTIC_AMOUNT_KEY=UNIQUE08
VOUCHER_INTERNATIONAL_EMPLOYEE_KEY=UNIQUE09
VOUCHER_INTERNATIONAL_PROGRAM_KEY=UNIQUE10
VOUCHER_INTERNATIONAL_COURSE_KEY=UNIQUE11
VOUCHER_INTERNATIONAL_SCHOOL_KEY=UNIQUE12
VOUCHER_INTERNATIONAL_EMPLOYEE_ID_KEY=UNIQUE13
VOUCHER_INTERNATIONAL_AMOUNT_KEY=UNIQUE14
VOUCHER_INTERNATIONAL_DATES_KEY=UNIQUE15
VOUCHER_INTERNATIONAL_COURSE_NAME_KEY=UNIQUE16
VOUCHER_INTERNATIONAL_COURSE_NUMBER_KEY=UNIQUE17 …
```
=> voucher dropdown update

static/scss/voucher.scss, voucher/templates/resubmit.html
Fixes #1020 
Add button to resubmit page that leads to support center.
- Goto `/boeing/upload/`
- Try upload any invalid file
- You should see button `CONTACT US` that will leads to support center.
=> link to support center on voucher resubmit page

courses/utils.py
No ticket
Fixes bug introduced in #1032 
Considering this is a very simple management command fix, and that command isn't trivial to test, I don't think this needs functional testing
=> Fixed bug in sync_grades_and_certificates command

cms/templates/partials/text-video-section.html, static/js/hero.js, static/js/text_video_section.js, static/scss/detail/text-video-section.scss
=> asadiqbal08/mitxpro-1036 Homepage: open "Watch Now" video in a lightbox

courses/api.py, courses/api_test.py
#595 
Sorts courses on dashboard by start date.
Make sure user has enrollments so that they show up on the dashboard. Go to the dashboard and verify that all courses are displayed sorted according to their start date.
=> #595 Sort dashboard courses

static/scss/voucher.scss
Fixes #883 
Add css to style filename.
Goto `/boing/upload`
Try to upload any file.
See comments on the #883
=> styling of file name

package.json, yarn.lock
Fixes #1085 
Update `set-value` and `mixin-deep`
- Nothing should break.
- Tests should pass.
You may want to take a look at https://blog.shovonhasan.com/fixing-a-security-vulnerability-in-a-transitive-dependency/
=> update set-value and mixin-deep js dependencies

courses/apps.py
Just import the signals in app.py file for courses.
=> mitxpro-1030-fix import the signal in courses app

config/nginx.conf, config/nginx.conf.erb
#1031 
The previous change only applies to the local Docker container which doesn't serve the intended purpose. Adding the endpoint to the Nginx config for Heroku so that it will successfully validate.
Additionally, this adds a properly formatted HTML document instead of just the meta tag.
Verify that the endpoint  /.well-known/pki-validation/gsdv.txt returns the expected HTML
=> Adding validation to proper Nginx config and full HTML response

courses/management/commands/sync_grades_and_certificates.py
No ticket. I noticed this while confirming the command on RC
Prevents the command from syncing grades/certificates for course runs that haven't ended unless a `-f`/`--force` flag is included. The edX API client returns grade data for courses that are still in progress, so we should not consider those grades to be final (and, given that, we should not make decisions about certificates) unless the course run has actually ended.
Using a course run with an `end_date` that is either `None` or in the future, run this command:
```
manage.py sync_grades_and_certificates --run "course-v1:edX+DemoX+Demo_Course" --user "<enrolled_user_email_or_username>"
```
An error should be raised and the command should exit. After that, add the `-f` flag and try again. It should succeed
=> Updated sync_grades_and_certificates params

ecommerce/migrations/0019_amount_more_decimal_places.py
None
Renames a migration to fix a migration conflict
=> Fix migrations by renaming one conflicting migration to happen later

authentication/pipeline/user.py, authentication/pipeline/user_test.py, static/js/components/forms/ProfileFormFields.js, static/js/components/forms/RegisterDetailsForm_test.js
=> asadiqbal08/mitxpro-1122 - Add validation over name field

cms/models.py, cms/templates/certificate_page.html, static/scss/certificates/certificate.scss
#1123 
Adds a validation link to the certificate template.
Go to a certificate page, verify the link displays correctly and navigates to the same page when clicked. Also verify that the link appears in black color with no underline in print mode.
=> #1123 certificate validation link

static/js/components/forms/CouponForm.js
#953 
- Just rendered the form errors
=> asadiqbal08/mitxpro-953 Introduce FormErrors for ecommerce coupons

authentication/pipeline/compliance.py, ecommerce/utils.py
Fixes #972 
Change from email for admin notifications.
Not sure
=> change from email for admin notifications

static/js/containers/pages/register/RegisterConfirmSentPage.js, static/js/containers/pages/register/RegisterConfirmSentPage_test.js, static/js/containers/pages/register/RegisterEmailPage.js, static/js/containers/pages/register/RegisterEmailPage_test.js, static/js/containers/pages/register/RegisterPages.js, static/js/lib/auth.js, static/js/lib/selectors.js, static/js/lib/selectors_test.js, static/js/lib/urls.js, static/scss/auth.scss
Fixes #1106 
Add new react page to redirect users after verification email sent.
Try creating new account after enter email and ticking captcha you should see new page.
=> email verification message updated

b2b_ecommerce/admin.py, courses/admin.py, courseware/admin.py, ecommerce/admin.py, mitxpro/admin.py
No ticket
Fixes a bunch of admin classes that are unusable with semi-large amounts of data
Visit the list and detail admin pages for all of the admin classes changed
=> Updated several admin classes (course run enrollment, etc)

static/js/containers/pages/login/LoginEmailPage.js, static/js/containers/pages/login/LoginEmailPage_test.js
fixes #1063 
Fix redirecting issue while creating account.
(Required)
=> MIT xPRO - 1063 Fix redirect issue while creating account

cms/models.py, courses/models.py
Fixes #1141 
Optimize queries to improve performance.
- Goto `/catalog`
- You should see no warnings on console about n+1 queries.
=> performance optimization on catalog page

config/nginx.conf, config/nginx.conf.erb, fastly_verification.html
#1031 
The `return` directive doesn't cause the text to be rendered as HTML. Updated to return an HTML file so it gets rendered properly for verification
Verify that the location `/.well-known/pki-validation/gsdv.txt` returns an HTML rendered page with the specified meta tag.
=> Fixing verification rendering

ecommerce/admin.py
Fixes #1189 
Add product as raw_id_field in the product version admin page.
Goto `/admin/ecommerce/productversion/` and try to add new or change any existing record.
=> product as raw field in product version

static/scss/catalog/body.scss
Fixes #964 
Update CSS for catalog page to render on IE11
Load `/catalog` page on IE11.
=> fix catalog page for IE11

README.md, docs/configure_open_edx.md
fixes #1153 
Fix broken commands.
(Required)
=> MIT xPRO - 1153 Fix broken commands in handbook and added in mitxpro

static/scss/dashboard.scss
Fixes #1195 
Fix the dashboard display is wonky on IE 11
- Enroll in a program
- View the dashboard in IE11
- Click the button to reveal the list of courses
=> asadiqbal08/mitxpro-1195 Fix the layout issue for IE over dashboard

fastly_verification.html
#1031 
Updated the metadata for Fastly TLS cert verification
Visit the specified location in the nginx config and verify that the updated metadata is shown
=> Updated metadata for new attempt at TLS cert generation

app.json, mitxpro/context_processors.py, mitxpro/settings.py, mitxpro/templates/base.html
#1174 
Add a zendesk help widget. 
visit mitxpro web project. There should be a help widget all over project and The help widget should look and function on xpro.mit.edu the same way it does on https://xpro.zendesk.com/hc/en-us
=> asadiqbal08/mitxpro-1174 Added the zendesk help widget to project

static/scss/user-menu.scss
fixes #1212 
Changes user menu in the following way
- Cursor changes from arrow to finger
- The clickable area includes the rectangular area that includes the avatar and the dropdown area
Just click on the User menu to see the changes.
=> Expand clickable area for user menu

courses/management/utils.py, courses/management/utils_test.py
Fixes #1248 
Fix `KeyError` in `transfer_enrollment` management command.
Run `transfer_enrollment` management command.
=> fix key error in transfer enrollment command

cms/templates/certificate_page.html, static/scss/certificates/certificate.scss
Fixes #1254
Fixes #1244 
Removed the border
- Visit https://xpro-ci-pr-1258.herokuapp.com/certificate/4089dc79-5a3b-4326-bcb4-f68ebeda959c/
- Design in print landscape mode should be same as mentioned in #1254 
- Notifications should not be in printing page.
=> asadiqbal08/mitxpro-Fix the landscape mode issue while Printing

voucher/templates/enroll.html, voucher/utils.py, voucher/utils_test.py, voucher/views.py, voucher/views_test.py
fixes #1227 
You need to perform the following steps for generating seed data of vouchers.
**Add Environment Variables**
> VOUCHER_DOMESTIC_DATE_KEY=UNIQUE01
VOUCHER_DOMESTIC_EMPLOYEE_KEY=UNIQUE02
VOUCHER_DOMESTIC_EMPLOYEE_ID_KEY=UNIQUE03
VOUCHER_DOMESTIC_KEY=UNIQUE04
VOUCHER_DOMESTIC_COURSE_KEY=UNIQUE05
VOUCHER_DOMESTIC_CREDITS_KEY=UNIQUE06
VOUCHER_DOMESTIC_DATES_KEY=UNIQUE07
VOUCHER_DOMESTIC_AMOUNT_KEY=UNIQUE08
VOUCHER_INTERNATIONAL_EMPLOYEE_KEY=UNIQUE09
VOUCHER_INTERNATIONAL_PROGRAM_KEY=UNIQUE10
VOUCHER_INTERNATIONAL_COURSE_KEY=UNIQUE11
VOUCHER_INTERNATIONAL_SCHOOL_KEY=UNIQUE12
VOUCHER_INTERNATIONAL_EMPLOYEE_ID_KEY=UNIQUE13
VOUCHER_INTERNATIONAL_AMOUNT_KEY=UNIQUE14
VOUCHER_INTERNATIONAL_DATES_KEY=UNIQUE15
VOUCHER_INTERNATIONAL_COURSE_NAME_KEY=UNIQUE16 …
=> Vouchers: sort matching courseruns by similarity

ecommerce/admin.py
#1247
Display the product latest version `text ID` and `price` in django admin.
visit admin/ecommerce/product/ to see price and text id in list_display.
=> asadiqbal08/mitxpro-1247- Display the text id and price in product list_display

hubspot/api.py, hubspot/api_test.py, hubspot/management/commands/configure_hubspot_bridge.py, hubspot/serializers.py, hubspot/serializers_test.py
#1295 #1296 
Adds Birth Year to the custom contact properties
Adds status to custom deal properties and syncs it
Reconfigure the hubspot bridge and then sync an individual item, make sure it updates.
Then resync all deals.
(Optional)
(Optional)
(Optional)
(Optional)
=> Add status to deal sync, add birth year to custom props

static/js/containers/pages/login/LoginForgotPasswordConfirmPage_test.js, static/js/containers/pages/login/LoginForgotPasswordPage_test.js, static/js/lib/queries/auth.js
fixes #1226 
After login, visit /sigin/forgot-password/ and try to change your password.
=> MIT xPRO - 1226 Fix forgot password form while logged in

cms/migrations/0031_setup_catalog_page.py, cms/migrations/0043_setup_certificate_index_page.py, requirements.in, requirements.txt
Update **Wagtaill** to **v2.6.3** and **Pillow** to **v6.2.0**
Release notes:
[Pillow v6.2.0](https://github.com/python-pillow/Pillow/releases/tag/6.2.0)
[Wagtail v2.6](https://github.com/wagtail/wagtail/releases/tag/v2.6)
[Wagtail v2.6.1](https://github.com/wagtail/wagtail/releases/tag/v2.6.1)
[Wagtail v2.6.2](https://github.com/wagtail/wagtail/releases/tag/v2.6.2)
[Wagtail v2.6.3](https://github.com/wagtail/wagtail/releases/tag/v2.6.3)
First of all, you need to run this command `docker-compose build` which will install the required modules. Then try to run each feature of it.
=> Update Pillow, Wagtail

courses/models.py
#1327 
Fix the comparison issue between `<` and NoneType
=> asadiqbal08/mitxpro-1327 TypeError '<' not supported 

app.json, mitxpro/settings.py
#1331 
Adds the USE_X_FORWARDED_HOST setting
Verify that the Host attribute for things such as verification emails is set properly when the X-Forwarded-Host header is set.
In order for our integration with Fastly (or any CDN) to work properly we need to be able to use the `X-Forwarded-Host` attribute to override the `Host` header on the application so that things such as verification emails are using the correct domain.
=> Add X-Forwarded-Host setting and make it configurable

sheets/configure_sheets_client.md
(Required)
(Required)
(Required)
(Optional)
(Optional)
(Optional)
(Optional)
=> Updated Sheets setup doc

sheets/api.py, sheets/management/utils.py
No ticket. Bug discovered in RC
Adds logging for spreadsheet sharing failures and continues sharing with the rest of the admin emails
Code review only. Will be tested on RC
I fixed a util function for a management command as part of this PR as well
=> Added spreadsheet sharing error handling

app.json, courses/serializers.py, courses/serializers_test.py, ecommerce/serializers.py, ecommerce/serializers_test.py, ecommerce/views.py, ecommerce/views_test.py, mitxpro/settings.py, static/js/containers/pages/DashboardPage.js, static/js/containers/pages/DashboardPage_test.js, static/js/containers/pages/ReceiptPage.js, static/js/containers/pages/ReceiptPage_test.js, static/js/factories/course.js, static/js/flow/courseTypes.js, static/js/flow/ecommerceTypes.js, static/js/lib/queries/ecommerce.js, static/js/lib/queries/users.js
fixes #1346 
**Desktop:**
**Mobile:**
=> MIT xPRO 1346 - Add link to receipt(s) to dashboard

courses/admin.py
Fixes #1312 
- Modify Django admin
- Add search fields
- Filter on course run id instead of name
- Make sure you have entries in courserungrade,
- Search on username and email should work,
- Course run id should appear instead of course name in filter.
=> add search for courserungrade in admin

app.json, ecommerce/api.py, ecommerce/api_test.py, ecommerce/models.py, ecommerce/models_test.py, mitxpro/settings.py, static/js/containers/pages/DashboardPage.js, static/js/containers/pages/DashboardPage_test.js, static/js/flow/ecommerceTypes.js, static/scss/dashboard.scss, users/serializers.py, users/views_test.py
Fixes #1293 
List unredeemed enrollment codes on the dashboard.
- Create coupon codes.
- Upload CSV with user's emails to bulk enroll.
- User(s) listed in the CSV should see a new section on the dashboard with a list of unredeemed codes.
**Given design:** https://projects.invisionapp.com/d/main#/console/17338252/393054151/inspect
=> list unredeemed enrollments on dashboard

ecommerce/api.py, ecommerce/mail_api.py, ecommerce/mail_api_test.py, ecommerce/views.py, mail/constants.py, mail/templates/email_base.html, mail/templates/product_order_receipt/body.html, mail/templates/product_order_receipt/subject.txt
#1344 
Will send a order receipt to user via email
- Enroll a user in a course/program. 
- Enroll with a coupon 100% discount
- Enroll with a cybersource process.
- Receipt email should be sent to the user with purchase details.
=> asadiqbal08/mit-1344 Email receipt to the user

sheets/tasks.py
No ticket. Bug observed in RC
Fixes a bug with updating coupon assignment rows upon enrollment.
=> Fixed bug with updating coupon assignment rows upon enrollment

sheets/tasks.py
Reverts mitodl/mitxpro#1396 (accidental merge w/o code review)
=> Revert "Fixed bug with updating coupon assignment rows upon enrollment"

sheets/api.py, sheets/api_test.py
Closes #1384 
Instead of throwing an exception if an unrecognized company name is encountered while processing coupon requests, a new company is created. Coupon requests are driven by a 
Google Form where users select a company, and we are now populating those company choices
with spreadsheet values. That spreadsheet will be considered a primary source of truth for 
valid company names, hence the change in logic.
The rest of the functionality described in #1384 is done in Google Scripts. That work has been tested and applied in the RC spreadsheet
=> Changed coupon request handling to create unrecognized companies

courses/models.py, courses/models_test.py
Fixes #1170 
Add `@cached_property` to optimize performance.
Tests should run.
The catalog page should work as expected.
=> optimize repetitive looping on course catalog page

b2b_ecommerce/constants.py
#1392 
change value of constant
The test should pass.
=> change value of constant

static/js/components/forms/CheckoutForm.js, static/js/lib/form.js, static/scss/checkout.scss, static/scss/variables.scss
fixes #1386 
**Desktop**
**Tablet**
**Mobile**
=> MIT xPRO - 1386 Checkout: Display success message when coupon is successfully

courses/management/commands/sync_grades_and_certificates.py
#1313 
Updates the `sync_grades_and_certificates` command to include the grade status, user passed status and certificate status (ignored, already exists, deleted, created)
Run the `sync_grades_and_certificates` management command
=> #1313 update sync_grades_and_certificates command msg

mail/api.py, mail/exceptions.py, sheets/api.py, sheets/constants.py, sheets/tasks.py, sheets/utils.py
Closes #1419 
Checks emails in a coupon assignment sheet and updates the sheet to indicate an error if any emails fail initial validation
=> Added validation and reporting for emails in coupon assignment sheets

ecommerce/mail_api.py, ecommerce/mail_api_test.py, ecommerce/serializers.py, ecommerce/serializers_test.py
fixes #1438 
- Add Cybersource Payment and order the course with 10% discount in dollar and cents
=> #1438 display dollars and cents in both email and receipt page

package.json, yarn.lock
https://github.com/mitodl/mitxpro/network/alert/yarn.lock/serialize-javascript/open
=> update the serialize-javascript

authentication/pipeline/compliance.py, users/models.py
#1391 
Include user's street address in export compliance notifications
=> asadiqbal08/mitxpro-1391 Included user's street address

package.json, yarn.lock
https://github.com/mitodl/mitxpro/network/alert/yarn.lock/handlebars/open
Version bump for handlebars.
=> Updated the version of handlebars

static/js/components/forms/CheckoutForm.js
#1436 
- The coupon should be applied
- The user should see a success message
=> asadiqbal08/mitxpro-1436 Fix coupon success message

sheets/api.py, sheets/utils.py
Closes #1320 
Sets protected ranges on coupon assignment sheet cells that should not be edited by non-privileged users
=> Set coupon assignment sheet cells to protected

sheets/api.py, sheets/views.py
No ticket. Related to some Sentry issues that are logged with unique names when they shouldn't be
Corrects the string interpolation for log messages in the sheets app
=> Fixed sheets app log message interpolation

test_requirements.txt
Pinned the version of freezegun
=> Pinned the version for freezegun

courses/management/commands/create_enrollment.py, courses/serializers.py
#1385 
fixes #1385 
Generate enrollment code and run the management command
`docker-compose exec web ./manage.py create_enrollment --user "abc@example.com" --run "course-v1:edX+DemoX+Demo_Course" --code="123"`
=> #1385 Management command to create enrollment in closed course

static/js/components/B2BCheckoutExplanation.js, static/js/components/forms/B2BPurchaseForm.js, static/js/components/input/ProductSelector.js, static/js/containers/pages/b2b/B2BPurchasePage.js, static/scss/checkout.scss
[Ticket-1](https://trello.com/c/AZNwLQ6e/50-bulk-purchase-form-updates-add-enterprise-terms-and-conditions)
[Ticket-2](https://trello.com/c/jlXtUEBI/52-bulk-purchase-enterprise-terms-and-conditions-page)
Updated the UI as described in the tickets. 
- Visit /ecommerce/bulk/
- Verify the requested changes.
=> asadiqbal08/mitxpro Added Enterprise Privacy Statement + UI Updates

sheets/tasks.py
No ticket. Fixed another bug introduced by #1503. Sentry issue: https://sentry.io/organizations/mit-office-of-digital-learning/issues/1490206168/?project=1413655&query=is%3Aunresolved
Fixes imports in `sheets/tasks.py`
=> Fixed incorrect sheets module reference in tasks

cms/templates/partials/hero.html
[Ticket](https://trello.com/c/oH06M047/73-regression-video-on-catalog-page-is-wrapping-to-a-new-line)
Fix video on catalog page is wrapping to a new line.
=> asadiqbal08/Fix video on catalog page is wrapping to a new line.

courses/views.py
None
Removes an unused view. It is not currently exposed in `urls.py` and there are no tests for it.
Nothing should change
=> Remove unused CourseCatalogView

ecommerce/views_test.py
No ticket
Fixes flaky test that was occasionally failing in CI
=> Fixed flaky bulk enrollment list test

static/js/components/forms/ProfileFormFields.js
[Ticket](https://trello.com/c/BA8WRVer/65-profile-ask-user-if-address-is-business-or-residential)
Create an account and verify the text as required in the ticket.
=> Change Street Address label (Home or Residential)

courses/management/commands/create_enrollment.py
[Ticket](https://trello.com/c/d5rbCeZH/59-bug-unused-coupon-message-still-displays-after-running-createenrollment)
Updates `create_enrollment` management command to mark `ProductCouponAssignment.redeemed=True` when the enrollment is created via the command.
- Create enrollment codes
- Assign code to a user via `/ecommerce/admin/enroll/`
- At this point the user should see the "unused coupon" banner when they sign in, also receive an email regarding the coupon code
- Use the `create_enrollment` management command to manually enroll them in the course
- Refresh the page, the user should be able to see their enrollment in the dashboard and the banner should not display anymore.
=> #59 Fix unused coupon banner bug after command create enrollment

courses/admin.py, ecommerce/admin.py, ecommerce/models.py
[Ticket](https://trello.com/c/Kfz5m2zO/41-django-admin-improvements)
As an admin, there are a number of small changes that would make me more efficient. 
Visit the admin pages as described in the ticket and verify the requested changes.
=> Django admin improvements

sheets/management/commands/setup_file_watch.py, sheets/tasks.py, sheets/views.py
Closes #1548
Adds management command and view handling for file watch requests from Google having to do with the deferral request spreadsheet
=> Added deferral sheet file watch and management command

runtime.txt
None
Updates the heroku runtime to python 3.7
N/A. Docker has already been updated to Python 3.7 so hopefully there are no hidden issues. To test this we can make sure the release candidate is working properly.
=> Update heroku to Python 3.7

config/nginx.conf.erb
https://trello.com/c/cmZZH9QH/58-dont-let-the-cdn-cache-api-routes
Fixes #1501
- Add cache header for `static/hash.txt`
- References: http://nginx.org/en/docs/http/ngx_http_headers_module.html, https://docs.fastly.com/en/guides/cache-control-tutorial#nginx-configuration
- Nothing should break.
=> Web app should issue appropriate headers for cache management

courses/admin.py
https://trello.com/c/hisv9w3M/67-admin-add-readableid-to-search-fields-for-courses-courses-admin
Add readable_id in search fields in courses admin
- Goto `admin/courses/course/`
- Search course with course readable id
=> add readable_id in search fields in course admin

ecommerce/api.py, ecommerce/api_test.py
[Ticket](https://trello.com/c/Lav8OqRE/64-bug-checkout-page-crashes-if-user-has-inactive-enrollment-code)
Fix checkout page crashes if user has inactive enrollment code.
- Turn on the flag in settings `SHOW_UNREDEEMED_COUPON_ON_DASHBOARD` to execute the flow. 
- follow the steps as mentioned in the ticket and in the video. -- https://share.vidyard.com/watch/zbtsjrvoAZx8NgSSYz7qxx
=> asadiqbal08/mitxpro- Fix Checkout page crashes if user has inactive enrollment code

sheets/management/utils_test.py
[Ticket](https://trello.com/c/o4UhkzMc/78-improve-xpro-coverage-report)
Adds tests for `sheets/management/utils.py` to increase coverage.
Pylint should report coverage of the indicated file above 0% (previous coverage).
=> Sheets management utils tests

static/js/components/forms/ChangeEmailForm.js, static/js/components/forms/ChangeEmailForm_test.js, static/js/containers/pages/settings/AccountSettingsPage.js, static/js/containers/pages/settings/AccountSettingsPage_test.js, static/js/lib/validation.js, static/js/lib/validation_test.js, static/scss/auth.scss
[Ticket](https://trello.com/c/4Lwa0VLQ/98-split-account-settings-page-into-two-forms)
Split Account Settings page into two forms.
You need to test the change password and email feature manually.
=> Split account settings page into two forms

sheets/deferral_request_api.py, sheets/refund_request_api.py
No ticket
Changes user email search to be case-insensitive for refund and deferral requests
Code review only. This will be tested in RC
=> Made email search case-insensitive for refunds/deferrals

ecommerce/serializers.py, ecommerce/serializers_test.py, ecommerce/views.py, ecommerce/views_test.py
[Ticket](https://trello.com/c/sRwKc5cb/95-bulk-purchase-improve-performance-of-product-api)
Try to improve the api bulk purchase operations.
Specifed in the ticket. 
```
[2020-02-27 12:48:20] ERROR 891 [nplusone] notifiers.py:40 - [ef6207f4ff5a] - Potential n+1 query detected on `Product.content_type`
[2020-02-27 12:48:20] ERROR 891 [nplusone] notifiers.py:40 - [ef6207f4ff5a] - Potential n+1 query detected on `Product.content_type`
[2020-02-27 12:48:20] ERROR 891 [nplusone] notifiers.py:40 - [ef6207f4ff5a] - Potential n+1 query detected on `Product.productversions`
[2020-02-27 12:48:20] ERROR 891 [nplusone] notifiers.py:40 - [ef6207f4ff5a] - Potential n+1 query detected on `Product.productversions`
[2020-02-27 12:48:20] ERROR 891 [nplusone] notifiers.py:40 - [ef6207f4ff5a] - Potential n+1 …
```
=> Optimizing N+1 ORM Bulk purchase operations

app.json, mitxpro/settings.py, users/serializers.py, users/views_test.py
[Ticket](https://trello.com/c/HaA9QtMu/94-remove-showunredeemedcouponondashboard-feature-flag)
UNREDEEMED COUPONS should be shown on dashboard without any feature flag
Assign coupons to the user and go to the dashboard
=> remove SHOW_UNREDEEMED_COUPON_ON_DASHBOARD feature flag

courses/admin.py
https://trello.com/c/cuwIErME/105-admin-on-course-and-program-certificates-show-date-created-and-updated
Admin: on course and program certificates, show date created and updated
Just visit the following pages
http://xpro.odl.local:8053/admin/courses/courseruncertificate/
http://xpro.odl.local:8053/admin/courses/programcertificate/
=> Admin: on course and program certificates, show date created and updated

ecommerce/admin.py
https://trello.com/c/2ndIBWMy/123-application-error-attempting-to-access-admin-ecommerce-dataconsentagreement-2-in-production
Optimize performance(N+1 queries) on admin dataconsentagreement page
Create data consent agreement page with atleast 4 to 5 DATA CONSENT USERS
(Optional)
(Optional)
**Before**
**Now**
(Optional)
=> Optimize performance(N+1 queries) on admin dataconsentagreement page

static/js/components/forms/B2BPurchaseForm.js
[Ticket](https://trello.com/c/GDZM1p4p/136-bulk-purchase-text-updates)
Makes some changes to the language of the form as per the requirements in the ticket.
Visit `/ecommerce/bulk/` and verify the changes are in line with the requirements.
=> Bulk purchase text updates - #136

cms/template_tags_test.py
No ticket
Moves a test file so that the test suite can run correctly in deployed envs
No manual testing. If the build succeeds, it works
=> Moved test file for cms templatetags

static/js/components/forms/CheckoutForm.js
#1664 , https://trello.com/c/X3yoQfAo/143-placement-of-place-your-order-button-when-multiple-courses
fixes #1664
Change placement of order button on checkout page
Just visit the checkout page for both program and course run.
**Multiple Courses**
**One Course**
**Mobile**
=> change placement of order button on checkout page

package.json, yarn.lock
https://trello.com/c/JAbw4VA5/133-upgrade-kind-of-to-version-603-or-later
This updates the` kind-of` version from `3.2.2` to `6.0.2`.
Security alerts ask to update it `6.0.3`. As it's not being used as a direct dependency in our project but it depends on many other packages. But any of its parents packages either no longer supporting it or supporting only `6.0.2`. 
**NOW**
``` ⚙ umerasghar@A006-00274  ~/arbisoft/MIT/bootcamp-devstack/devstack   master ●  heroku run /bin/bash -a xpro-ci-pr-1748
Running /bin/bash on ⬢ xpro-ci-pr-1748... up, run.6295 (Free)
~ $ cd node_modules/kind-of/
~/node_modules/kind-of $ cat package.json
{
"name": "kind-of",
"description": "Get the native type of a value.",
"version": "6.0.2",
"homepage": "https://github.com/jonschlinkert/kind-of",
"author": "Jon …
```
=> update kind-of version to 6.0.2

courses/README.md
closes #1754
documents xPRO processes for creating a new course
follow the instructions when creating a new course.
=> add course creation runbook

Procfile
Adds newrelic to worker processes similar to the config on the other apps that we're running in Heorku.
=> Added newrelic to worker processes

b2b_ecommerce/factories.py, b2b_ecommerce/views.py, hubspot/api.py, hubspot/conftest.py, hubspot/management/commands/configure_hubspot_bridge.py, hubspot/management/commands/sync_hubspot.py, hubspot/serializers.py, hubspot/serializers_test.py, hubspot/task_helpers.py, hubspot/tasks.py, hubspot/tasks_test.py
[Ticket](https://trello.com/c/Eze40x90/47-bulk-purchase-sync-with-hubspot)
- If the bulk purchaser doesn't have an account (which isn't required), create a contact in Hubspot using only their email address. 
- Pass the hubspot cookie, similar to how we do it at account creation
- Create a Deal in Hubspot similar to how we create them on the checkout page. 
- Synced a Product and Contact too.
- Updated the management commands for syncing with hubspot. 
- Complete a B2B purchase and verify the above points over hubspot. 
- Deal created with contact and product synced.
=> asadiqbal08/Bulk purchase: sync with Hubspot

ecommerce/models.py
[Ticket](https://trello.com/c/PtyEZciS/275-need-to-add-default-image-under-unused-enrollment-code-flow)
Add up default image under unused enrollment code flow. [Previous PR](https://github.com/mitodl/mitxpro/pull/1356)
=> Fix Broken Image

cms/templates/certificate_page.html, static/scss/certificates/certificate.scss, static/scss/layout.scss
#1798 
fixes #1798 , make 5 signatories for the certificate.
Just generate the certificate with 5 sigantories
**Desktop**
**Tablet**
**Mobile**
**Certificate**
**Pdf**
[certificate.pdf](https://github.com/mitodl/mitxpro/files/4863347/certificate2.pdf)
=> make 5 signatories for the certificate

b2b_ecommerce/views.py, b2b_ecommerce/views_test.py
fixes: #1771 
User is not able to apply a coupon code when user pass the product_id as text_id e.g. ?product_id=program-v1:xPRO+SysEngx but works fine in case of integer pass ?product_id=1 in B2B/Bulk purchase so the PR fix this problem.
- Create a b2b coupon for a product. 
- Follow a B2B purchase by passing product_id as both integer and text_id e.g.
- .../ecommerce/bulk/?product_id=1
- .../ecommerce/bulk/?product_id=program-v1:xPRO+SysEngx
- Apply Coupon in both cases and it should work as expected.
=> asadiqbal08/Fix for product_id as text during coupon redemption

courses/templates/subscription.html, mitxpro/templates/base.html, mitxpro/templates/footer.html
fixes: #1826 
Fix the sentry error for hubspot undefined.
=> asadiqbal08/Fix the undefined refernce error for hbspot. 

courses/management/commands/create_enrollment.py
fixes: #1751 
Create an order when enrollment is created for a user via coupon code.
=> asadiqbal08/mitxPro create_enrollment management command create an order

.pre-commit-config.yaml, .secrets.baseline, README.md
Closes #1759
Install config files to run the `detect-secrets` hook via `pre-commit`
- Installs a pre-commit hook during `docker-compose build` that will run before every commit
- run `pip install pre_commit`
- run `pre-commit install`
- `git add` an `.env`-like file with fake (but realistic) AWS credentials in it
- `git commit -a -m 'test' ` should generate an error list of bad things it finds in the added file, and the commit should be aborted.
- Replace the contents of the file with safe random text, then run `git commit -a -m 'test'` again, it should work.
=> precommit hook configuration

mitxpro/templates/footer.html
fixes: #1855 
Add a Accessibility link in footer
=> asadiqbal08/mitxPro - Add the Accessability link in footer

static/js/components/forms/B2BPurchaseForm.js, static/js/components/input/ProductSelector.js
fixes #1868 
Apply coupon automatically on switching product from the select field
See that video https://www.dropbox.com/s/riws3bqdhco5nol/xPRO_Issue_1868.mov?dl=0
Or on switching products (different course run with different date and time), it should automatically apply the coupon
=> apply coupon automatically on switching product from the select field

cms/templates/product_page.html, static/js/containers/pages/CheckoutPage.js
#1887 
The product requires some additional metadata on each for product page for the catalog to pull from.
Verify the meta options in product page.
=> asadiqbal08/mitxpro Product page microdata

static/js/containers/pages/settings/EmailConfirmPage.js, static/js/containers/pages/settings/EmailConfirmPage_test.js
closes https://github.com/mitodl/mitxpro/issues/1898
Fixes a typo in email change success message
Change the email for a  profile. Verify that the success message looks good
=> fix email change confirmation

authentication/api.py
closes https://github.com/mitodl/mitxpro/issues/1890
This pr ensures that generated usernames have at least two characters
Create an account with an email and full name that each have only one non-numeric character. You can easily generate an email with only one non-numeric character on https://www.guerrillamail.com/.
Verify that the generated username is longer than two characters.
=> pad short username

cms/templates/product_page.html, static/js/containers/pages/CheckoutPage.js
#1887 
Address [Sam's Feedback](https://github.com/mitodl/mitxpro/issues/1887#issuecomment-691311997)
- Visit product detail page and verify the price value in header meta tag for all `course`, `program` and `external courses`.
- Visit http://xpro.odl.local:8053/checkout/?product=2 and verify the window datalayer should contains the `course-id` and 'price' attributes properly.
=> asadiqbal08/Addressing Sam's Feedback

mail/templates/b2b_receipt/body.html, static/js/components/forms/B2BPurchaseForm.js
#1913 
Updated the terms and condition text and URL. 
Visit the following pages in order to verify the text and URL.
- B2B Purchase Page
- B2B Receipt Page
- xPro Checkout Product Page
-
=> asadiqbal08/mitxpro Updated the terms & condition text and link url

cms/templates/partials/image-carousel.html, mitxpro/templates/base.html
#1908 
Makes resource usage changes to the home page to partially fix issues described in #1908 
Use Lighthouse or Google Pagespeed to test before/after performance score. There should be an increase in the overall score and speed for the page.
Devops needs to increase the cache expiry limit on media resources for xPRO (probably on the CDN level if it's being controlled from there or the server if that's the original source of the cache header).
=> Home page performance tweaks - #1908

courses/management/commands/create_enrollment.py
#1924 
Fix the `MultipleObjectsReturned` issue.
Run the create_enrollment command, After a successful enrollment for a user there should be corresponding order too for it.
=> Fix Order.MultipleObjectsReturned create_enrollment command

ecommerce/admin.py
No ticket - related to #1917 
See title
Check that the `BulkCouponAssignment` admin looks correct (/admin/ecommerce/bulkcouponassignment/)
=> Improved BulkCouponAssignment admin to be searchable and show timestamps

docs/configure_open_edx.md
Minor update to the doc regarding adding a user and token on the Open edX side.
=> Added info about setting up Open edX user and token

cms/models.py
fixes #1919 
optimize the catalog page performance
**Before**
**After**
=> xPRO Catalog page performance improvements

courses/management/commands/create_enrollment.py
Fixed #1939 
It adds a fix in `create_enrollment` command for order association with enrollment. Previously enrollment and order were getting created, But they won't associate with each other.
Might need to run the command with specified params. Verify the enrollment on `/admin`. The order should be associated with enrollment.
=> Associate order with Course Enrollment in enrollment command

package.json, yarn.lock
fixes #1950 
update kind-of version to fix the security alert
Just test everything is working fine in the system
=> fix kind-of security alert

package.json, yarn.lock
fixes #1940
fixes `minimist` security alert
Just check the system everything is working fine
=> fix minimist security alert

mitxpro/templates/base.html, static/scss/icomoon.scss, static/scss/slick.scss
fixes #1956 
fix broken icomoon svg icons
Just visit the home page and see the notification and carousel left and right button icons. Please make sure you have the Wagtail populated page
=> fix icomoon svg broken icons

courses/views_test.py
No ticket
Fixes flaky test
None required. Build should succeed
=> Fixed flaky course runs test

users/views_test.py
Fixes https://github.com/mitodl/mitxpro/issues/1753
enhances users_api-me api tests
=> enhance users_api-me api tests

test_requirements.txt
N/A
Fixes ci tests (hopefully)
CI tests should pass
=> Peg faker at 5.0.1 to avoid test failures

cms/views_test.py
No ticket
⚠️ This is rebased on https://github.com/mitodl/mitxpro/pull/2048 and should only be merged after that PR merges ⚠️ 
Adds a test for the Wagtail admin API, which was fixed in https://github.com/mitodl/mitxpro/pull/2048
N/A
=> Wagtail admin api test

cms/api.py, cms/api_test.py, cms/factories.py, cms/models.py
https://github.com/mitodl/mitxpro/issues/2053
Related to #2034, We need to filer the pages along with program external pages over the catalog page.
=>  Filtering and Sorting for External Program Pages

cms/templates/home_page.html, courses/templates/subscription.html, mail/templates/email_debugger.html, mitxpro/templates/base.html, mitxpro/templates/footer.html, mitxpro/templatetags/render_bundle.py, mitxpro/tests/render_bundle_test.py, static/js/courseware_carousel.js, static/js/entry/django.js, static/js/entry/third-party.js, static/js/faculty_carousel.js, static/js/hero.js, static/js/image_carousel.js, static/js/notifications.js, static/js/testimonials_carousel.js, static/js/text_video_section.js, static/js/tooltip.js
https://github.com/mitodl/mitxpro/issues/2065
Defers js/css files that were blocking the main thread's execution while could be downloaded later.
=> defering possible js and css files

.coveragerc
https://github.com/mitodl/mitxpro/issues/2097
Adds a threshold to pytest's coverage acceptance criteria
=> add test coverage threshold

b2b_ecommerce/api_test.py, ecommerce/api_test.py, requirements.in, requirements.txt
=> asadiqbal08/Fix Flaky Tests

.coveragerc
Related to #2097 
Lowers the coverage threshold since it;s failing on some branches probably due to some rounding errors.
=> Lower coverage requirements to fix flakiness

ecommerce/mail_api_test.py, ecommerce/serializers.py, ecommerce/serializers_test.py, static/js/containers/pages/ReceiptPage.js, static/js/containers/pages/ReceiptPage_test.js, static/js/flow/authTypes.js, static/js/flow/ecommerceTypes.js, static/scss/receipt.scss, users/serializers.py
=> asadiqbal08/Receipt Updates Front end changes.

ecommerce/mail_api.py, mail/templates/b2b_receipt/body.html
=> Update B2B Email Receipt

cms/templates/certificate_page.html, static/scss/certificates/certificate.scss
https://github.com/mitodl/mitxpro/issues/2188
Changes content of program certificates
* Create a Program Certificate and match acceptance criteria of https://github.com/mitodl/mitxpro/issues/2188
* Make sure Course Certificates are not effected by this change.
**Program Certificate Web-View**:
**Program Certificate Printed-View:**
**Course Certificate Web-View**:
**Course Certificate Printed-View:**
=> changing text in program certificates

authentication/strategy.py, authentication/urls.py, authentication/views.py, pylintrc, requirements.in, requirements.txt, static/js/containers/pages/login/LoginForgotPasswordConfirmPage.js
Issue: https://github.com/mitodl/mitxpro/issues/2192
Dependabot PR: https://github.com/mitodl/mitxpro/pull/2160
Upgrades djangorestframework to 3.12.4, djoser to 2.1.0 and social-auth-app-django to 4.0.0
Test Login, Logout, Registration, Activation, and Password reset.
=> Upgrade djangorestframework to 3.12.4, djoser to 2.1.0 and social-auth-app-django to 4.0.0

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/pull_request_template.md
adjusting our PR template to remove autotag
=> remove autotag

static/js/components/forms/CheckoutForm.js, static/js/components/forms/CheckoutForm_test.js
fixes #2215 
update refund policy link in checkout page to `https://xpro.mit.edu/terms-of-service/#registration`
Just visit the refund policy link on checkout page that should be updated
=> update refund policy link in checkout page

package.json, static/js/components/forms/ProfileFormFields.js, yarn.lock
=> Property-expr (Yup) version bump

requirements.in, requirements.txt
N/A
This updates the digital credentials app dependency to try to fix some issues seen on RC.
It's not practical to test this locally and the code isn't user facing atm.
=> Update digital-credentials dependency

requirements.in, requirements.txt
#2238 
- *Fixes the security alert for [urllib3](https://github.com/mitodl/mitxpro/security/dependabot/requirements.txt/urllib3/open)
- It was mandatory to update `sentry-sdk`, `Boto3`, and `requests` to take the 'urllib3' to the required version.
- Modules that depend on or use any of the aforementioned packages e.g. File uploaded.
=> build: upgrade boto3, sentry-sdk and requests to fix urllib3 alert

package.json, yarn.lock
=> Update mocha for diff dependency upgrade

package.json, yarn.lock
https://github.com/mitodl/mitxpro/issues/2287
Upgrades glob-parent to 5.1.2
Test if everything is working
=> upgrade glob-parent to 5.1.2

requirements.in, requirements.txt
fixes: #2362
Recent upgrade of Django==3.2 is requiring to have updated version of django-storage as the issue occurred over RC while uploading images to AWS bucket.
Exception occurring over RC:
```
2022-03-08T21:37:59.521916+00:00 app[web.1]: module = import_module(module_path)
2022-03-08T21:37:59.521918+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
2022-03-08T21:37:59.521918+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-03-08T21:37:59.521918+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2022-03-08T21:37:59.521919+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2022-03-08T21:37:59.521919+00:00 app[web.1]: File "<frozen …
```
=> Upgrade django-storage

static/js/containers/pages/DashboardPage.js
fixes #2361 
Digital Credentials: UI Changes for DCC integration
=> Digital Credentials: UI Changes for DCC integration

docs/configure_open_edx.md
Closes #2465
Updates the edx setup docs to work with the `maple` branch of openedx
Follow the instructions and see if everything works
=> Update openedx setup doc

requirements.txt
Closes #2510 
Updates new relic to 8.0.4
Nothing should break, app should start up.  This is best tested on RC where NewRelic can be tried out.
=> upgrade newrelic

cms/models.py, cms/models_test.py, courses/models.py
None for now.
Optimizes queries for the Course and Program Pages.
Visit the Program and Course Detail pages. Verify that everything remains the same with and without these changes.
=> Reduce Product page queries

cms/models.py
Initial PR for https://github.com/mitodl/mitxpro/issues/2530.
- This PR is just a quick fix for the Catalog page so that current performance improvements are not compromised in the master branch.
- It fixes the performance degradation of the Catalog page due to the changes in the Product page performance improvement under https://github.com/mitodl/mitxpro/pull/2502
- The product pages still contain a few N+1 queries and work on that is under progress and should be fixed in a follow-up PR that is https://github.com/mitodl/mitxpro/pull/2531
- Make sure you have enough data for the Catalog and the Product CMS pages.
- Visit the catalog page. Monitor queries at `/silk/requests/`. No N+1 queries should be there.
- Visit the Course Detail page. It should work fine. Query optimization won't be …
=> fix: Catalog page performance

.github/workflows/ci.yml, .github/workflows/production.yml, .github/workflows/release-candiate.yml
Closes #2496 
Replaces `ubuntu-latest` with `ubuntu-22.04` in github action yaml files
Tests should pass here.
=> Change ubuntu-latest to ubuntu-22.04

.github/workflows/new-issues.yml
N/A
N/A
This adds a github action workflow to add new issues to a [global project on the hq repo](https://github.com/orgs/mitodl/projects/21/views/1) so we can triage them properly before starting on them.
Can't test until it's on `master`, but you can see the same workflow setup on this test repo:
https://github.com/mitodl/workflow-testing/blob/main/.github/workflows/new-issues.yml
And a successful run of that here:
https://github.com/mitodl/workflow-testing/actions/runs/4048796451
Note: the issue this ran for has since been removed from the project.
=> Add a workflow for new issues

cms/models.py, cms/templates/home_page.html, cms/templates/partials/catalog-topics-section.html, cms/views_test.py, courses/factories.py, courses/models.py, static/js/catalog-topics-carousel.js, static/js/entry/django.js, static/scss/detail/catalog-topics.scss, static/scss/detail/common.scss, static/scss/layout.scss
https://github.com/mitodl/mitxpro/issues/2590
Adds a new section for course topics on the home page.
- Visit the xPro Homepage.
- Make sure that the changes are as per the designs.
- Make sure that the links redirect to the catalog page.
- Slider is visible for all screens when topics are more than 6.
- Slider is visible for small screens when topics are 6 or fewer.
=> feat(homepage): add course topic section

authentication/pipeline/user.py
#2489 
Fixes the `duplicate email exception returns 500` on the register page
- Visit the `xpro` locally
- Click on the `Create Account` button
- Enter email address
- Open the email and click on verify email
- Enter details in the form and click the `Continue` button
- Now click the browser's back button and re-enter the detail
- Click the `Continue` button again
- Validate you'll see no errors and you'll continue to the next page
=> fix: UserCreationFailedException

ecommerce/serializers.py, ecommerce/views.py, ecommerce/views_test.py, static/js/containers/pages/CheckoutPage.js, static/js/containers/pages/CheckoutPage_test.js
This is a follow-up on **https://github.com/mitodl/mitxpro/pull/2585**. This is based on a discussion about external products being sellable after https://github.com/mitodl/mitxpro/pull/2585 change. A related comment is posted https://github.com/mitodl/mitxpro/issues/2581#issuecomment-1482731388
None, Inspired by https://github.com/mitodl/mitxpro/issues/2581#issuecomment-1482731388. Not allowing external products to be sold or shown in products API.
- Adds validation for external products on checkout, adds an appropriate message
- Hides the external products from `API/products`
- First, On master, Create a Product, and an external Course
- Now manually hit a URL something like `http://xpro.odl.local:8053/checkout/?product=<external course's product ID>`
- The checkout page should show - …
=> fix: don't allow external products to be sellable

requirements.txt
https://github.com/mitodl/mitxpro/security/dependabot/92
- Fixes: Unintended leak of Proxy-Authorization header in requests
- Tested the register Recaptcha
- account created on edX through xpro register form
- tested duplicate username issue on edX which uses requests `get_existing_openedx_user`
=> fix: Unintended leak of Proxy-Authorization header in requests

cms/migrations/0066_fix_revision_content.py
Fix for https://github.com/mitodl/mitxpro/pull/2846
Fixes the migration to filter the custom revisions that we added using the migrations.
- Testing Broken State (As RC is Broken):
- Remove existing containers
- Checkout the `release` branch(Release does not contain the upgrade changes)
- Run the migrations, then run `configure_wagtail` command
- Now there won't be any PageRevision objects.
- Create PageRevision for Blog and Webinar Index Pages using the below code
```
from wagtail.core.models import PageRevision, Page, Site
from cms.models import WebinarIndexPage, BlogIndexPage
from django.contrib.contenttypes.models import ContentType
import json, datetime, pytz
site = Site.objects.filter(is_default_site=True).first()
home_page = Page.objects.get(id=site.root_page.id) …
```
=> fix: filter revision created by wagtail

conftest.py
None
Improves a fixture that creates the index pages.
Checks should pass.
=> test: improve test fixture

cms/forms.py, cms/models.py, cms/models_test.py, ecommerce/admin.py, ecommerce/models.py, ecommerce/wagtail_hooks.py, ecommerce/wagtail_views.py, fixtures/common.py
Fixes https://github.com/mitodl/hq/issues/2764
- Adds the ability to update the Courseware pricing in the CMS pages.
- Add a view of Products and ProductVersions in the CMS.
- Create a few courses and programs (External and Internal)
- Create course runs for the courses.
- Create CMS Pages for the courseware objects.
- Edit a CoursePage or an ExternalCoursePage. Verify that you can see a price change section. You should find a course runs dropdown and a price decimal field.
- Select a course run and add a price. Publish the page.
- Now verify that the Product is created if it does not exist and a new product version is created for the course run.
- The updated price should be visible to the learner and in the checkout process.
- Now edit a ProgramPage or an ExternalProgramPage.
- Verify …
=> feat: change courseware pricing in CMS

package.json, static/js/components/forms/ProfileFormFields.js, static/js/containers/pages/profile/ViewProfilePage.js, static/js/lib/api.js, yarn.lock
This PR restores the changes from PR https://github.com/mitodl/mitxpro/pull/3013 which were [reverted](https://github.com/mitodl/mitxpro/pull/3044) due to an urgent release.
=> Restore "fix(deps): update dependency ramda to ^0.30.0 (#3013)"

package.json
None
This PR removes package manager from package.json to fix the renovate artifact issue
=> temp: remove package manager from package.json

.github/workflows/ci.yml, docker-compose.yml, package.json
None
Upgrade Node to v20
- Checks should pass
- Smoke test everything
=> chore: upgrade node to v20

.secrets.baseline, ecommerce/constants.py, ecommerce/management/commands/invalidate_payment_coupons.py, ecommerce/permissions.py, ecommerce/urls.py, ecommerce/utils.py, ecommerce/utils_test.py, ecommerce/views.py, ecommerce/views_test.py, fixtures/common.py, mitxpro/templates/index.html, mitxpro/urls.py, mitxpro/views.py, mitxpro/views_test.py, static/js/components/forms/CouponDeactivateForm.js, static/js/components/forms/CouponDeactivateForm_test.js, static/js/constants.js, static/js/containers/pages/admin/DeactivateCouponPage.js, static/js/containers/pages/admin/DeactivateCouponPage_test.js, static/js/containers/pages/admin/EcommerceAdminPages.js, static/js/global_init.js, static/js/lib/queries/ecommerce.js, static/js/lib/urls.js, static/scss/ecommerce-admin.scss, static/scss/variables.scss
Closes https://github.com/mitodl/hq/issues/5435
This PR adds the functionality to deactivate the coupons from ecommerce/admin UI
While submitting the button is disabled
If all the codes and names entered are invalid 
- Go to http://localhost:8053/ecommerce/admin/deactivate-coupons/
- Enter the coupons names you want to deactivate. Each coupon at separate line. Submit the form
- Go to http://localhost:8053/admin/ecommerce/coupon/ and validate that the enable field of the coupons entered in the step  above is set to False
- Try to use the coupon in a checkout. You should get `Enrollment / Promotional Code 'coupon-code' is invalid` error
- More details regarding access control: https://github.com/mitodl/hq/issues/5435#issuecomment-2400206915
=> feat: add coupons deactivate form

package.json, yarn.lock
=> Revert "fix(deps): update dependency sass to ~1.79.0"

package.json
none
removes unused https://github.com/jonschlinkert/mixin-deep
- verify that the usage.
- checks should pass
=> chore: remove unused dep mixin-deep

courses/admin.py
None
Improves performance of Course and CourseRun admin list views.
- Checkout master and visit `http://xpro.odl.local:8053/admin/courses/course/` and `http://xpro.odl.local:8053/admin/courses/courserun/`
- Monitor the queries at /silk/requests/
- Checkout this branch and monitor the results.
- Nothing should break
=> perf: select related objects for course and courserun admin

package.json
none
Remove unused package [set-value](https://github.com/jonschlinkert/set-value)
- verify the usage.
- checks should pass
=> chore(deps): Remove unused package 'set-value'

renovate.json
Fixes https://github.com/mitodl/mitxpro/issues/2838
Fixes renovate json as described in the issue.
Renovate should open new PRs after merge?
=> fix: replace matchPackages with matchPackageNames

hubspot_xpro/tasks_test.py
Closes https://github.com/mitodl/mitxpro/issues/3305
Reduces test execution time for test_batch_upsert_hubspot_objects by 700%.
Reduces overall test execution time by ~15%
- Checks should pass
=> chore: improve tests execution time for hubspot

mitxpro/utils.py, mitxpro/utils_test.py, static/js/components/TopAppBar.js, static/js/components/TopAppBar_test.js, static/js/containers/App.js, static/js/containers/HeaderApp.js, static/js/flow/declarations.js
Closes https://github.com/mitodl/hq/issues/6370
Removes feature flag COURSE_DROPDOWN
- Courses dropdown with topics should be visible in the header without any issues.
=> refactor: remove COURSE_DROPDOWN flag

.secrets.baseline, mitxpro/settings.py, sheets/conftest.py, sheets/dev-setup.md, sheets/views.py
Closes https://github.com/mitodl/hq/issues/6374
Removes flag COUPON_SHEETS
- I don't have sheets setup, @arslanashraf7 might have to cover it up for me.
=> refactor: remove COUPON_SHEETS

courses/docs/external-course-sync.md, mitxpro/utils.py
None
Adds external course sync documentation to explain what we do during the external course sync.
=> docs: add external course sync documentation
